### ISSUE TITLE
[Sandbox] Clusternet (RESUBMISSION)

### ISSUE THREAD

**Issue by dixudx** [cncf/sandbox#10]
### Application contact emails

stephenhsu90@gmail.com

### Project Summary

Managing your Kubernetes clusters (including public, private, edge, etc) as easily as visiting the Internet

### Project Description

Clusternet is an open-source project that helps users manage multiple Kubernetes clusters as easily as 'visiting the Internet' (thus the name 'Clusternet'). It is a general-purpose system for controlling Kubernetes clusters across different environments as if they were running locally.

### Org repo URL

https://github.com/clusternet

### Project repo URL

https://github.com/clusternet/clusternet

###  Project Updates Since Last Review 🌟🌟🌟

- We've released 14 major releases so far, attracting 30+ contributors from Tencent, intel, ByteDance, Ant Group, Kanzhun, Purple Mountain Laboratories, Dmall, KuGou, Futu, WeBank, QQ Music, 37Games, etc.
- This is not a one-person project any more. More contributors participate in our release. For recent releases, 10+ contributors get participated in a release. Another exciting thing is that we've got more new contributors to join with us. Moreover, we have a bi-weekly regular meeting with other contributors from other companies.
- Clusternet gets stars over 1k. More and more people are watching and using this projects. We do receive many requests from other companies, such as CMCC, Kanzhun. They give us great support on moving forward.
- Within Tencent, we're using Clusternet managing hundreds of Kubernetes clusters, with a total of 1 million CPU cores. And this number keeps growing.
- We introduced this project on Open Source Summit Euro 2022 as well, where we shared some updates and performance benchmarks on using Clusternet to manage Kubernetes clusters running at the edge.
- More integrations. We make integrations with other CNCF projects, such as [mcs-api](https://github.com/kubernetes-sigs/mcs-api), [cluster-api](https://github.com/kubernetes-sigs/cluster-api), [node-feature-discovery](https://github.com/kubernetes-sigs/node-feature-discovery), [prometheus](https://github.com/prometheus/prometheus), [kyverno (ongoing)](https://github.com/kyverno/kyverno), [submariner (ongoing)](https://github.com/submariner-io/submariner), etc. There will be more integrations like these in the next following releases.
- More frameworks. With the help of many contributors, Clusternet gets the capability to work with multiple scheduling scenarios, such as dividing scheduling (static and dynamic), subgroup scheduling. We build multiple frameworks (scheduling framework, predictor framework) to plumb out-of-tree plugins/implementations.

### Website URL

https://clusternet.io

### Roadmap

https://github.com/clusternet/clusternet/blob/main/ROADMAP.md

### Contributing Guide

https://github.com/clusternet/clusternet/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/clusternet/clusternet/blob/main/CODE_OF_CONDUCT.md

### Maintainers file

https://github.com/clusternet/clusternet/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

By joining CNCF, we want to motivate more innovation and participation from the open-source community. Some significant values joining CNCF could bring to the project are:

- Be vendor-neutral: Clusternet can get a neutral home in CNCF, to facilitate further project development through a more diverse and neutral community.

- Be more aware: leverage CNCF to promote the project and get more users and contributors through official events, mailing lists, blog posts, etc.

We also believe that Clusternet could be an excellent addition to the existing CNCF landscape. Clusternet is based on Kubernetes, and it is a significant attempt to tackle the multi-cluster Kubernetes management challenge.

### Benefit to the Landscape

As Kubernetes gets adopted by large organizations, the demand for multi-cloud and multi-cluster have become prominent to offer better scalability, stability, and cost-saving.

Clusternet is built to address these challenges. It provides an easy-to-operate tool that extends (instead of replaces) Kubernetes. Clusternet naturally supports all the native Kubernetes APIs and fits well in the cloud-native ecosystem.

Clusternet is a decent effort to stitch multiple Kubernetes cluster into a single one. Clusternet turns an existing Kubernetes cluster to a multi-cluster control plane, while keeps the original cluster untainted. We've done a lot of work to make that happen. Clusternet adopts a novel approach to solve multi-cluster problems. This is the biggest difference that makes Clusternet outstanding when comparing with other similar projects.

### Cloud Native 'Fit'

Multi-cluster management has been an open issue since the early day of the cloud-native movement. Clusternet is based on Kubernetes, and it is a significant attempt to tackle the multi-cluster Kubernetes management challenge.

### Cloud Native 'Integration'

Clusternet can be easily integrated with various cloud native projects to build a powerful multi-cluster Kubernetes platform.

- Clusternet provides build-in support for [Helm](https://www.cncf.io/projects/helm/) to coordinate Helm Chart applications across multiple clusters.
- Multiple clusters monitoring is straightforward with [Prometheus](https://www.cncf.io/projects/prometheus/) and [Grafana](https://github.com/grafana/grafana). Registered to Clusternet, each cluster obtain its ID and labels following unified naming convention.
- Cross-cluster service mesh can be achieved by integrating with [Linkerd](https://www.cncf.io/projects/linkerd/), [Istio](https://www.cncf.io/projects/istio). [Submariner](https://www.cncf.io/projects/submariner/) can be used to create an overlay network for cross-cluster connection and service discovery.
- In Clusternet, clusters creating by [cluster-api](https://github.com/kubernetes-sigs/cluster-api) will be discovered automatically and registered to parent cluster. Auto-labelling for managed clusters is also available now. By integrating [mcs-api](https://github.com/kubernetes-sigs/mcs-api), multi-cluster services are discoverable and accessible across clusters with a virtual IP.

Existing CNCF projects can leverage Clusternet to enhance their multi-cluster management capabilities.

### Cloud Native Overlap

N/A

### Similar projects

- kubefed
- [OCM](https://github.com/open-cluster-management-io)
- [Karmada](https://github.com/karmada-io/karmada)

### Product or Service to Project separation

N/A

### Project presentations

CNCF TAG-Runtime (on Feb 17th, 2022):
- [Meeting Note](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#)
- [Meeting Recording](https://youtu.be/coZ2JjaguWQ)

**Comment by dims** [comment]
Hi @dixudx, back from April! https://lists.cncf.io/g/cncf-toc/message/6861

```
Clusternet: TOC would like to see more people who are active in the project actively doing PRS and reviews and issues.
```

**Comment by TheFoxAtWork** [comment]
Hi @dixudx We're excited to see the increased contributions, however the Contributing guidelines on the site:https://clusternet.io/docs/contribution-guidelines/ looks like it needs some guidelines.

**Comment by dixudx** [comment]
> Hi @dixudx We're excited to see the increased contributions, however the Contributing guidelines on the site:https://clusternet.io/docs/contribution-guidelines/ looks like it needs some guidelines.

Hi @TheFoxAtWork Thanks for pointing it out. We've updated the contributing guidelines. PTAL.
