### ISSUE TITLE
[Sandbox] KubeVPN

### ISSUE THREAD

**Issue by wencaiwulue** [cncf/sandbox#102]
### Application contact emails

895703375@qq.com

### Project Summary

KubeVPN offers a Cloud-Native Dev Environment that seamlessly connects to your Kubernetes cluster network.

### Project Description

KubeVPN offers a Cloud-Native Dev Environment that seamlessly connects to your Kubernetes cluster network.

Gain access to the Kubernetes cluster network effortlessly using service names or Pod IP/Service IP. Facilitate the interception of inbound traffic from remote Kubernetes cluster services to your local PC through a service mesh and more.

For instance, you have the flexibility to run your Kubernetes pod within a local Docker container, ensuring an identical environment, volume, and network setup. With KubeVPN, empower yourself to develop applications entirely on your local PC!

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/kubenetworks

### Project repo URL in scope of application

https://github.com/kubenetworks/kubevpn

### Website URL

https://www.kubevpn.cn/

### Roadmap

none yet

### Roadmap context

KubeVPN is quite mature and the only roadmap is:
- Improve documentation and fix bugs

### Contributing Guide

https://github.com/kubenetworks/kubevpn/blob/master/README.md#Contributions

### Code of Conduct (CoC)

none yet (will reuse the CNCF one)

### Contributing or Sponsoring Org

https://github.com/kubenetworks/kubevpn/blob/master/README.md#Contributions

### Maintainers file

none yet, 3 maintainers

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [x] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

As a PaaS / DevOps sofeware engineer. I know it is so hard to startup Cloud Native Application on local PC. basicly the only way to develop our app is to build image and replace container image tag. So i develop a tools `KubeVPN`, it offers a Cloud-Native Dev Environment that seamlessly connects to your Kubernetes cluster network. Gain access to the Kubernetes cluster network effortlessly using service names or Pod IP/Service IP. Facilitate the interception of inbound traffic from remote Kubernetes cluster services to your local PC through a service mesh and more. For instance, you have the flexibility to run your Kubernetes pod within a local Docker container, ensuring an identical environment, volume, and network setup. With KubeVPN, empower yourself to develop applications entirely on your local PC!

### Benefit to the Landscape

If being part of CNCF gives more visibility to the project, then every people using apps in the CNCF landscape, and specifically Kubernetes sofeware engineer or DevOps engineer or Paas engineer , will benefit.

### Cloud Native 'Fit'

This project help many k8s engineer to develop their app quickly.

### Cloud Native 'Integration'

In proxy mode with service mesh, we using [envoy](https://github.com/envoyproxy/envoy) as data plane. and we make a control plane by envoy library. 

### Similar projects

https://github.com/telepresenceio/telepresence

### Landscape

Yes, here is [link](https://landscape.cncf.io/?item=app-definition-and-development--application-definition-image-build--kubevpn)

### Business Product or Service to Project separation

none i'm aware of

### Additional information

Don't forget to star the project if you like it :)
https://github.com/kubenetworks/kubevpn

**Comment by wencaiwulue** [comment]
@caniszczyk Can you help to evaluate this project ?

**Comment by TheFoxAtWork** [comment]
@wencaiwulue The TOC reviews sandbox applications roughly every 2 months. for more information on the Sandbox process, please refer to the README for this repo: https://github.com/cncf/sandbox/?tab=readme-ov-file#how-applications-are-reviewed

**Comment by angellk** [comment]
@wencaiwulue please coordinate a project presentation with [TAG Network](https://github.com/cncf/tag-network)

**Comment by TheFoxAtWork** [comment]
@wencaiwulue a few questions:
* while there is no maintainers file, it looks as though the maintainers are all from bytedance, is this correct?
* Telepresence (as indicated in the application) is the most similar existing CNCF project, however this project has been in sandbox since 2018 without significant momentum towards moving to incubation.  How do you see this project's adoption progressing towards incubation, particularly as many of these types of projects don't reach widespread adoption the way other projects in the ecosystem do and by this application's comments it is "quite mature"?

**Comment by wencaiwulue** [comment]
> [@wencaiwulue](https://github.com/wencaiwulue) a few questions:
> 
> * while there is no maintainers file, it looks as though the maintainers are all from bytedance, is this correct?
> * Telepresence (as indicated in the application) is the most similar existing CNCF project, however this project has been in sandbox since 2018 without significant momentum towards moving to incubation.  How do you see this project's adoption progressing towards incubation, particularly as many of these types of projects don't reach widespread adoption the way other projects in the ecosystem do and by this application's comments it is "quite mature"?

- Actually, the maintainers comes from individual developer. 
- "quite mature" is based on the project functions, it provide many function for developer to develop cloud native app. 
- Perhaps the reason why such projects are not widely known is due to the project itself, because they provide development environments and tools, which are generally used in development and testing environments. Unlike other components, it can be used in a production environment.
- Entering the sandbox can be known to more people and find more enthusiasts to maintain the project together.

**Comment by cathyhongzhang** [comment]
It seems this project is in the primitive stage. The functionalities provided on its project website are limited. It does not seem it has the potential to be widely adopted given its current shape.

**Comment by jberkus** [comment]
TAG Contributor strategy has reviewed this project and found the following:

* The [contributor guide](https://github.com/kubenetworks/kubevpn/blob/master/README.md#Contributions) is extremely minimal
* The project has no written governance, yet.
* The project has no roadmap, yet.
* There are no listed maintainers.  The project appears to have just one regularly active contributor.

This review is for the TOC’s information only.  Sandbox projects are not required to have full governance or contributor documentation.

**Comment by rochaporto** [comment]
@wencaiwulue @nicholasjackson did the TAG-Network presentation happen? I see the project's issue for it is closed but no link to any reference - also couldn't find a mention in the TAG-Network meeting notes.

If it did and it's just missing pointers, please @nicholasjackson leave a summary for a TAG recommendation.

**Comment by nicholasjackson** [comment]
We have not yet had the presentation but we are going to get this scheduled in the next month.

**Comment by TheFoxAtWork** [comment]
Thank you so much for the application, at this time the TOC has reviewed the project and found that it doesn't quite yet meet the expectations of a CNCF sandbox project.
Of note, the project is largely driven by a single maintainer, we'd like more active maintainers on the project

We recommend engaging TAG Network to build out the community around the project and re-apply in 6 months- 1 year depending on the continuing maturity of the project and activity of maintainership.
