### ISSUE TITLE
[Sandbox] OpenEBS - Promotion from Archive -> Sandbox

### ISSUE THREAD

**Issue by edrob999** [cncf/sandbox#104]
### Application contact emails

ed.robinson@gmail.com, brace.dave@gmail.com, tiagolobocastro@gmail.com, vishnu.attur@gmail.com

Also see [OpenEBS project leadership Maintainers team](https://github.com/openebs/community?tab=readme-ov-file#project-leadership-team)

### Project Summary

Cloud native storage

### Project Description

OpenEBS was accepted as a Sandbox project in 2019, then moved to archive in Feb 2024. For background on why, see [OpenEBS - why we were archived](https://docs.google.com/document/d/13T5cELI4f8N7CM1tIZS5cPKQMvGWN7Y1E__BJIesLvg/edit). The project team and sponsoring company have made changes in order to ensure the long term sustainability of OpenEBS. We are asking to unarchive the project, and are challenging ourselves to move forward in the CNCF maturity process. 

OpenEBS provides enterprise grade block storage for Kubernetes, enabling persistent resilient cloud native storage (storage is managed-from and contained-within a Kubernetes cluster). OpenEBS is popular, with >25,000 new clusters installed every month.
This is a re-application to Sandbox. Project was archived Feb 2024 after [TOC vote on 1051](https://github.com/cncf/toc/issues/1051). The team has listened to TOC feedback, [has made changes](https://github.com/openebs/openebs/issues/3701) , and is now seeking readmission to Sandbox.
Changes include:
- Archived older storage engines and consolidated engines from 11 to 4 (75 repos to 38), these are the actively maintained repos that will be further developed in the future.
- Reworked documentation
- Reworked all governance docs, and centralized to umbrella Community repo
- Rewrote project docs including Vision.md, Governance.md, Contributing.md
- Instituted processes inside the project, so people abide by the project docs
- Engaged with Linux Foundation brand counsel (DanielC) to bring DataCore’s commercial offering into compliance
- Project members attended KubeCon Paris, in order to engage with the community on how best to proceed reapplying for sandbox in the most efficient manager possible - we’ve been working with the CNCF Projects team to help us meet the requirements. (ChrisA and JorgeC)
- Educated the sponsoring organization on open source and CNCF policies and procedures
- Assigned a CNCF liaison (Ed Robinson), who reports to DataCore CEO to represent the project and take guidance from the TOC
- The team hopes to gain admission to Sandbox soon, then work with CNCF towards incubation, then graduation.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/openebs 

### Project repo URL in scope of application

https://github.com/openebs/openebs

### Additional repos in scope of the application

The new OpenEBS project consists of 5 Storage Engines. The strategy is to eventually unify all 5  into 1 platform. There are sub repos & dependencies, 1 sub project & 1 critical external fork dependency. The team took advice from TOC, and advised community, then deprecated, then moved tech-debt of 44 legacy repos to [openebs-archive org](https://github.com/openebs-archive) based on guidance from @caniszczyk and @castrojo. - Our new [repo structure](https://github.com/openebs#project-structure) is listed below, with engines listed in order of User Adoption:

| Name | Project Repos |
|-------|---------------|
|Community                       | https://github.com/openebs/community/
|Local PV Hostpath           | https://github.com/openebs/dynamic-localpv-provisioner
|Local PV ZFS                    | https://github.com/openebs/zfs-localpv
|Local PV LVM                   | https://github.com/openebs/lvm-localpv
|Replicated PV Mayastor  | https://github.com/openebs/mayastor
|                                          | https://github.com/openebs/mayastor-control-plane
|                                          | https://github.com/openebs/mayastor-extensions
|                                          | https://github.com/openebs/spdk-rs
|SPDK fork w/OpenEBS patches | https://github.com/openebs/spdk
| Local PV Rawfile     | https://github.com/openebs/rawfile-localpv

Note: SPDK patches are available to the community

### Website URL

https://openebs.io
https://openebs.io/docs

### Roadmap

https://github.com/openebs/openebs/blob/main/ROADMAP.md

### Roadmap context

The new project roadmap & strategy is to eventually unify 5 Storage Engines into 1 single Storage platform. This is a major project change compared to the old roadmap, which did not provide enough attention and focus on the 4 Local PV engines. The team acknowledges this lack of focus which created a stale & disappointed community with low contributions.

The team has defined a [VISION doc](https://github.com/openebs/community/blob/develop/VISION.md) as part of the new GOVERNANCE structure that supports the roadmap and helps guide the Team, the contributors and the community.

### Contributing Guide

https://github.com/openebs/community/blob/develop/CONTRIBUTING.md 

### Code of Conduct (CoC)

https://github.com/openebs/community/blob/develop/CODE_OF_CONDUCT.md

### Adopters

https://github.com/openebs/community/blob/develop/ADOPTERS.md

### Contributing or Sponsoring Org

https://www.datacore.com/

### Maintainers file

https://github.com/openebs/community/blob/develop/MAINTAINERS 

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

OpenEBS was accepted as a Sandbox project in 2019, then moved to archive in Feb 2024.

We have re-examined why we want to continue to contribute to CNCF. Here is why:
- CNCF as an organization is able to protect, guide and nurture the Kubernetes open
source platform.
- Under CNCF’s guidance & governance OpenEBS aims to democratize persistent
storage for K8s for a wide range of use cases.
- Aligning with CNCF’s mission, OpenEBS can leverage CNCF’s community and
guidance to drive innovation, adoption, and growth.
- Thousands of clusters trust OpenEBS to reliably manage persistent data in K8s.
- The Team is proud of the progress, and being able to work with cloud-native
adopters, together we are innovating and enabling the community for the future.

### Benefit to the Landscape

Key benefits of OpenEBS are:
- Resilient and reliable data management capabilities within Kubernetes
- Software-defined, container-native and device agnostic
- Seamless migration capabilities of legacy deployments to Kubernetes

### Cloud Native 'Fit'

OpenEBS is cloud native storage which enables K8s stateful apps with persistent block storage.

### Cloud Native 'Integration'

Kubernetes
Containerd
KubeVirt
Kubernetes
Etcd
NATS
HELM
gRPC
Jaegar
OpenTelemetry
Prometheus
Open Telemetry

### Cloud Native Overlap

Longhorn (storage)
CubeFS (storage)
Rook/Ceph (storage) 

### Similar projects

Longhorn (storage)
CubeFS (storage)
Rook/Ceph (storage) 

### Landscape

Cloud Native Storage

### Business Product or Service to Project separation

The sponsoring company, DataCore offers premium support services to OpenEBS adopters and production users.
The company plans to release a future offering to provide enhanced enterprise management solutions complementing OpenEBS.
The prior commercial offering “openEBS Pro” had trademark issues with Linux Foundation and has been withdrawn.

### Project presentations

Prior to project-archiving, OpenEBS has participated with TAG Storage. The Team met once with TAG Storage post archiving in July 2024.

### Project champions

Jorge Castro
Chris Aniszczyk

### Additional information

OpenEBS production installations
- Microsoft uses OpenEBS in Azure Container services
- CIVO uses OpenEBS as the basis for their CSP offerings
- Flipkart, India’s largest eCommerce service has relied on OpenEBS for their storage
- Replicated's Embedded Cluster and kURL products use OpenEBS as the default
storage provider.
- … and more

The Team has accepted the feedback and adopted changes recommended by the TOC in February 2024.
While OpenEBS is in Archive, the users are uncertain of the project’s future, and the future of their own software that depends on OpenEBS.
We request TOC to consider OpenEBS for a promotion to Sandbox, the Team commits to work with CNCF guidance to develop and execute a plan to move the project to its next level.

**Comment by edrob999** [comment]
adding prefix [Sandbox]

**Comment by edrob999** [comment]
Update: Project team presented to Tag Storage today (7/24). 
**[Link to Presentation](https://docs.google.com/presentation/d/1AxulTY3zWbOf5N4qf23xSCwteCFB0AIjwoN9OsqA9Ak/edit#slide=id.p)**

**Comment by edrob999** [comment]
**Update2:** Since beginning of June, OpenEBS has held weekly maintainer meetings, and minute the meetings, for transparency. [Minutes of the weekly meetings are here](https://github.com/openebs/community/discussions/categories/weekly-maintainers-meetings)

**Comment by angellk** [comment]
@edrob999 Are the meetings recorded? Please link the recording location.

**Comment by edrob999** [comment]
Sorry @angellk - b/c project is in archive, most CNCF project resources were turned off. [See Reference](https://github.com/cncf/toc/issues/1250). We've got some access, but not Zoom or ability to publish community mtgs on CNCF calendar yet. For now, we're using free Google Meet, no recording capability, we're announcing the community mtgs on Slack.  Looking forward to getting full access to the project resources again!

**Comment by angellk** [comment]
Hi @edrob999 - many open source projects are not part of an official foundation and do record and upload to various channels for community engagement, including google drive or video channels. The free version of Zoom [allows local recording](https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0063640) to upload anywhere (including YouTube). 

As your project is applying to be promoted from archive, I was interested to see how community meetings are held, how features are discussed, as well as open discussion around the roadmap. Please update if you are able to record community sessions.

**Comment by edrob999** [comment]
Hi @angellk. If this is "critical" for our sandbox application,  let me know - we'll cancel the existing community mtgs and set them up using free Zoom, although recording is limited to 40 mins.  I would prefer we set the vid recording up after we've been accepted to Sandbox and have access to the CNCF Zoom. But let me know - we are happy to take guidance, and are making a genuine effort for transparency. Ed

**Comment by angellk** [comment]
Thank you @edrob999 - having a way for community members to engage with your community meetings would be great - and being able to view the recordings is one way to do that. 

Please connect with TAG Contributor Strategy - if you have not already done so - for guidance on building your community.

Also, please update your README and Community Pages for accuracy and to communicate access to your community meetings. I cannot locate a resource that shows how to join your community meetings live.

**Comment by edrob999** [comment]
@angellk - good points, I'll make the change to ReadMe as you suggest. I need to push back on switching to recorded Zoom for our community meeting this week (DM me if you want to talk thru it), we do understand the importance of the recordings.

Following @TheFoxAtWork suggestion, I joined **Tag Contributor Strategy(governance)** working group about 3 weeks ago, both to help OpenEBS, and to contribute. We did a verbal review with @riaankleinhans, @jberkus, @geekygirldawn. Like all projects we have stuff to work on. 

Within the project leadership, I have the most interest in governance/contributor strategy.
After reviewing with Tag, my four priorities are:
1. Contributor Ladder / path-to-maintainer. I wrote it. I thought it was clear. I was wrong. I have a PR in-review to improve clarity. We then need to put the policy into practice, and sustain this effort.
2. Ensuring transparency and easy-to-find resources (we have too much documentation, and it needs to be organized better for people to find).
3. Growing contributor base + external maintainers. In the last year, we had contributions from 21 sponsor, and 44 non-sponsor people. We will apply energy to grow non-sponsor contributors + maintainers.
4. Cementing processes with project sponsor (DataCore) to ensure independent governance, and both sponsor + project have well understood boundaries

All of these require work, and I wish progress was faster. Most important for me is to ensure improvements "stick", beyond the tenure of myself + other individuals. I believe our current project governance already compares well against Sandbox projects. But we have more work to do, and I appreciate ongoing guidance and best practices as the project moves forward.

Ed

**Comment by edrob999** [comment]
@angellk: We revised the org Readme, so community meetings are easier to find (including the next meeting): 
https://github.com/openebs/#monthly-community-meeting

The vid from last week's meeting is here: https://www.youtube.com/watch?v=CjjqzrPGxVU

The links to the vids, plus minutes from weekly maintainers meetings are all in the openEBS Community repo discussions:
https://github.com/openebs/community/discussions

**Comment by edrob999** [comment]
Reviewing the document, fixed some typos. May fix some more

**Comment by edrob999** [comment]
The maintainers asked for some language changes made to the submission [tracked in this GitHub issue](https://github.com/openebs/community/issues/92). 
The change includes removing names of supporters we didn't ask permission from (an honest mistake)

**Comment by DMajrekar** [comment]
Best of luck with the Sandbox Application, we all see the work you're putting in, and Civo relies on OpenEBS for Civo Platform, used by hundreds of companies

**Comment by Zman2356** [comment]
In February when CNCF archived OpenEBS, we committed to making changes, and re-applying.

This Sandbox application is the first step: we addressed the technical issues and re-worked project governance (including maintainer lifecycle). We put in place transparency: the project is now publishing minutes of regular maintainer meetings, videos of community meetings.

If the Sandbox application is approved, the second step comes next: DataCore commits to ensuring OpenEBS becomes a true community project, with a growing contributor base, and a diverse group of maintainers leading the project. We will work with CNCF to make this happen as the project moves towards incubation then graduation.

Dave Zabrowski
CEO, DataCore Software

**Comment by croomes** [comment]
Microsoft supports the OpenEBS application to Sandbox. Azure Container Storage is based in part on several OpenEBS components. We are talking with the maintainers about how Microsoft can contribute back to the project.

**Comment by chira001** [comment]
The TAG Storage review is here: https://docs.google.com/document/d/1Biq0gWG8o2npNfjvUiM4WIeFuM9o3I1ZQMDBXz28YAY/edit

**TAG recommendation to TOC: 
Storage TAG recommends YES for sandbox.**

**Comment by mrbobbytables** [comment]
Project has been given the okay to move to a vote in [today's sandbox review](https://github.com/cncf/toc/issues/1427)
/vote

**Comment by TheFoxAtWork** [comment]
As part of my vote in favor of this project I would like to call attention to an important consideration for the project's future success in CNCF:

Ed has been instrumental in bringing the OpenEBS project into alignment with CNCF expectations of sandbox projects. He has engaged CNCF staff and several community members on direction and next steps for the project towards potential incubation-level maturity. The project's current efforts have been largely shouldered by Ed and a few others. 

However as with all concerns regarding projects survivability of the lottery factor, it will be paramount to OpenEBS's continued progress that additional community members of OpenEBS step into active leadership roles for the project to more healthfully distribute those efforts beyond a single individual.

**Comment by niladrih** [comment]
!!!

I had a question: What do we do next? Is there a PR we could raise? Sorry if there's some doc I missed. Thanks :).
Tagging @chira001.

**Comment by angellk** [comment]
> Great!
> 
> I had a question: What do we do next? Is there something the OpenEBS maintainers could do to help? Sorry if there's some doc I missed. Thanks :). Tagging [@chira001](https://github.com/chira001).

Hi @niladrih - an onboarding issue will be opened by the CNCF onboarding team. Cc: @krook

**Comment by Cmierly** [comment]
Congrats on being accepted back into Sandbox from Archived!
Here is your onboarding checklist: https://github.com/cncf/sandbox/issues/299

If you have any questions, please don't hesitate to reach out!

**Comment by mrbobbytables** [comment]
With the onboarding issue created, we can go ahead and close this out. :)
Congrats again!
