### ISSUE TITLE
[Sandbox] alustan

### ISSUE THREAD

**Issue by ChichiCaleb** [cncf/sandbox#110]
### Application contact emails

chichiuchenna@gmail.com

### Project Summary

End to end continuous delivery orchestrator

### Project Description

Alustan leverages concept proposed by tools like Score, Kubevela, Crossplane, IAC controllers, helm, argocd and it's intricate capabilities to build a unified end to end continuous delivery orchestrator without sacrificing flexibility

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/alustan

### Project repo URL in scope of application

https://github.com/alustan/alustan

### Roadmap

https://github.com/alustan/alustan/blob/main/roadmap.md

### Contributing Guide

https://github.com/alustan/alustan/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/alustan/alustan/blob/main/CODE_OF_CONDUCT.md

### Maintainers file

https://github.com/alustan/alustan/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We strongly believe that the project will be of immense help to platform engineering teams and their overall goal of setting up a functional Internal Developers Platform so being part of CNCF will definitely foster awareness and adoption, above all get more hands to contribute and make the project better

### Benefit to the Landscape

There are projects in the landscape already tending towards solving similar problem however they are either not providing a wholesome solution or pushes platform engineers to learn new syntax or totally new logic flow. Alustan leverages on popular and familiar tools used already in the ecosystem such as helm, terraform and argocd to orchestrate a fully functional IDP without sacrificing flexibility

### Similar projects

Crossplane
Kubevela

### Landscape

No

### Business Product or Service to Project separation

N/A

**Comment by angellk** [comment]
Hi @ChichiCaleb - it looks like your project application isn't ready yet. Could you please finish your application and resubmit? Looking forward to seeing your complete application!

**Comment by ChichiCaleb** [comment]
Thanks @angellk The project is up and running and can quickly be setup and tested on codespace https://github.com/alustan/alustan/blob/main/quick-setup.md

**Comment by ChichiCaleb** [comment]
Can this issue be reopened?

**Comment by ChichiCaleb** [comment]
Just started software development few months ago and this is my very first project, hoping to learn a lot from this whole process irrespective of the outcome
