### ISSUE TITLE
[Sandbox] OVN-Kubernetes

### ISSUE THREAD

**Issue by tssurya** [cncf/sandbox#111]
### Application contact emails

[suryaseetharaman.9@gmail.com](mailto:suryaseetharaman.9@gmail.com) ,
[gmoodalbail@nvidia.com](mailto:gmoodalbail@nvidia.com) , 
[trozet@redhat.com](mailto:trozet@redhat.com),
[jcaamano@redhat.com](mailto:jcaamano@redhat.com)

### Project Summary

A robust Kubernetes networking platform powered by Open Virtual Network (OVN) and OpenvSwitch at its core

### Project Description

OVN-Kubernetes is a robust Kubernetes Networking platform, built from the ground up by leveraging Open vSwitch (OVS) as the data plane, and Open Virtual Network (OVN) as the SDN Controller. The project focuses strictly on enhancing networking for the Kubernetes clusters and includes a wide variety of features that are critical to enterprise and telco users.

OVN-Kubernetes community members are active in upstream Kubernetes (particularly in SIG Network) to create new features and then realize them in OVN-Kubernetes. In addition to a feature rich platform, the project also aims to provide a highly scalable and performance CNI.

### Org repo URL (provide if all repos under the org are in scope of the application)

N/A

### Project repo URL in scope of application

https://github.com/ovn-org/ovn-kubernetes

### Additional repos in scope of the application

https://github.com/ovn-org/libovsdb

Projects used by OVN-Kubernetes at its core that are part of Linux Foundation:
https://github.com/ovn-org/ovn
https://github.com/openvswitch/ovs

### Website URL

https://ovn-kubernetes.io/ 

### Roadmap

https://github.com/orgs/ovn-org/projects/5/views/4

### Roadmap context

We use GitHub Milestones to plan our roadmap - 6 months at a time.
This planning is done with input from the community during our bi-monthly meetings.
[Version 1.0](https://github.com/ovn-org/ovn-kubernetes/releases/tag/v1.0.0) was released on June 14, 2024 and our [next release](https://github.com/ovn-org/ovn-kubernetes/milestone/3), 1.1 is planned for Q4 2024.

### Contributing Guide

https://ovn-kubernetes.io/governance/CONTRIBUTING/

### Code of Conduct (CoC)

https://ovn-kubernetes.io/governance/CODE_OF_CONDUCT/

### Adopters

https://github.com/ovn-org/ovn-kubernetes/blob/master/ADOPTERS.md

### Contributing or Sponsoring Org

Red Hat, NVIDIA

### Maintainers file

https://ovn-kubernetes.io/governance/MAINTAINERS/

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

The main reason for joining CNCF is to increase participation and diversify the OVN-Kubernetes community. By raising awareness about the project, we hope to increase the interest in the project and bring in more outside contributors. This will help us to become more vendor neutral as well.

### Benefit to the Landscape

Networking, especially in the context of SDN, is complicated. There are many networking projects out there that provide varying solutions for Kubernetes. OVN-Kubernetes is unique in that it provides feature differentiators that are leveraged in production to meet telco and enterprise use cases. We believe by being included in the CNCF landscape we can raise awareness about the OVN-Kubernetes networking platform, and provide users with features and solutions that are unavailable in the current solutions offered today. See [here](https://docs.google.com/presentation/d/1MkpwuIxwUP9jPmoj09kWQ2b-tPm1lXNeKXw7GNmvcy8/edit#slide=id.g2df9b4c42e3_0_192) for more details on our project's value add.

### Cloud Native 'Fit'

OVN-Kubernetes is designed specifically for Kubernetes and is running today on almost every cloud platform. It is built by Kubernetes contributors and follows the same design principles as other Kubernetes projects. It is fully compatible with the Kubernetes API and uses Custom Resource Definitions (CRDs) to expose its own APIs. It aims to tackle the challenges present in Kubernetes Cluster Networking Ecosystem: https://ovn-kubernetes.io/#challenges-for-cluster-networking-in-kubernetes-ecosystem.

### Cloud Native 'Integration'

As a Networking project, we’d like to build this project in the CNCF, with collaboration from other networking CNI projects that are trying to solve similar problems:

[Cilium](https://www.cncf.io/projects/cilium/)
[Project Calico](https://landscape.cncf.io/card-mode?category=cloud-native-network&project=hosted,member,no&grouping=category&selected=project-calico)
[Antrea](https://github.com/antrea-io/antrea)
[KubeOVN](https://github.com/kubeovn/kube-ovn/)

### Cloud Native Overlap

Of the projects listed above that we could complement, you may also consider that we might overlap a little with Antrea which uses OVS and KubeOVN which uses OVN and OVS:

However we already work in close collaboration with KubeOVN as outlined in the next section. We also collaborate with the other CNIs like Antrea in upstream sig-network working groups and infact work together to solve common problems like designing [AdminNetworkPolicy](https://network-policy-api.sigs.k8s.io/implementations/) API.

We plan to continue to work more closely with other CNIs moving forward.

### Similar projects

A Similar CNCF project is KubeOVN which was [founded](https://github.com/kubeovn/kube-ovn/pull/1) in 2019 while OVN-Kubernetes was founded in 2016. Both projects use OVN as their SDN controller but their architectures are different and KubeOVN community also works and contributes to the https://github.com/ovn-org/libovsdb that is hosted in our org.

### Landscape

No

### Business Product or Service to Project separation

Yes, Red Hat OpenShift Networking. Red Hat is known for its “upstream first” identity and with OVN-Kuberentes there is no exception. Any development done for the product is conducted upstream first, including working with and seeking approval of new features or patches from non Red Hat contributors in OVN-Kubernetes upstream community.

### Project presentations

Presented to TAG-Network on June 6th 2024. [Slides](https://docs.google.com/presentation/d/1MkpwuIxwUP9jPmoj09kWQ2b-tPm1lXNeKXw7GNmvcy8/edit#slide=id.p), [MeetingNotes](https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#bookmark=id.crmkkkocwfvz)

**Comment by TheFoxAtWork** [comment]
@nicholasjackson @leecalcote @zachbutcher Does the TAG have a recommendation regarding this project? From the notes there were two outstanding questions that were not answered in the notes.

**Comment by nicholasjackson** [comment]
Apologies, I have been out with flu, will update the DTR as soon as I am back. Both of the questions have been satisfied, the questions were only notes during the meeting and were covered on the call.

TAGNetwork recommend that OVN Kubernetes should progress to a TOC vote for sandbox inclusion, the project is already providing cloud scale solutions for a huge industry member and the wider community have much to gain from its inclusion.

**Comment by angellk** [comment]
@tssurya please link to the public discussion of LF's OVN org approving the transfer of OVN Kubernetes from OVN to CNCF - if application is approved.

**Comment by tssurya** [comment]
yup pasting the results of voting from OVN org's TSC committee: https://mail.openvswitch.org/pipermail/ovs-discuss/2024-July/053244.html

**Comment by cathyhongzhang** [comment]
OVN and Open vSwitch are quite mature solutions. It is great to see the integration of them with K8S.

**Comment by jberkus** [comment]
TAG Contributor strategy has reviewed this project and found the following:

* The [contributor guide](https://ovn-kubernetes.io/governance/CONTRIBUTING) is more complete than most Sandbox projects, including a Reviewer Guide as well
* The [governance](https://github.com/ovn-org/ovn-kubernetes/blob/master/GOVERNANCE.md) is a Maintainer Council, based on the CNCF template.
* The [roadmap](https://github.com/orgs/ovn-org/projects/5/views/4) is a project board, which appears to only set priorities for the next release
* There are five [maintainers](https://ovn-kubernetes.io/governance/MAINTAINERS/), four of whom work for Red Hat
* This project has been under Linux Foundation OVN Project for several years, and is applying to move to CNCF.

This review is for the TOC’s information only.  Sandbox projects are not required to have full governance or contributor documentation.

**Comment by mrbobbytables** [comment]
Project has been given the okay to move to a vote in [today's sandbox review](https://github.com/cncf/toc/issues/1427)
/vote

**Comment by Cmierly** [comment]
Congrats on being accepted into the CNCF Sandbox!
Here's a link to your onboarding checklist: 
https://github.com/cncf/sandbox/issues/302

If you have any questions or concerns, please don't hesitate to reach out!

**Comment by mrbobbytables** [comment]
With the onboarding issue created, we can go ahead and close this out. :)
Congrats again!

**Comment by tssurya** [comment]
Posting the results of libovsdb voting by OVN TSC: https://mail.openvswitch.org/pipermail/ovs-discuss/2024-November/053376.html for ensuring we have paper trail, sorry that project's vote was separate from the main voting we did.
