### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] Shipwright

### ISSUE THREAD

**Issue by Cmierly** [cncf/sandbox#131]
# Welcome to CNCF Project Onboarding!

This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.

We would like your project to complete onboarding within one month of acceptance.

Please track your progress by using "Quote reply" to create your own copy of this checklist in an issue, so that you can update the status as you finish items.

## Review and understand

- [x] The [Technical Leadership Principles](https://github.com/cncf/toc/blob/main/PRINCIPLES.md#technical-leadership-principles) that outlines the expected behavior for any maintainer in a leadership role.
- [x] The [project proposal process and requirements](https://github.com/cncf/toc/blob/main/process/README.md).
- [x] The [services available for your project at the CNCF](https://contribute.cncf.io/resources/project-services/).
- [x] The [CNCF IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).
- [x] The [trademark guidelines](https://www.linuxfoundation.org/legal/trademark-usage).
- [x] The [license allowlist](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist).
- [x] The [online program guidelines](https://github.com/cncf/foundation/blob/main/online-programs-guidelines.md).
- [x] Optional: [Book time with CNCF staff](http://project-meetings.cncf.io) for any onboarding questions.

## Contribute and transfer

- [x] Move your project to its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account. If it's already in a GHE account, you will need to remove it from that first.
- [x] Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project.
- [x] Migrate your Slack channels (if any) to the [Kubernetes or CNCF Slack workspace](https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another). CNCF staff can help.
- [x] Submit a [pull request](https://github.com/cncf/landscape/pulls) to add your project as a Sandbox project to the [Cloud Native Landscape](https://landscape.cncf.io) by updating [landscape.yml](https://github.com/cncf/landscape/blob/master/landscape.yml) following these [instructions](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml).
- [x] Transfer [your domain to the CNCF](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63). The "LF Stakeholder email" is <projects@cncf.io>.
- [x] Transfer any [trademark and logo assets to the Linux Foundation](https://github.com/cncf/foundation/tree/main/agreements).
- [x] Submit a [pull request](https://github.com/cncf/artwork) with your artwork.
- [x] Transfer website analytics to <projects@cncf.io>. CNCF staff can help.

## Update and document

- [x] Ensure that [DCO](https://github.com/apps/dco) (preferred) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project.
- [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's `README` on GitHub.
- [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md) are followed (if your project doesn't have a dedicated website, please adopt those guidelines for the `README` file).
- [x] Create a maintainer list and add it to the [aggregated CNCF maintainer list](https://maintainers.cncf.io) via pull request.
- [x] Provide emails for the maintainers to get access to the maintainers mailing list and Service Desk. Email them to <project-onboarding@cncf.io>.
- [x] Start working on [written, open governance](https://contribute.cncf.io/maintainers/governance/).
- [x] Start on an [OpenSSF Best Practices Badge](https://www.bestpractices.dev/en).

## CNCF staff tasks

- [x] Add the project to [DevStats](https://devstats.cncf.io/).
- [x] Add the project to [CLOmonitor](https://clomonitor.io/).
- [x] Add the project to [LFX Insights](https://insights.lfx.linuxfoundation.org/). This is done by adding a read-only app to your GitHub organization once it's in CNCF GHE.
- [x] Add the project to [LFX Project Control Center](https://projectadmin.lfx.linuxfoundation.org/project/a0941000002wBz4AAE).
- [x] Add a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/).
- [x] Invite developers to the [#maintainers-circle](https://app.slack.com/client/T08PSQ7BQ/C014YQ8CDCG) Slack channel.
- [x] Send a welcome email to confirm maintainer list access.

**Comment by qu1queee** [comment]
Hello all,

We are almost completed with the on-boarding items, see our previous [comment](https://github.com/cncf/sandbox/issues/131#issuecomment-2375200185). There are only two open items on our side:

> [ ] Transfer any [trademark and logo assets to the Linux Foundation](https://github.com/cncf/foundation/tree/main/agreements).

We are wondering if there is something to do here, as we are coming from the Continuous Delivery Foundation.


> [ ] Transfer website analytics to [projects@cncf.io](mailto:projects@cncf.io). CNCF staff can help.

We kindly ask for your help on this one.

**Comment by krook** [comment]
@RobertKielty can you please assist with FOSSA and/or Synk?

**Comment by RobertKielty** [comment]
Hi @qu1queee @2SaschaSchwarze0 @adambkaplan 

Can you please let me know what preference you have for license scanning services? I can setup you up on CNCF Service Instances for FOSSA or Snyk.

**Comment by qu1queee** [comment]
@RobertKielty we seem not to have one, could you give us a recommendation?

**Comment by adambkaplan** [comment]
@RobertKielty I'm personally more familiar with Snyk.

**Comment by RobertKielty** [comment]
@qu1queee @SachaSchwarze I have added you to the Shipwright FOSSA Team. 

@adambkaplan I have re-sent the FOSSA Invite. If you want to look at FOSSA to actively comply with the CNCF 3rd Party License policy, please import your code repos into FOSSA using the FOSSA Shipwright Team.

@adambkaplan I have also sent out invites for Snyk to you, @qu1queee and @SachaSchwarze. 
On Snyk, the invites are tied to the Snyk Shipwright Organziaion I have just created.

Feel free to try both services and let me know which one settle on.

**Comment by krook** [comment]
Hello folks! Looks like this is nearly ready to be closed 

Project team (@adambkaplan @qu1queee) , can you please confirm you've read this piece of text:

- [ ] The [Technical Leadership Principles](https://github.com/cncf/toc/blob/main/PRINCIPLES.md#technical-leadership-principles) that outlines the expected behavior for any maintainer in a leadership role.

And @Cmierly can you please confirm this email has been sent:

- [ ] Send a welcome email to confirm maintainer list access.

**Comment by qu1queee** [comment]
@krook yes, confirmed.

**Comment by Cmierly** [comment]
Thanks @qu1queee  and congrats on completing onboarding!
