### ISSUE TITLE
[SANDBOX PROJECT ONBOARDING] TrestleGRC

### ISSUE THREAD

**Issue by Cmierly** [cncf/sandbox#136]
# Welcome to CNCF Project Onboarding!

This is an issue created to help onboard your project into the CNCF after the TOC has voted to accept your project into the Sandbox.

We would like your project to complete onboarding within one month of acceptance.

Please track your progress by using "Quote reply" to create your own copy of this checklist in an issue, so that you can update the status as you finish items.

## Review and understand

- [ ] The [Technical Leadership Principles](https://github.com/cncf/toc/blob/main/PRINCIPLES.md#technical-leadership-principles) that outlines the expected behavior for any maintainer in a leadership role.
- [x] The [project proposal process and requirements](https://github.com/cncf/toc/blob/main/process/README.md).
- [x] The [services available for your project at the CNCF](https://contribute.cncf.io/resources/project-services/).
- [x] The [CNCF IP Policy](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy).
- [x] The [trademark guidelines](https://www.linuxfoundation.org/legal/trademark-usage).
- [x] The [license allowlist](https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md#approved-licenses-for-allowlist).
- [x] The [online program guidelines](https://github.com/cncf/foundation/blob/main/online-programs-guidelines.md).
- [ ] Optional: [Book time with CNCF staff](http://project-meetings.cncf.io) for any onboarding questions.

## Contribute and transfer

- [x] Move your project to its own separate neutral GitHub organization. This will make it transferable to the CNCF's GitHub Enterprise account. If it's already in a GHE account, you will need to remove it from that first.
- [x] Accept the invite to join the CNCF GitHub Enterprise account. We'll then add `thelinuxfoundation` as an organization owner to ensure neutral hosting of your project.
- [x] Migrate your Slack channels (if any) to the [Kubernetes or CNCF Slack workspace](https://slack.com/help/articles/217872578-Import-data-from-one-Slack-workspace-to-another). CNCF staff can help.
- [x] Submit a [pull request](https://github.com/cncf/landscape/pulls) to add your project as a Sandbox project to the [Cloud Native Landscape](https://landscape.cncf.io) by updating [landscape.yml](https://github.com/cncf/landscape/blob/master/landscape.yml) following these [instructions](https://github.com/cncf/landscape2/blob/main/docs/config/data.yml).
- [x] Transfer [your domain to the CNCF](https://jira.linuxfoundation.org/plugins/servlet/theme/portal/2/create/63). The "LF Stakeholder email" is <projects@cncf.io>.
- [x] Transfer any [trademark and logo assets to the Linux Foundation](https://github.com/cncf/foundation/tree/main/agreements).
- [x] Submit a [pull request](https://github.com/cncf/artwork) with your artwork.
- [x] Transfer website analytics to <projects@cncf.io>. CNCF staff can help.

## Update and document

- [x] Ensure that [DCO](https://github.com/apps/dco) (preferred) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project.
- [x] Ensure that that the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/main/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's `README` on GitHub.
- [x] Ensure LF footer is on your website and [guidelines](https://github.com/cncf/foundation/blob/main/website-guidelines.md) are followed (if your project doesn't have a dedicated website, please adopt those guidelines for the `README` file).
- [x] Create a maintainer list and add it to the [aggregated CNCF maintainer list](https://maintainers.cncf.io) via pull request.
- [x] Provide emails for the maintainers to get access to the maintainers mailing list and Service Desk. Email them to <project-onboarding@cncf.io>.
- [x] Start working on [written, open governance](https://contribute.cncf.io/maintainers/governance/).
- [x] Start on an [OpenSSF Best Practices Badge](https://www.bestpractices.dev/en).

## CNCF staff tasks

- [x] Add the project to [DevStats](https://devstats.cncf.io/).
- [x] Add the project to [LFX Insights](https://insights.lfx.linuxfoundation.org/). This is done by adding a read-only app to your GitHub organization once it's in CNCF GHE.
- [x] Add a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/).
- [x] Send a welcome email to confirm maintainer list access.

**Comment by degenaro** [comment]
@Cmierly Is there anything else expected from our side on this issue? Otherwise, I think we have complied with all the requirements.

**Comment by Cmierly** [comment]
@degenaro as long as you're set up with Snyk and ready to go then we can close this out as complete!

Congrats on finishing up Onboarding!

**Comment by jpower432** [comment]
Hi @Cmierly @RobertKielty I wanted to circle back and verify our setup with Synk.

Should we expect an invite to a Synk organization? What information do you need from the OSCAL Compass team? Thanks!

**Comment by RobertKielty** [comment]
@jpower432 I created a Snyk Organization for TrestleGRC and have sent invites just now to all of the project maintainers.

https://app.snyk.io/org/trestlegrc-KA4QpZ8FuRjHL9obtvAkk7

We just need one of the maintainers to accept their invitation and import the project's code repos into the TrestleGRC Snyk Org.

For the import to work, the email address to which the invite was sent will need be associated with a GitHub profile that has read/write access to the project repos.

**Comment by jpower432** [comment]
Thanks @RobertKielty! I have accepted and starting importing the projects under the organization.

**Comment by RobertKielty** [comment]
Hi @jpower432 I can see you imported 4 repos into TrestleGRC on Snyk. Thank you for importing those repos.

However, I need all 18 repos scanned. Can you please import the remaining 14 repos into Snyk? Many thanks.

**Comment by jpower432** [comment]
@RobertKielty Ack. I have imported the remaining repos.

**Comment by RobertKielty** [comment]
FYI @krook I have updated the name of the project here to be "OSCAL Compass" for data accuracy reasons. (lining up the project name in maintainer-d with this ob issue) Let me know if this causes you any issues.

**Comment by ancatri** [comment]
@RobertKielty thank you so much , I really appreciate the care of doing it proactively! It has been on my mind. We have a booth at KubeCon EU and this is very helpful.
