### ISSUE TITLE
[Sandbox] Loggie

### ISSUE THREAD

**Issue by ethfoo** [cncf/sandbox#20]
### Application contact emails

fuyi1@corp.netease.com, hzzhoujianding@corp.netease.com

### Project Summary

Loggie is a lightweight, cloud-native, event-driven data collector, transformer and aggregator.

### Project Description

Loggie is a cloud-native, event-driven data collector and aggregator that is designed to be lightweight and high-performing. It is written in Golang and uses a pluggable architecture that allows users to easily configure multiple pipelines using custom sources, interceptors, and sinks. Loggie can be deployed as either an Agent or an Aggregator, and its pipelines can be connected to form large-scale data flows.
![loggie-arch](https://loggie-io.github.io/docs/getting-started/imgs/loggie-arch.png)

One of the key benefits of Loggie is its ability to support various types of data streams and to normalize, transform, and process data in real-time. It is also scalable, with the ability to handle large volumes of data without requiring significant resources. Additionally, Loggie is designed to be isolated, meaning that different data streams do not influence each other, providing a more stable and secure transmission.

In the context of Kubernetes, Loggie can be easily configured using CRD (Custom Resource Definitions) to create standard streaming data transmission pipelines. It can be used in a variety of scenarios, including collecting container and host logs, aggregating and forwarding data, and collecting Kubernetes events. Overall, Loggie is an ideal tool for managing and processing streaming data in a cloud-native environment.
![loggie-crd-usag](https://loggie-io.github.io/docs/user-guide/use-in-kubernetes/imgs/loggie-crd-usage.png)

### Org repo URL

https://github.com/loggie-io

### Project repo URL

https://github.com/loggie-io/loggie

### Website URL

https://loggie-io.github.io/docs-en/

### Roadmap

https://loggie-io.github.io/docs-en/getting-started/roadmap/roadmap-2023/

### Contributing Guide

https://loggie-io.github.io/docs-en/developer-guide/contributing/

### Code of Conduct (CoC)

https://github.com/loggie-io/loggie/blob/main/CODE-OF-CONDUCT.md

### Contributing or Sponsoring Org

[Netease](https://www.neteasegames.com/)

### Maintainers file

https://github.com/ethfoo, https://github.com/mmaxiaolei

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Loggie is a rapidly developing project with a strong focus on user experience and creative ideas. We have received positive feedback from companies currently utilizing Loggie and believe that joining the Cloud Native Computing Foundation (CNCF) will increase the visibility of the project, attract more users and contributors, and help us to continually improve and make Loggie more widely applicable. We believe that joining the CNCF will provide us with valuable resources and support as we strive to make Loggie an easy-to-use and highly effective tool for a wide range of scenarios.

### Benefit to the Landscape

As a cloud-native log collector, Loggie has unique capabilities for collecting container logs in Kubernetes environments. Unlike Fluentd and other log collectors, which require mounting and collecting from all standard output paths, Loggie allows users to flexibly choose which pods to collect logs from using the LogConfig Custom Resource Definition (CRD). In addition to collecting standard output logs, Loggie can also collect log files within the container without requiring any modifications to the pod.

One of the key advantages of Loggie is that it includes a built-in Kubernetes operator/controller, eliminating the need to deploy additional operator components. Users can simply create a LogConfig/ClusterLogConfig CRD to perform individual log collection configuration, format processing, and data conversion for each workload. Additionally, the use of Interceptor/Sink CRDs allows users to quickly build a log transmission architecture for collecting, aggregating, and forwarding logs.

Beyond log collection, Loggie's multi-pipeline and `source->interceptor->sink` processing architecture make it a versatile tool for collecting, processing, aggregating, and forwarding a wide range of events. In event-driven scenarios or situations where multiple event sources need to be connected, Loggie can be used to collect and convert events to cloud events or opentelemetry logs format. This makes Loggie an valuable addition to the CNCF, providing a powerful tool for log and event collection, processing, and aggregation.

### Cloud Native 'Fit'

Based on the idea of cloud-native Operator/Controller, Loggie provides a better solution for transmitting data such as logs in Kubernetes.

### Cloud Native 'Integration'
`Prometheus`

- Loggie primarily focuses on log collection, but also supports the conversion of logs into metrics such as Nginx access logs. Similar to `mtail`, Loggie supports log processing and structuring, and supports data aggregation over a period of time into metrics. The converted metrics can then be sent to Prometheus via Loggie's `prometheusExporter sink` or `prometheusRemoteWrite sink` for further analysis. 
- Loggie has the capability to detect and match log data according to rules and can trigger alerts through its integration with `Prometheus AlertManager` via the `alertWebhook sink`. 
- Loggie also supports the collection of Prometheus metrics as an agent on each node, with the ability to perform pre-aggregation and processing of metric data, providing an additional method for Prometheus to collect metrics.

`opentelemetry`

Loggie incorporates a robust transformer interceptor that can be used to comply with the log standard format defined by OpenTelemetry. Additionally, Loggie plans to implement a fluentforwardreceiver to facilitate seamless integration with the OpenTelemetry Collector.

`Grafana Loki`

Loggie has a `loki sink`, so Loggie can directly collect logs and send them to Loki for storage, and can use Grafana to query and retrieve logs.

### Cloud Native Overlap

`Fluentd/Filebeat`

One of the main scenarios of Loggie is log collection and transmission. Compared to similar projects, Loggie has distinct design and user experience features such as:

- Loggie is a log collection and transmission tool that utilizes a cloud-native design, implemented as a Kubernetes Operator. This design allows for a more user-friendly and powerful log collection experience within Kubernetes environments. (please refer to the Benefit to the Landscape section above)
- Loggie also features a Multi-Pipeline design, which provides stronger isolation in complex production environments. This feature enables separate deployment as a data transmission transit and aggregation solution.
- Loggie boasts improved performance and a more lightweight design compared to similar projects. This allows for faster data transmission and a more efficient use of resources.

### Similar projects

Fluentd

### Product or Service to Project separation

N/A

**Comment by dims** [comment]
There are a number of projects/tools in CNCF around monitoring/logging/tracing can you please write about any intersection/cooperation between the existing projects and the one you are proposing?

**Comment by ethfoo** [comment]
> There are a number of projects/tools in CNCF around monitoring/logging/tracing can you please write about any intersection/cooperation between the existing projects and the one you are proposing?

Thanks for the suggestion. Have added to the `Cloud Native 'Integration'` and `Cloud Native Overlap` section.
