### ISSUE TITLE
[Sandbox] ErieCanal

### ISSUE THREAD

**Issue by addozhang** [cncf/sandbox#21]
### Application contact emails

xiaohui@flomesh.io, reaver@flomesh.io, caishu@flomesh.io

### Project Summary

ErieCanal is a Kubernetes Multi-Cluster Service API (MCS) implementation, and provides MCS, Ingress, Egress, and Gateway API for Kubernetes clusters.

### Project Description

As enterprises continue to grow and technology continues to advance, the trend towards multi-cloud and hybrid cloud adoption in cloud strategies is becoming increasingly evident. As a result, the communication problem of multi-cluster service in Kubernetes has also received attention. To solve the communication problem of multi-clusters, the Kubernetes community has proposed [Multi-cluster Service](https://github.com/kubernetes-sigs/mcs-api), but currently, there are very few open-source implementations.

ErieCanal is an implementation of the multi-cluster service API. It uses eBPF technology, integrates Ingress/Gateway API components, and realizes Kubernetes multi-cluster communication. This solution is compatible with any Ingress/Gateway API implementation.

The eBPF solution is about to be released, see the [proposal](https://github.com/flomesh-io/ErieCanal/issues/71).

Currently, to solve the problem of insufficient support for eBPF in the operating system kernel, the recommended solution is to use SMI to implement osm-edge and use service mesh for cross-cluster traffic scheduling. This solution can help users solve the multi-cluster communication problem before upgrading the kernel.

We aim to promote the adoption of the Kubernetes multi-cluster service eco-system through the ErieCanal project to meet the network inter-connectivity needs of Kubernetes multi-cluster use-cases, and reduce the threshold of multi-cluster traffic management.

### Org repo URL

https://github.com/flomesh-io

### Project repo URL

https://github.com/flomesh-io/ErieCanal

### Roadmap

https://github.com/flomesh-io/ErieCanal/wiki/Roadmap

### Contributing Guide

https://github.com/flomesh-io/ErieCanal/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/flomesh-io/ErieCanal/blob/main/CODE_OF_CONDUCT.md

### Contributing or Sponsoring Org

https://flomesh.io

### Maintainers file

https://github.com/flomesh-io/ErieCanal/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

ErieCanal provides bundles of features on south-north traffic management and is used as part of our commercial offerings. By joining CNCF, we hope it can be well-exposed and adopted by the community. With more and more feedback from the community, we can build it better together with community contributors.

### Benefit to the Landscape

ErieCanal is an implementation of MCS API, Ingress, Gateway API. It can work as a standalone or be well integrated with CNCF ecosystem.

### Cloud Native 'Fit'

ErieCanal is built with Cloud Native technologies and idea to deal with traffic management.

### Cloud Native 'Integration'

ErieCanal runs on Kubernetes platform and implements the standard MCS API, Ingress and Gateway API.

### Similar projects

[Ingress Nginx](https://github.com/kubernetes/ingress-nginx)
[Submariner](https://submariner.io/)
[Istio](https://istio.io/)

### Product or Service to Project separation

N/A

**Comment by dims** [comment]
@addozhang Can you please expand a bit on the `must be used` relationship between the project being submitted and the other one?

**Comment by addozhang** [comment]
@dims Thanks for your advice. Have updated the project description.

**Comment by caishu97** [comment]
> 

There is a new design proposed, it will remove service mesh dependency and will use ebfp based approach for newer kernel k8s nodes. @dims https://github.com/flomesh-io/ErieCanal/issues/71 implementation will release soon~
