### ISSUE TITLE
[Sandbox] Eraser

### ISSUE THREAD

**Issue by salaxander** [cncf/sandbox#24]
### Application contact emails

xandergr@microsoft.com, ritazh@microsoft.com, seozerca@microsoft.com, bridget.kromhout@microsoft.com

### Project Summary

Eraser is a project that helps clean up unused and vulnerable container images from nodes in a Kubernetes cluster.

### Project Description

When deploying to Kubernetes, it's common for pipelines to build and push images to a cluster, but it's much less common for these images to be cleaned up. This can lead to accumulating bloat on the disk, and a host of non-compliant images lingering on the nodes.

The current garbage collection process deletes images based on a percentage of load, but this process does not consider the vulnerability state of the images. Eraser aims to provide a simple way to determine the state of an image, and delete it if it meets the specified criteria.

### Org repo URL

https://github.com/Azure

### Project repo URL

https://github.com/Azure/eraser

### Additional repos

https://github.com/Azure/eraser-scanner-template

### Website URL

https://azure.github.io/eraser/docs/

### Roadmap

https://github.com/Azure/eraser/milestones

### Roadmap context

We currently use GitHub milestones and a project board to track the short term roadmap

### Contributing Guide

https://azure.github.io/eraser/docs/contributing

### Code of Conduct (CoC)

https://azure.github.io/eraser/docs/code-of-conduct

### Contributing or Sponsoring Org

https://microsoft.com

### Maintainers file

Managed through GitHub Teams

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We would like the project to ultimately be community owned rather than Azure owned. We feel the project can provide benefit to everyone using Kubernetes, and having it belong to the community rather than a single organization will help communicate that. We would also like to grow the community of users and contributors in order to make the tool the absolute best it can be. The CNCF is the best way to go about that.

### Benefit to the Landscape

While Kubernetes has its own garbage collection mechanism today, it does still regularly leave images cached on nodes. In addition to consuming storage, this opens a possible attack vector if images contain vulnerabilities. The core benefit to the landscape is helping users heighten the security of the Kubernetes clusters and the workloads running on them.

### Cloud Native 'Fit'

This project helps users be more successful in running their Kubernetes clusters. Since that's where a good many "cloud native" workloads are running today, we see this as being a good fit for the entire ecosystem around Kubernetes.

### Cloud Native 'Integration'

The main way that Eraser has integration potential with other CNCF projects is through it's extension mechanism. Currently, Eraser utilizes Trivy for vulnerability scanning, but it follows a plugin model, so other scanners could be implemented using the same interface. This opens up Eraser to integrating with other CNCF projects in the container security space.

### Cloud Native Overlap

To our knowledge, there isn't any direct overlap with other CNCF projects today.

### Similar projects

N/A

### Product or Service to Project separation

Azure Kubernetes Service has developed a managed addon of the project for customer clusters. The development and roadmap of the open source project and the managed addon have always remained entirely separate, and that will continue to be true going forward.

### Project presentations

The project was presented to Kubernetes SIG Security as part of their "security tooling" subproject meeting.

https://youtu.be/c1yhWxxEkJI

### Project champions

Lachlan Evenson

**Comment by dims** [comment]
@salaxander @ashnamehrotra, can you please summarize in a short paragraph any feedback from the k8s sig security?

**Comment by salaxander** [comment]
Heya @dims! If I'm remembering correctly, they were excited about it and curious to see how things went as it reached a 1.0.0 version (which should be quite soon!). There were also some questions around architecture, and since then we've updated the documentations site to try and make that a bit more clear -> https://azure.github.io/eraser/docs/architecture

**Comment by helayoty** [comment]
Hey @salaxander, CNCF TAG-Runtime is here. It would be great if you and the Eraser team could present and discuss the project in the next TAG meeting.

Please feel free to add the project to the TAG-Runtime [agenda](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.s485wlw1do6e) at your convenience.

Cc: @raravena80 @nikhita

**Comment by rochaporto** [comment]
Hi @salaxander.

Following the 2023-05-09 [TOC Meeting](https://youtu.be/qt0cfsuGfVo?t=2448) we'd like to ask for a couple clarifications regarding the 'Cloud Native Integration'.
* How do you see the project fitting with others attempting to prevent vulnerable workflows from being deployed? An example being Harbor and vulnerability scans at the registry and offering the possibility to prevent pulling vulnerable images.
* On a similar note, do you see it related to projects focusing on runtime security checks? Here an example would be Falco.

Thanks!

**Comment by salaxander** [comment]
Hey @rochaporto! Thanks for following up

- I think there is overlap in the sense of scanning for vulnerabilities, but the approaches are different. Eraser targets runtime where Harbor sits further left
- I do think there's more overlap in the runtime security tool space, with something like Falco or the Trivy controller. The core difference is Eraser's focus on image cleanup, while using vulnerability data to make decisions on that primary objective. I also don't know if any other tools are focusing their efforts on non-running images like Eraser is (quite possibly! I just haven't looked at that personally).

Definitely let me know if there's any more info I can provide :) 

CC @sozercan @pmengelbert in case they'd like to add any details I may have missed

**Comment by rochaporto** [comment]
Thanks for the clarifications @salaxander

**Comment by sozercan** [comment]
Like @salaxander mentioned, vulnerability scanning with Harbor is on the registry side. There are also vulnerability scanning with Kubernetes webhooks, like Gatekeeper, for admission requests. Images that are being pushed to registries or being admitted to Kubernetes might not be vulnerable at that point in time. However, they'll be cached into nodes and accumulate vulnerabilities over time. This is where eraser comes in to clean up on the vulnerable images that are being present on the nodes.

**Comment by bridgetkromhout** [comment]
Hi, @rochaporto - I see this issue is still tagged "Needs Info". Can you help us understand what info we can additionally provide? Thanks!

**Comment by rochaporto** [comment]
We have all the info we need, thanks @bridgetkromhout . Will update tag.

**Comment by jberkus** [comment]
Can you explain more about why Eraser is a separate project from Kubernetes, and should remain so?

**Comment by bridgetkromhout** [comment]
> Can you explain more about why Eraser is a separate project from Kubernetes, and should remain so?

Hi, @jberkus - we see Eraser as suited for CNCF sandbox to provide the neutral governance and the lightweight process necessary for entities outside Azure to begin adopting and participating in the project.

While Eraser’s implemented use cases are currently scoped to Kubernetes, we are uncertain that it would be a valuable use of a SIG’s time to carry the administrative overhead of Eraser as a subproject, given how early-stage Eraser is. And adding to the weight of the k/k codebase seems to be a non-goal, whereas modular components like Eraser are nice for iterating quickly outside the thrice-yearly releases. Eraser is also easily extensible and customizable, and it can be used with other CNCF projects like Trivy.

If you’d like Eraser to enter CNCF and then explore a working group with a specific Kubernetes SIG, that seems achievable. Happy to discuss further – thanks!

**Comment by amye** [comment]
Closing with approved, new onboarding issue: https://github.com/cncf/toc/issues/1092
