### ISSUE TITLE
[Sandbox] API Improvement Proposals (AIP)

### ISSUE THREAD

**Issue by makahmad** [cncf/sandbox#30]
### Application contact emails

seyed.ahmad@gmail.com, davidebbo@google.com, yusuketsutsumi@google.com

### Project Summary

API Improvement Proposals (AIP) are focused design documents for flexible API development 

### Project Description

In 2019, Google published their API standards, API Improvement Proposals (AIPs), externally on google.aip.dev. Starting 2020, an industry wide effort began with API enthusiasts in many companies (Google, Meta, Roblox, Microsoft, IBM, Oracle, Netflix, and Salesforce) to create API design guidelines now known as Core AIPs. 

Drawing from lessons learned by experts from across the industry, Core AIPs specify patterns and practices for cloud APIs that have a great developer experience, are robust, secure, and scalable by design, support a variety of client integration paradigms, and provide evolutionary flexibility.

### Org repo URL

https://github.com/aip-dev

### Project repo URL

https://github.com/aip-dev/aip.dev 

### Additional repos

https://github.com/aip-dev/google.aip.dev (this would remain as these are Google specific AIPs and there’s numerous links to google.aip.dev from internal Google documents)

https://github.com/googleapis/api-linter

### Website URL

aip.dev

### Roadmap

See below

### Roadmap context

For 2023, we are making a significant push toward widening the reach of the AIPs, and addressing known issues that make the standards and surrounding framework less usable. There have been a handful of enterprise adopters, but see several projects that are valuable to expand the reach of this standard.
Specifically:
- Performing a full audit of Google’s 30+ AIPs, generalizing them for readily consumption by an organization.
- Improvements to the [site-generator to allow customization without forking](https://github.com/aip-dev/site-generator).
- Improvements to the information architecture of the AIPs (enabling deeper explanations of rationale for standard decisions).
- Refactor of aip.dev and the api-linter to the same repository, allowing code that enforces guidance to live closer to the written specification.
- Expanding the api-linter framework to enable verification of more interface definitions beyond protobut (e.g. OpenAPIV3).

### Contributing Guide

https://aip-dev.github.io/aip.dev/contributing  (with the Google CLA removed)

### Code of Conduct (CoC)

will adopt the CNCF CoC

### Adopters

AIPs have been adopted at multiple companies such as Roblox and Salesforce however the URLs are not public.

### Contributing or Sponsoring Org

Google

### Maintainers file

https://github.com/aip-dev/aip.dev/graphs/contributors

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

The API design guidelines that are, in many ways, universal. Besides being used at Google, many companies (Roblox, IBM, Meta, Microsoft, Salesforce, etc) have also adopted it for various teams. The best choice for long-term viability and independence of the API design guidelines is to centralize the API standards in a foundation, such as CNCF, to live among other Google donated projects such as Kubernetes and Istio.

### Benefit to the Landscape

APIs are a fundamental part of the cloud-native ecosystem. Enabling API developers to reference good design guidelines will improve the API design production experience and consumption experience. 

Our values are:

- Approachability (easy to get started)
- Usability (easy to build real world integrations)
- Versatility (ability to support everything from simple automations, to graphical user interfaces, to comprehensibve declarative integrations)
- Robustness (clear and consistent input validation, safe concurrent request support)
- Scalability (individual operations don't become too expensive at scale)
- Language and framework independence (API could be re-implemented on a different stack)
- Evolutionary flexibility (API is designed to grow to support more features without breaking existing clients)

### Cloud Native 'Fit'

API design is fundamental for any Cloud Native project. We feel that AIPs should be in the same foundation family as Kubernetes and Istio, as well as a companion to gRPC (incubating).

### Cloud Native 'Integration'

Long term, we hope that AIPs can become the rich API standard that CNCF projects that expose APIs can adhere to (e.g. Kubernetes).

An API standard and validation toolkit is a great dependency for projects who want ease of integration into multiple categories of clients (CLIs, UIs, SDKs, and IaC tools) without the significant mental overhead of considering the concerns of each and every one. Scope could include CNCF-sponsored projects (e.g. simplifying integration for Backstage plugins).

### Cloud Native Overlap

AIPs provide API guidance, which exists in some form in multiple CNCF projects (e.g. Kubernetes explains guidance around [their resource model](https://github.com/kubernetes/design-proposals-archive/blob/main/architecture/resource-management.md). similar to [AIP's resource-oriented design](https://google.aip.dev/121)).

### Similar projects

Tactically, this project is similar to Microsoft’s REST guidelines and IBM Cloud’s API Handbook.
Conceptually, this project is similar to OpenTelemetry: providing a common higher-order interface and semantics paired with an ecosystem of code generators, documentation, and integrations that can be used by API producers and consumers. 

### Product or Service to Project separation

N/A

### Project presentations

Nope

### Project champions

None

**Comment by toumorokoshi** [comment]
In addition to the other reason to join the CNCF: we are actively adjusting the AIPs to clarify API rules that enable low-cost / fully-automated integration with infrastructure-as-code tools, CLIs, and UIs. 

So another connection point would be AIPs potential to become *the* defined standard interface for management of cloud resources.  

Happy to discuss or produce any desired docs around this if there's interest.

**Comment by toumorokoshi** [comment]
Side question: would it be ok to create a Slack channel in the CNCF slack around this project? 

We do have a private slack channel but it's not particularly accessible. I know it's early, but we'd love to foster open engagement, and it might be helpful to discuss the sandbox application.

**Comment by amye** [comment]
> Side question: would it be ok to create a Slack channel in the CNCF slack around this project?
> 
> We do have a private slack channel but it's not particularly accessible. I know it's early, but we'd love to foster open engagement, and it might be helpful to discuss the sandbox application.

Of course, ping me on Slack if you're having issues.

**Comment by toumorokoshi** [comment]
Thanks @amye! We are now in the `#aip` channel in the CNCF slack for those who want to ask questions or learn more about the project.

**Comment by TheFoxAtWork** [comment]
@AloisReitbauer , @Jenniferstrej , @hongchaodeng - would you all take a look at this project and chime in with any questions or observations?

**Comment by joshgav** [comment]
@makahmad could you come to the next TAG App Delivery meeting on Wednesday June 21 and present the project to us in about 15 minutes? We'll record it and take notes for TOC and other reviewers.

This project would be one of just a few app _development_ projects in CNCF. Dapr, GRPC and perhaps test frameworks like Microcks (#37) are other examples.

Others have expressed interest in developing microservices patterns and practices, in particular @pasimoes presented this proposal earlier this year: <https://github.com/pasimoes/microservices-wg/blob/main/microservices-wg-charter.md>.

@pasimoes would you be able to help review this project? Thanks!

**Comment by pasimoes** [comment]
Hi Josh yes with pleasure. Next Monday I will review it. Thank you.
-- -- -- 
Paulo Alberto Simoes ∴ | Architect, Cloud Specialist
m: +55-21-981-045-770  | ***@***.***

Stay Connected [Linkedin | Twitter | Github | Instagram]: pasimoes

“All our dreams can come true if we have the courage to pursue them.”  -- Walt Disney

**Comment by makahmad** [comment]
@joshgav yes I can totally do that. Please include @toumorokoshi as well. How do I get the meeting invite details or will someone email ?

**Comment by joshgav** [comment]
Hi @makahmad - you can RSVP and get an invite from the TAG community site, here's the June 21 meeting: <https://community.cncf.io/e/mzgfad/>

Continuous agenda and notes for our meetings are [here](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/), agenda for 6/21 is here and already includes AIP :tada:: <https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit#heading=h.kgfhy0kww6ym>

Talk to you soon!

**Comment by makahmad** [comment]
Awesome, RSVPed, thank you Josh!

**Comment by caniszczyk** [comment]
FYI The Linux Foundation would be interested in hosting this effort in the JDF: https://jointdevelopment.org (where GraphQL, OpenAPI etc live)

@makahmad and other AIP folks, LMK if you want to have that convo

**Comment by toumorokoshi** [comment]
Wow, thanks @caniszczyk! We'll discuss it in our next meeting (which is a couple weeks out, due to the US holidays).
