### ISSUE TITLE
[Sandbox] KubeClipper

### ISSUE THREAD

**Issue by sacredartr** [cncf/sandbox#31]
### Application contact emails

contact@kubeclipper.io, zhu.xiaowei@99cloud.net, wu.wenxiang@99cloud.net

### Project Summary

KubeClipper: Manage Kubernetes clusters in the most light and simple way !

### Project Description

KubeClipper is a lightweight, friendly, reliable, and stable platform that provides a friendly graphical interface, API, and CLI tool for Kubernetes cluster lifecycle management. It is fully compatible with K8S, and enables users to quickly create K8S clusters through a friendly wizard Web UI, reducing the learning and construction threshold of K8S.
KubeClipper provides flexible and reliable Kubernetes as a Service (KaaS), enabling enterprise users to manage the K8S clusters like virtual machines. KubeClipper allows users to rapidly deploy K8S clusters in enterprise owned infrastructure and provides continuous full lifecycle management capabilities, and also supports the management of K8S clusters running in any location and provides consistent services. 
Through the KubeClipper wizard graphical interface, users can quickly complete the installation of a production K8S cluster and required components such as CRIs, CNIs, CSI, and various CRD components. In addition, users can perform management actions, such as installation, deleting, upgrading, backup and restoration, scaling, remote access, plug-in management etc..

### Org repo URL

https://github.com/kubeclipper

### Project repo URL

https://github.com/kubeclipper/kubeclipper

### Additional repos

https://github.com/kubeclipper/console
https://github.com/kubeclipper/community
https://github.com/kubeclipper/test-infra

### Website URL

https://kubeclipper.io/

### Roadmap

https://github.com/kubeclipper/community/blob/main/Roadmap.md

### Roadmap context

- Support the KOK (Karmaji) cluster deployment：support k8s-on-k8s cluster based on karmaji
- Support plug-in installation using helm：support cluster plug-in installation through helm
- GPU support (MIG)：support Nvidia GPU operator
- Monitor support：Provides cluster monitoring using Prometheus and Grafana
- Kubernetes Dashboard support：Support installing and accessing the native Kubernetes Dashboard
- LB & Ingress support：support the LB & Ingress plug-in 
- Support the KubeEdge deployment：Support the KubeEdge deployment and edge node management

### Contributing Guide

https://github.com/kubeclipper/kubeclipper#contributing

### Code of Conduct (CoC)

https://github.com/kubeclipper/community/blob/main/code-of-conduct.md

### Contributing or Sponsoring Org

https://www.99cloud.net/

### Maintainers file

https://github.com/kubeclipper/community/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

By joining CNCF, we want to motivate more innovation and participation from the open-source community. Some significant values joining CNCF could bring to the project are:
- Be vendor-neutral: KubeClipper can get a neutral home in CNCF, to facilitate further project development through a more diverse and neutral community.
- Be more aware: leverage CNCF to promote the project and get more users and contributors through official events, mailing lists, blog posts, etc.

We also believe that KubeClipper could be an excellent addition to the CNCF landscape. Based on native K8S and kubeadm, Kubeclipper provides users with a simple and friendly graphical interface platform that reduces the learning and construction cost of K8S. 

### Benefit to the Landscape

As Kubernetes is adopted by large enterprises, the demand for multi-region K8S cluster management has become prominent to optimize construction and maintenance costs.
KubeClipper's contribution to CNCF gives developers and enterprises another option to deploy and manage K8S clusters. KubeClipper is a secondary package based on kubeadm and provides a graphical interface, API, and CLI tool which are perfectly compatible with native K8S. In particular, it is very lightweight and does not rely on installation tools such as ansible.
At the same time, kubeclipper is also a great management tool for enterprise users. Kubeclipper provides flexible Kubernetes as a Service, which allows users to manage K8S clusters like virtual machines in enterprise owned infrastructure. It provides continuous full lifecycle management capabilities for K8S clusters, such as installation, unloading, upgrading, backup and restoration, scaling, remote access, plug-in management etc..  It also supports the management of K8S clusters running in any location and provides consistent services. 

### Cloud Native 'Fit'

Platform - Certified Kubernetes - Installer 
Fully compatible with native Kubernetes, KubeClipper is a secondary package based on the widely used kubeadm and provides a graphical interface, API, and CLI tool, providing rapid deployment of K8S clusters and continuous full lifecycle management (installation, deleting, upgrading, scaling, remote access, etc.) in enterprise owned infrastructure. It is also a great KaaS management tool for enterprise users and enables enterprise users to manage production K8S clusters in multiple regions through the interface. 

### Cloud Native 'Integration'

Kubeclipper depends on kubeadm to install and upgrade the cluster, and depends on kubectl to access the cluster.
It can be used to complement the K8S management platform, such as KubeSphere.

### Similar projects

- Amazon Elastic Kubernetes Service Anywhere (Amazon EKS Anywhere)
- Rancher Kubernetes Engine (RKE)
- Kubekey
- autoK3S

### Product or Service to Project separation

kubeClipper is also part of 99cloud's cloud platform "Animbus Cloud". kubeClipper is the core module of the K8S cluster deployment and management module in the cloud platform, but will never undertake other product functions. Enhancements to the cluster management module of Animbus Cloud will be continually contributed to open source KubeClipper, and new features from KubeClipper will be selectively incorporated into Animbus Cloud product iterations.

### Project presentations

OpenInfra Days China 2022: https://segmentfault.com/area/openinfra-2022

### Additional information

99Cloud is a silver member of CNCF. Since its establishment in 2012, it has always adhered to the original intention of embracing open source and giving back to the community. It has opened source several star projects successively, such as:
1. Jianmu for AutoOps https://jianmu.dev/
2. Skyline: A new dashboard for OpneStack https://opendev.org/openstack/skyline-apiserver
3. OpenV2X for vehicle-road collaboration https://openv2x.org/

KubeClipper is another open source project of 99cloud, which aims to provide light, friendly, reliable and stable KaaS management, in order to reduce the threshold of K8S, providing more convenience for enterprise users and developers.

**Comment by helayoty** [comment]
Hi @sacredartr ,

I'm part of [CNCF TAG Runtime](https://github.com/cncf/tag-runtime). It would be great for you to present/discuss KubeClipper at one of our meetings, especially since you've applied for Sandbox.

For example, it would be great to learn things like the roadmap, tech, community, and the general overview of the project.

Let me know if this is something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-tag-runtime-meeting-notes) or reach out to us in the [#tag-runtime](https://cloud-native.slack.com/messages/tag-runtime) channel on the CNCF slack.

Thanks!

cc @raravena80 @nikhita

**Comment by jberkus** [comment]
Does Kubeclipper work on any cloud?   Does it work on bare metal?

**Comment by TheFoxAtWork** [comment]
@sacredartr Could you provide more information on the types of environments KubeClipper is capable of running on (bare-metal, cloud provider, etc)?

**Comment by x893675** [comment]
kubeclipper supports running on cloud, hypervisor, bare metal, without vendor binding. We tested centos7, debian9/10, ubuntu18.04/20.04/22.04 (amd64/arm64)
