### ISSUE TITLE
[Sandbox] Spiderpool

### ISSUE THREAD

**Issue by weizhoublue** [cncf/sandbox#33]
### Application contact emails

weizhou.lan@outlook.com, kay.yan@daocloud.io

### Project Summary

Underlay and RDMA network solution of the Kubernetes, for bare metal, VM and any public cloud. Spiderpool delivers exceptional network performance, particularly benefiting network I/O-intensive and low-latency applications like storage, middleware, and AI trainning.

### Project Description

![arch](https://github.com/cncf/sandbox/assets/45163302/8e3d963a-e0ee-43c9-a411-ca78a0b41887)

Spiderpool is an underlay and RDMA network solution for the Kubernetes. It enhances the capabilities of [Macvlan CNI](https://github.com/containernetworking/plugins/tree/main/plugins/main/macvlan), [ipvlan CNI](https://github.com/containernetworking/plugins/tree/main/plugins/main/ipvlan), [SR-IOV CNI](https://github.com/k8snetworkplumbingwg/sriov-cni), and fulfills various networking needs and supports to run on **bare metal, virtual machine, and public cloud environments**. Spiderpool delivers exceptional network performance, particularly benefiting network I/O-intensive and low-latency applications like **storage, middleware, and AI**.
It could refer to [website](https://spidernet-io.github.io/spiderpool/) for more details.

**What enhancements does Spiderpool provide for macvlan, ipvlan, and SR-IOV CNI?**

* Simplified installation and usage

    Through eliminating the need for manually installing multiple components such as [Multus CNI](https://github.com/k8snetworkplumbingwg/multus-cni) , RDMA and SR-IOV, Spiderpool simplifies the installation process and decreases the number of running PODs. It provides streamlined installation procedures, encapsulates relevant CRDs, and offers comprehensive documentation for easy setup and management.

* CRD-based dual-stack IPAM capability

  Spiderpool provides exclusive and shared IP address pools, supporting various affinity settings. It supports to assign static IP addresses for stateful applications such as [mysql](https://www.mysql.com) , [redis](https://github.com/redis/redis) , [kubevirt](https://github.com/kubevirt/kubevirt) , while enabling fixed IP address ranges for stateless ones. Spiderpool automates the management of exclusive IP pools, ensuring excellent IP reclamation to avoid IP leakage. In additions, it owns [wonderful IPAM performance](https://github.com/spidernet-io/spiderpool/blob/main/docs/concepts/ipam-performance.md).

    The IPAM of Spiderpool could be available for any main CNI supporting third-party IPAM plugin, not only including [Macvlan CNI](https://github.com/containernetworking/plugins/tree/main/plugins/main/macvlan), [ipvlan CNI](https://github.com/containernetworking/plugins/tree/main/plugins/main/ipvlan), [SR-IOV CNI](https://github.com/k8snetworkplumbingwg/sriov-cni), but also [calico](https://github.com/projectcalico/calico) [weave](https://github.com/weaveworks/weave) as static IP usage.

* Multiple network interfaces from underlay and overlay CNI

    Spiderpool enables scenarios where Pods can have multiple underlay CNI interfaces or a combination of overlay and underlay CNI interfaces. It ensures proper IP addressing for each CNI interface and effectively manages policy routing to maintain consistent data paths, eliminating packet loss concerns. It could strengthen [cilium](https://github.com/cilium/cilium), [calico](https://github.com/projectcalico/calico), [kubevirt](https://github.com/kubevirt/kubevirt) .

* Enhanced network connectivity

    As we know, native CNI of macvlan ipvlan SR-IOV has lots of communication limits. However, Spiderpool establishes seamless connectivity between Pods and host machines, ensuring smooth functioning of Pod health checks. **It enables Pods to access services through kube-proxy or eBPF-based kube-proxy replacement**. Additionally, it supports advanced features like IP conflict detection and gateway reachability checks. The network of Multi-cluster could be connected by a same underlay network, or [Submariner](https://github.com/submariner-io/submariner) .

* eBPF enhancements

    The eBPF-based kube-proxy replacement significantly accelerates service access, while socket short-circuiting technology improves local Pod communication efficiency within the same node.  Compared with kube-proxy manner, [the improvement of the performance is Up to 25% on network delay, up to 50% on network throughput](https://github.com/spidernet-io/spiderpool/blob/main/docs/concepts/io-performance.md)

* RDMA support

    Spiderpool offers RDMA solutions based on RoCE and InfiniBand technologies. POD could use the RDMA device in shared or exclusive mode, and it is fit for AI workloads.

* Dual-stack network support

    Spiderpool supports IPv4-only, IPv6-only, and dual-stack environments.

* Good network performance of latency and throughput

  Spiderpool performs better than overlay CNI on network latency and throughput, referring to [performance report](https://github.com/spidernet-io/spiderpool/blob/main/docs/concepts/io-performance.md)

* Metrics

**Which scenarios can Spiderpool be applied in?**

Spiderpool, powered by underlay CNI, offers unparalleled network performance compared to overlay CNI solutions, as evidenced in [I/O Performance](./docs/concepts/io-performance.md). It can be effectively applied in various scenarios, including:

* Support to deploy on the environments of bare metal, virtual machine, and public cloud, especially offer an unified underlay CNI solution for hybrid cloud.

* Traditional host applications. They hope to directly use the underlay network, with the reasons such as direct access to the underlay multi-subnet, multicast, multicast, layer 2 network communication, etc. They cannot accept the NAT of the overlay network and hope to seamlessly migrate to Kubernetes .

* Leverage RDMA for efficient network transmission, such as AI application.

* Network I/O-intensive applications such as middleware, data storage, log observability, and AI training.

* Applications which needs a separate network bandwidth

* Latency-sensitive application.

**Spiderpool provides many exciting features, refter to [feature](https://github.com/spidernet-io/spiderpool/blob/main/docs/develop/roadmap.md)**

### Org repo URL

https://github.com/spidernet-io

### Project repo URL

https://github.com/spidernet-io/spiderpool

### Additional repos

https://github.com/spidernet-io/community

https://github.com/spidernet-io/egressgateway

https://github.com/spidernet-io/cilium-chaining

### Website URL

https://spidernet-io.github.io/spiderpool/

### Roadmap

![企业微信截图_18abdd3d-ee62-4ba2-bf60-746d656ef3b0](https://github.com/cncf/sandbox/assets/45163302/b19c54dd-d79a-4f4d-9029-55ffeb0d5ff1)

refer [doc](https://github.com/spidernet-io/spiderpool/blob/main/docs/develop/roadmap.md) for details

### Roadmap context

the roadmap goals of Spiderpool:

- IPAM needs of the underaly network, especially static IP
- kinds of RDMA features from high-performance needs, support RoCE and Infiniband, 
- network acceleration integrating with more hardware and eBPF features
- kinds of other features offered by common CNI projects

[community meetings](https://docs.google.com/document/d/1tpNzxRWOz9-jVd30xGS2n5X02uXQuvqJAdNZzwBLTmI/edit) 

### Contributing Guide

https://github.com/spidernet-io/spiderpool/blob/main/docs/develop/contributing.md

### Code of Conduct (CoC)

https://github.com/spidernet-io/spiderpool/blob/main/docs/develop/CODE-OF-CONDUCT.md

### Adopters

In the upcoming KCD China 2023, one of biggest smartphone manufacturer in China, [VIVO](https://www.vivo.com/en) will present [how they use Spiderpool to build RDMA networks on their AI cluster](https://mp.weixin.qq.com/s?__biz=MzI4NjY4MTU5Nw==&mid=2247497810&idx=2&sn=f5cf932db92b0f482abf3b4a7b6d2686&chksm=ebdb88c0dcac01d64d6c687452631cb46409b0c318e24dedeec5dc99aaeb2273aa3190a0f02d&mpshare=1&scene=1&srcid=1213ZOSDsCmLoean08u4AzGe&sharer_shareinfo=c105c121e3df35391fcbbe1eb416a73f&sharer_shareinfo_first=2dd4ec3d54ac52e125d8a7e73a8b3694&version=4.1.12.99346&platform=mac#rd)

refer to [User](https://github.com/spidernet-io/spiderpool/blob/main/docs/USERS.md) for more details

### Contributing or Sponsoring Org

https://github.com/spidernet-io/spiderpool/blob/main/AUTHORS

### Maintainers file

https://github.com/spidernet-io/spiderpool/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

The Cloud Native Computing Foundation (CNCF) is the vendor-neutral, open-source hub of cloud-native computing
that has become an essential project in promoting cloud-native technology. The Spiderpool community fully supports CNCF's vision.

- Being an ecosystem project of CNCF can increase awareness of the Spiderpool project. On the one hand,
  Spiderpool can enable more CNI solutions to benefit more people with underlying network needs, also aware more needs
from the community to make Spiderpool thrive. On the other hand, it cloud involve more developer in the Spiderpool and make the community better

- With the guidance of CNCF, Spiderpool can adhere to its requirements and set goals in the right direction.

- Spiderpool could strength CNCF projects such as [calico](https://spidernet-io.github.io/spiderpool/dev/usage/install/underlay/get-started-calico/) [cilium](https://spidernet-io.github.io/spiderpool/dev/usage/install/overlay/get-started-cilium/)  [kubevirt](https://spidernet-io.github.io/spiderpool/dev/usage/kubevirt/) [Submariner](https://github.com/submariner-io/submariner)

### Benefit to the Landscape

We believe that our community will contribute significantly to the advancements in CNI add-ons.

- Currently, AI workload is so important, and there is no CNI project providing RDMA feature. Spiderpool focus on underlay network and RDMA solution, and its features could provide complete features for RDMA, which makes  Spiderpool special for AI application.

- Spiderpool could help and cooperate with [cilium](https://github.com/cilium/cilium), [calico](https://github.com/projectcalico/calico), [kubevirt](https://github.com/kubevirt/kubevirt) [Submariner](https://github.com/submariner-io/submariner) .

- Not only limited to bare metal environments in data centers, but also providing a unified underlay CNI solution for openstack, vmware, and various public cloud scenarios. But there is no similar project in the community.

- Before the Spiderpool project was launched, we had developed a similar private project.
  The idea and design of Spiderpool were based on our extensive experience in production environments.
  Spiderpool has been deployed on production environment of end users, and it has proven to be both practical and stable.

- Spiderpool could help many of the main CNI addons to manage IP addresses,
  especially for CNIs without IPAM capabilities. The IPAM needs for underlay networks are more complex than those for  overlay networks. For example, pods  may require static IP addresses for firewall reasons. Additionally, private IPv4 addresses are scarce,  and Spiderpool must release IP addresses taken by abnormal pods to make them available for new pods.

  Therefore, Spiderpool is unique in that all its features are primarily designed for underlay networks.
  Its design is based on best practices in production environments.

### Cloud Native 'Fit'

Underlay and RDMA network solution of the Kubernetes, for bare metal, VM and any public cloud.
It could strengthen [cilium](https://github.com/cilium/cilium), [calico](https://github.com/projectcalico/calico), [kubevirt](https://github.com/kubevirt/kubevirt) [Submariner](https://github.com/submariner-io/submariner) .
Spiderpool fits within the “Cloud Native Network” section of the CNCF landscape.

### Cloud Native 'Integration'

- It is specifically designed for underlay network use and works well in cooperation with CNI addons
like [macvlan](https://github.com/containernetworking/plugins/tree/main/plugins/main/macvlan), [calico BGP mode](https://github.com/projectcalico/calico), [weave](https://github.com/weaveworks/weave), [vlan](https://github.com/containernetworking/plugins/tree/main/plugins/main/vlan), [ipvlan](https://github.com/containernetworking/plugins/tree/main/plugins/main/ipvlan), [sriov](https://github.com/k8snetworkplumbingwg/sriov-cni), [ovs](https://github.com/k8snetworkplumbingwg/ovs-cni), [Multus](https://github.com/k8snetworkplumbingwg/multus-cni),  
It could offer underlay network and static iPAM for [kubevirt](https://github.com/kubevirt/kubevirt), offer secondary underlay network card for [cilium](https://github.com/cilium/cilium) and [calico ](https://github.com/projectcalico/calico). It could integrate with [Submariner](https://github.com/submariner-io/submariner) for multi-cluster network

- The Spiderpool is based on CRD design, and it uses client-go to create, watch and delete kubernetes resources.

- Spiderpool offers extensive [usage documentation](https://github.com/spidernet-io/spiderpool/tree/main/docs/usage)
that demonstrates how to solve underlay network problems. Spiderpool's documentation offers clear guidance on best practices . 

### Cloud Native Overlap

Spiderpool is a network project, and focus on underlay network and RDMA solution, and there is no CNI project providing RDMA feature. 

There are some similar projects for accessing L2 underlay network, such [kube-ovn](https://github.com/kubeovn/kube-ovn). But Spiderpool implements it with macvlan sriov in a different way, and Spiderpool does have unique RDMA feature for high performance needs, fit for AI workload, and no CNCF projects offer this feature.

In addition , overlay CNIs such as [cilium](https://github.com/cilium/cilium) and [calico ](https://github.com/projectcalico/calico), take veth virtual interface to perform in different way, and pod could not directly access the layer 2 network of the node, could not offer RDMA feature. 

At this time, we do not believe that there is significant overlap between Spiderpool and other CNCF projects.

### Similar projects

1. [network-operator](https://github.com/Mellanox/network-operator) is an underlay project, but not a landscape or CNCF project. It is about macvlan sriov for RDMA. Spiderpool differs from it in several ways:

- Spiderpool has network connectivity enhancerment like clusterip and local node communication, but network-operator does not
- network-operator takes [Whereabouts] as IPAM, but Spiderpool has more advanced IPAM
- Spiderpool apply underlay CNI on public cloud, but network-operator does not
- Spiderpool has multiple interfaces enhancement , but network-operator does not

2. [Whereabouts](https://github.com/k8snetworkplumbingwg/whereabouts) is an IPAM project, but not a landscape or CNCF project. Spiderpool has IPAM feature, but differs from Whereabouts in several ways:

- Spiderpool can automatically assign static IP addresses to applications, whereas Whereabouts cannot.
- For stateful applications, Spiderpool can automatically fix IP addresses for each pod,
  while Whereabouts does not support this feature.
- When an application has pods running on nodes accessing different underlay subnets,
  Spiderpool can assign IP addresses within different subnets, but Whereabouts does not have this capability.
- Spiderpool has subnet and ippool CRD storage, while Whereabouts does not.
- Spiderpool supports assigning IP addresses in different subnets for multi-NIC cases, but Whereabouts does not.
- Spiderpool supports customized pod routing, while Whereabouts does not.

3. [kube-ovn](https://github.com/kubeovn/kube-ovn) is a CNCF network project, it is based on openvswitch datapath and offers a solution for L2 underlay network and overlay network. But Spiderpool has some differences:

- offer datapath such as macvlan sriov, and it could specify a subnet with separate bandwidth
- offer high-performance RDMA feature, fit for AI worload
- more features for IPAM, fitting for more underlay IPAM needs
- Not only limited to bare metal environments in data centers, but also providing a unified underlay CNI solution for openstack, vmware, and various public cloud scenarios.
- provide a secondary network card for POD with [cilium](https://github.com/cilium/cilium) [calico](https://github.com/projectcalico/calico)
- multiple underlay network cards for POD

### Product or Service to Project separation

N/A

### Project presentations

[MakeUnderlayCNItoBePowerfulandSimple_v5.pdf](https://github.com/cncf/sandbox/files/13359755/MakeUnderlayCNItoBePowerfulandSimple_v5.pdf)

[Kubecon 2023 US slides](https://cloud-native.slack.com/archives/CMG237Z5Z/p1690485800216789)

[Kubecon 2023 US Presentation](https://www.youtube.com/watch?v=KqfzkOGObCQ)

[network TAG Presentation](https://cloud-native.slack.com/archives/CMG237Z5Z/p1690485800216789)

### Additional information

Community：
- [community](https://github.com/spidernet-io/community)
- 27 contributor, and 8 contributors of them is not from daocloud
- In WeChat popular in China, there is a spiderpool communication channel since 2022.
- Slack channel since 2023:  https://cloud-native.slack.com/messages/spiderpool
- Theres are English and Chinese documents available on official website:  https://spidernet-io.github.io/spiderpool/
- Lots of posts have been published in the Daocloud blogs since 2022https://github.com/spidernet-io/spiderpool#blogs
- Presentation in daocloud open source meeting in NanJing City, 2022.08
- Presentation in Kubecon 2023 North America
- One version published for each month, since the beginning
- version changelogs https://github.com/spidernet-io/spiderpool/tree/github_pages/changelogs
- community meeting https://docs.google.com/document/d/1tpNzxRWOz9-jVd30xGS2n5X02uXQuvqJAdNZzwBLTmI/edit
- In the upcoming KCD China 2023, one of biggest smartphone manufacturer in China, [VIVO](https://www.vivo.com/en) will present [how they use Spiderpool to build RDMA networks on their AI cluster](https://mp.weixin.qq.com/s?__biz=MzI4NjY4MTU5Nw==&mid=2247497810&idx=2&sn=f5cf932db92b0f482abf3b4a7b6d2686&chksm=ebdb88c0dcac01d64d6c687452631cb46409b0c318e24dedeec5dc99aaeb2273aa3190a0f02d&mpshare=1&scene=1&srcid=1213ZOSDsCmLoean08u4AzGe&sharer_shareinfo=c105c121e3df35391fcbbe1eb416a73f&sharer_shareinfo_first=2dd4ec3d54ac52e125d8a7e73a8b3694&version=4.1.12.99346&platform=mac#rd)

**Comment by weizhoublue** [comment]
> Could you present it to the TAG-network and get their input on positioning this as a CNCF project?

great, we will prepare it and present on coming meeting

**Comment by amye** [comment]
@leecalcote - fyi!

**Comment by weizhoublue** [comment]
Is it ok to add the presentation to the agenda of TAG network meeting , July 21th

**Comment by weizhoublue** [comment]
slides are shared here
https://cloud-native.slack.com/archives/CMG237Z5Z/p1690485800216789

**Comment by weizhoublue** [comment]
Spiderpool will be also presented in topic "Make Underlay CNI to Be Powerful and Simple", November 8, Kubecon 2023, North America
https://kccncna2023.sched.com/event/1R2sl/make-underlay-cni-to-be-powerful-and-simple-lan-weizhou-qiuping-dai-daocloud

**Comment by TheFoxAtWork** [comment]
@leecalcote - Does TAG Network have a recommendation on this project?

**Comment by weizhoublue** [comment]
support of kubevirt、RDMA for AI feature is on the way

**Comment by amye** [comment]
@leecalcote  - quick ping on this! We're getting ready for December's sandbox review meeting and would like to know if TAG Network has a recommendation.

**Comment by Icarus9913** [comment]
Hi @amye , we had a presentation in Kubecon north America 2023 this month.

(1) kubecon video
https://www.youtube.com/watch?v=KqfzkOGObCQ
(2) kubecon slides
https://kccncna2023.sched.com/event/1R2sl/make-underlay-cni-to-be-powerful-and-simple-lan-weizhou-qiuping-dai-daocloud?iframe=no

**Comment by linsun** [comment]
Hi @weizhoublue and team, I reviewed spiderpool meeting mins in July along with updated info you provided via slack, and provided the following feedback:

1. the connection to cncf/cloud native isn't clear to me on your repo other than cncf logo. it is not clear to me how this can work with other cncf incubating or graduation projects other than k8s. 2. I didn't find a get started guide, so not sure how to use this or how others can benefit from it. 3. I noticed all maintainers are from DaoCloud, do you have other maintainers? I saw you mentioned you have quite a few contributors from other companies. 4. great performance was mentioned a few times, would be helpful to provide some links/data. 5. Do you implement k8s [network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) API? if so, worth calling that out.

@weizhoublue has replied that he has addressed my feedback by updating github contents, which I just confirmed it. I'd recommend to accept this as a sandbox project as it integrates nicely with other CNIs such as Cilium or Calico per their [Architecture doc](https://github.com/spidernet-io/spiderpool/blob/main/docs/concepts/arch.md#spiderpool-architecture). I would recommend the team to grow at least 1+ non dao cloud maintainers (they have 5 contributors from outside of daocloud atm).

cc @leecalcote & @ZackButcher for their input as well.

**Comment by weizhoublue** [comment]
> Hi @weizhoublue and team, I reviewed spiderpool meeting mins in July along with updated info you provided via slack, and provided the following feedback:
> 
> 1. the connection to cncf/cloud native isn't clear to me on your repo other than cncf logo. it is not clear to me how this can work with other cncf incubating or graduation projects other than k8s. 2. I didn't find a get started guide, so not sure how to use this or how others can benefit from it. 3. I noticed all maintainers are from DaoCloud, do you have other maintainers? I saw you mentioned you have quite a few contributors from other companies. 4. great performance was mentioned a few times, would be helpful to provide some links/data. 5. Do you implement k8s [network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) API? if so, worth calling that out.
> 
> @weizhoublue has replied that he has addressed my feedback by updating github contents, which I just confirmed it. I'd recommend to accept this as a sandbox project as it integrates nicely with other CNIs such as Cilium or Calico per their [Architecture doc](https://github.com/spidernet-io/spiderpool/blob/main/docs/concepts/arch.md#spiderpool-architecture). I would recommend the team to grow at least 1+ non dao cloud maintainers (they have 5 contributors from outside of daocloud atm).
> 
> cc @leecalcote & @ZackButcher for their input as well.

many thanks to @linsun professional reviews, I have updated some Spiderpool's documents to put it straight about important information. Spiderpool will make more efforts to involve more contributors and members from non-Daocloud company

**Comment by TheFoxAtWork** [comment]
@weizhoublue I would recommend reaching out to TAG Contributor Strategy to learn more about how the project can seek, promote, and retain contributors and maintainers from other organizations.

**Comment by weizhoublue** [comment]
> TAG Contributor Strategy

Thanks a lot, that is a great direction for us to improve and make the spiderpool community better

**Comment by weizhoublue** [comment]
In the upcoming KCD China 2023, Chinese smartphone manufacturer [VIVO](https://www.vivo.com/en) will present [how to use Spiderpool to build RDMA networks on AI cluster](https://mp.weixin.qq.com/s?__biz=MzI4NjY4MTU5Nw==&mid=2247497810&idx=2&sn=f5cf932db92b0f482abf3b4a7b6d2686&chksm=ebdb88c0dcac01d64d6c687452631cb46409b0c318e24dedeec5dc99aaeb2273aa3190a0f02d&mpshare=1&scene=1&srcid=1213ZOSDsCmLoean08u4AzGe&sharer_shareinfo=c105c121e3df35391fcbbe1eb416a73f&sharer_shareinfo_first=2dd4ec3d54ac52e125d8a7e73a8b3694&version=4.1.12.99346&platform=mac#rd)

**Comment by weizhoublue** [comment]
> cncf/toc#1225

great, and many thanks, I will check and finish these items

**Comment by weizhoublue** [comment]
> Hi @weizhoublue ! Welcome aboard! We're very excited to get you onboarded as a CNCF sandbox project! Here's the link to your onboarding checklist: [cncf/toc#1225](https://github.com/cncf/toc/issues/1225)
> 
> Here you can communicate any questions or concerns you might have. Please don't hesitate to reach out, I am always happy to help!

great, and thanks, I will check and finish these items
