### ISSUE TITLE
[Sandbox] easegress

### ISSUE THREAD

**Issue by localvar** [cncf/sandbox#35]
### Application contact emails

zhangbomin@megaease.com

### Project Summary

Easegress is a Cloud Native traffic orchestration system designed.

### Project Description

Easegress is a Cloud Native traffic orchestration system tailored for:
- High Availability: With integrated Raft consensus and leader election, it delivers a 99.99% availability rate.
- Traffic Orchestration: Effortlessly orchestrates a variety of filters for each traffic pipeline.
- High Performance: Its lightweight design and essential features contribute to accelerated performance.
- Observability: Regularly provides insightful statistics in an easily understandable format.
- Extensibility: Allows for seamless development of custom filters or controllers using high-level programming languages.
- Integration: Its straightforward interfaces enable effortless integration with other systems, such as Kubernetes Ingress, EaseMesh sidecar, Workflow, and more.

### Org repo URL

https://github.com/megaease

### Project repo URL

https://github.com/megaease/easegress

### Website URL

https://github.com/megaease/easegress

### Roadmap

https://github.com/megaease/easegress/blob/main/doc/Roadmap.md

### Contributing Guide

https://github.com/megaease/easegress/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/megaease/easegress/blob/main/CODE_OF_CONDUCT.md

### Maintainers file

https://github.com/megaease/easegress/blob/main/MAINTAINERS

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

By becoming a part of CNCF, we hope to encourage increased innovation and engagement from the open-source community. We aim to foster greater community adoption and contributions to Easegress by situating the project within a neutral organization, which reinforces our commitment to open governance. This move also helps align the project more closely with its target audience, the cloud native community.

### Benefit to the Landscape

As more and more organizations adopt cloud-native architectures, their expectations for traffic gateways extend beyond basic reverse proxies. They now seek dynamic traffic orchestration and scheduling solutions. Easegress adeptly addresses these requirements while providing high extensibility, seamlessly integrating diverse business logic.

We believe that Easegress offers users more choices in traffic management, helping them enter the cloud-native era more efficiently.

### Cloud Native 'Fit'

Easegress is completely built on cloud-native technologies, with native support for high availability, dynamic traffic orchestration, observability, and scalability.

### Similar projects

[envoy](github.com/envoyproxy/envoy)
[Traefik](https://github.com/traefik/traefik)

### Product or Service to Project separation

N/A

**Comment by mattfarina** [comment]
@localvar Thanks for submitting easegress. The TOC has two pieces of feedback we are looking for before finishing our evaluation.

1. Can you please present to [TAG Network](https://github.com/cncf/tag-network). We would like to get their feedback after a presentation.
2. Are you aware of the IP and trademark implications with donating to the CNCF. The CNCF policy is [here](https://github.com/cncf/foundation/blob/main/charter.md#11-ip-policy) and the trademark policy for using names after being donated are [here](https://www.linuxfoundation.org/legal/trademark-usage). For example, the name policy limits how you can use the easegress name in products and services after it's donated. Are you ok with those implications?

Thanks. We look forward to getting some more detail and looking at this in more detail.

**Comment by localvar** [comment]
hi @mattfarina , thanks for the feedback:

For 1: could you please give some hint about how to present to [TAG Network](https://github.com/cncf/tag-network), I checked the repo but didn't found out how to do this.

For 2: Yes, we are ok with the implications.

**Comment by nikhita** [comment]
> could you please give some hint about how to present to [TAG Network](https://github.com/cncf/tag-network), I checked the repo but didn't found out how to do this.

@leecalcote can you please provide guidance here?

**Comment by leecalcote** [comment]
@nikhita, thanks for this. I'll add a small point of instruction about how to propose an agenda item for TAG Network meetings.

@localvar, I have placed Easegress on the upcoming [TAG Network's meeting agenda](https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit), which is Thursday, August 10th, 2023 at 9am Pacific. Does this day/time work?

**Comment by localvar** [comment]
@leecalcote thanks for the help.
August 10th is a little tight for me, is it possible to give me one more week?

**Comment by xxx7xxxx** [comment]
I have taken over my @localvar 's application. Contact email: longyun@megaease.com

**Comment by amye** [comment]
@leecalcote  - quick ping on this! We're getting ready for December's sandbox review meeting and would like to know if TAG Network has a recommendation.

**Comment by linsun** [comment]
Hi @amye the TAG network team reviewed this on 9/14, and you can find [meeting mins](https://docs.google.com/document/d/18hYemFKK_PC_KbT_TDBUgb0rknOuIhikkRxer4_bv4Q/edit#bookmark=kix.51pdp2j44go).  We would recommend this to be added to CNCF sandbox project as it fits in the existing landscape of cloud native networking and the project looks healthy with 5k+ stars with ASL 2.0 license.

**Comment by amye** [comment]
Thank you, adding to the upcoming queue!
