### ISSUE TITLE
[Sandbox] Terrakube

### ISSUE THREAD

**Issue by jcanizalez** [cncf/sandbox#36]
### Application contact emails

javier-canizalez@outlook.com, alfespa17@gmail.com

### Project Summary

Open source Infrastructure Automation and Collaboration Platform.

### Project Description

Terrakube is an open source collaboration platform for running remote infrastructure as code operations using terraform that aims to be a complete replacement for close source tools like Terraform Enterprise, Scalr or Env0.
The platform can be easily installed in any kubernetes cluster, you can easily customize the platform using other open source tools already available for terraform (Example: terratag, opa,infracost, terrascan, etc) and you can integrate the tool with different authentication providers like Azure Active Directoy, Google Cloud Identity, Github, Gitlab or any other provider supported by [Dex](https://dexidp.io/docs/connectors/).

Terrakube provides different features like the following:
- **Terraform module protocol**: This allows Terrakube to expose an open source terraform registry that is protected and is private by default using different Dex [connectors](https://dexidp.io/docs/connectors/) for the authentication with different providers.
- **Terraform provider protocol:** This allows Terrakube to expose an open source terraform registry where you can have create your own private terraform providers or create a mirror of the current terraform providers available in the public Hashicorp registry.
- Handle you infrastructure as code using Organization like closed source tools like Terraform Enterprise and Scalr.
Easily extended by default integrating with many open source tools available today for terraform CLI.
Support to run the platform using any RDBMS supported by [liquibase](https://www.liquibase.org/) (mysql, postgres, oracle, sql server, etc).
- Plugins support to extends functionality using different cloud providers and open source tools using the Terrakube Configuration Languague (TCL).
- Easily extends the platform using common technologies like react js, java, spring, elide, liquibase, groovy, bash, go.
- Native integration with the most popular VCS like:
Github.
Azure DevOps
Bitbucket
Gitlab
- Support for SSH key (RSA and ED25519)
- Handle Personal Access Token
- Extends and create custom flows when running terraform remote operations with custom logics like:
Approvals
Budget reviews
Security reviews
Custom logic that you can build with groovy and bash scripts

### Org repo URL

https://github.com/AzBuilder/

### Project repo URL

https://github.com/AzBuilder/terrakube

### Additional repos
https://github.com/AzBuilder/terrakube-helm-chart
https://github.com/AzBuilder/terrakube-extensions

### Website URL

https://terrakube.org/

### Roadmap

https://github.com/orgs/AzBuilder/projects/6/views/1

### Contributing Guide

https://github.com/AzBuilder/terrakube/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/AzBuilder/terrakube/blob/main/CODE_OF_CONDUCT.md

### Maintainers file

https://github.com/AzBuilder/terrakube/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Terrakube shares many of the core values of CNCF, especially the following ones:
- **Open**: Terrakube is an open source platform that enables infrastructure automation and welcomes contributions from anyone who wants to make it better.
- **Platform Agnostic**: Terrakube was created with the idea of running on any cloud or on-premises environment, so Kubernetes is its preferred option for deployment.
- **Scalable**: Terrakube is designed to meet the needs of enterprise environments but its beneficial for small teams too.

### Benefit to the Landscape

Adding Terrakube to the CNCF landscape could benefit the cloud native community in several ways. For example:

- Terrakube could provide an open source alternative to closed source tools for remote infrastructure as code operations using Terraform, which could increase the adoption and innovation of cloud native technologies.
- Terrakube could integrate with various CNCF projects such as Kubernetes, OPA and Dex, which could enhance the interoperability and compatibility of cloud native solutions.
- Terrakube could fit into the CNCF landscape layers such as provisioning, runtime and platform, which could offer more choices and flexibility for cloud native users and developers.

### Cloud Native 'Fit'

In the provisioning layer, Terrakube could fit into the automation and configuration category, as it enables infrastructure as code automation and improves collaboration.

### Cloud Native 'Integration'

Terrakube is using the following CNCF projects:
- **Kubernetes**: Its the preferred way to install Terrakube using a helm chart
- **OPA**: Terrakube uses OPA policies to enforce best practices in the resources to be provisioned, see [Policy Enforcement](https://docs.terrakube.org/user-guide/policy-enforcement-opa)
- **DEX**: Terrakube uses DEX to provide cloud-agnostic authentication and authorization, so it can be easily integrated in various enterprise environments.

### Cloud Native Overlap

No overlap identified

### Similar projects

[Spacelift](https://spacelift.io/)
[Terraform Enterprise](https://developer.hashicorp.com/terraform/enterprise)
[Env0](https://www.env0.com/)

### Product or Service to Project separation

N/A

**Comment by telderfts** [comment]
Pretty disappointing that the CNCF would vote in this fashion. Expected more from them instead of hiding in the shadows.

**Comment by TheFoxAtWork** [comment]
@telderfts - Allow me to provide some background so the opinion and judgement you've shared can be more informed, in the hope that when next you perspective it is in a positive, inquisitive matter that seeks to understand what transpired so we all may improve, rather than the negative connotation the current phrasing conveys (which I don't believe to be your intent).

This, and similar votes around the time, were from the early days of the TOC's use of gitvote. At the time we had not yet established consistent procedures and expectations regarding the intentional use of these emojis as well as some unclear precedent in how votes should occur. 

Both of these issues have since been corrected; (see [our onboarding doc's section on voting](https://github.com/cncf/toc/blob/main/operations/onboarding.md#voting) which was created in early 2024 to address issues such as this).

This is why you see so many abstains instead of downvotes on this issue, a pattern no longer present in more recent votes except where the TOC member(s) may have a real or perceived conflict of interest.
