### ISSUE TITLE
[Sandbox] Logging Operator

### ISSUE THREAD

**Issue by sagikazarmark** [cncf/sandbox#42]
### Application contact emails

mark@sagikazarmark.hu, ospo@cisco.com, logging-operator@axoflow.com, gubasanyi@gmail.com

### Project Summary

The Logging Operator streamlines the deployment and configuration of a Kubernetes logging pipeline.

### Project Description

The Logging Operator orchestrates the deployment and management of log collectors and forwarders in a Kubernetes cluster, offering a Kubernetes-native configuration layer for filtering, enriching, and routing log messages. It provides a comprehensive selection of output options, including Elasticsearch, various object stores, and a diverse range of Software-as-a-Service (SaaS) log storage and analytics solutions.

This project empowers platform engineers with the ability to install and oversee the components of the logging infrastructure, as well as manage the configuration of logging at the cluster level. Additionally, it provides application developers with the autonomy to establish namespace-specific configurations that are tailored to their applications.

### Org repo URL

https://github.com/kube-logging

### Project repo URL

https://github.com/kube-logging/logging-operator

### Additional repos

https://github.com/kube-logging/fluentd-images
https://github.com/kube-logging/helm-charts
https://github.com/kube-logging/fluentd-drain-watch
https://github.com/kube-logging/syslogng-reload-image
https://github.com/kube-logging/log-generator
https://github.com/kube-logging/node-exporter-image
https://github.com/kube-logging/custom-runner
https://github.com/kube-logging/config-reloader
https://github.com/kube-logging/syslog_ng_exporter
https://github.com/kube-logging/fluent-plugin-label-router
https://github.com/kube-logging/fluent-plugin-tag-normaliser
https://github.com/kube-logging/eventrouter

### Website URL

https://kube-logging.dev

### Roadmap

https://github.com/orgs/kube-logging/projects/4

### Contributing Guide

https://github.com/kube-logging/.github/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/kube-logging/.github/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/kube-logging/logging-operator/blob/master/ADOPTERS.md

### Contributing or Sponsoring Org

https://opensource.cisco.com

### Maintainers file

https://github.com/kube-logging/logging-operator/blob/master/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

The CNCF hosts a vibrant and diverse community of developers and organizations. Contributing to this ecosystem allows the Logging Operator project to attract more contributors, leading to better and faster improvements. Furthermore, the CNCF is able to provide a vendor neutral home for the project, allowing for collaboration among various vendors, fostering the creation of a solution that delivers collective benefits to all stakeholders within the ecosystem.

### Benefit to the Landscape

As a well-developed and vendor-neutral solution, the Logging Operator stands as a distinctive project, benefiting both cloud-native consumers and vendors alike. It facilitates consumers by empowering them to deploy and manage their logging pipelines universally across diverse environments. Simultaneously, it enables vendors to offer their integrations, thereby granting consumers the flexibility to forward their logs seamlessly.

### Cloud Native 'Fit'

The Logging Operator best fits in under the Logging section in the Observability area of the landscape.

### Cloud Native 'Integration'

The project installs, configures and manages Fluentbit and Fluentd.

Integration with OpenTelemetry is in progress.

### Cloud Native Overlap

There is no strong overlap with existing solutions that are as robust and mature as the Logging Operator. Potential future overlap could emerge with the stabilization of OpenTelemetry's logging component, but we view this as an opportunity for integration rather than a direct competition. We believe the Logging Operator's proven track record and maturity provide it with a distinct advantage.

### Similar projects

https://github.com/fluent/fluent-operator
https://github.com/vmware/kube-fluentd-operator
https://github.com/OT-CONTAINER-KIT/logging-operator

### Product or Service to Project separation

N/A

### Project presentations

Show Me Your Labels and I’ll Tell You Who You Are - Kubecon EU 2022
https://www.youtube.com/watch?v=TWf1ho0XMyM

Logging Operator the Cloud Native Fluent Ecosystem - Fluentcon 2021
https://www.youtube.com/watch?v=uWc7FgoBL60

Bring Your Own Bytecode to the Logging Party - WASM days 2022
https://www.youtube.com/watch?v=yfWaY6lyRtY

Logging on Kubernetes the Easy Way
https://vday.hu/slides/14h00_nagy_Guba_Sandor.pdf

**Third party posts:**

BanzaiCloud Logging Operator in Kubernetes Simplified in 5 minutes.
https://alexandre-vazquez.com/banzaicloud-logging-operator/

Kubernetes Logging with Banzai Logging Operator
https://yitaek.medium.com/kubernetes-logging-with-banzai-logging-operator-9d27c35abcb4

### Project champions

@justaugustus
@detiber
@sagikazarmark
@pepov
@tarokkk
@ahma

**Comment by nikhita** [comment]
@sagikazarmark  it would be great if you could present Logging Operator at a TAG Observability meeting before the next sandbox vote on Sept 12.

@alolita @halcyondude

**Comment by sagikazarmark** [comment]
@nikhita sure thing!

@alolita @halcyondude can you help me find the right meeting for us to present the project?

**Comment by sagikazarmark** [comment]
@alolita @halcyondude can you help me find an appointment before Sept 12? Where should I reach out to TAG Observability?

**Comment by alolita** [comment]
Hi @sagikazarmark The next TAG Observability meeting is on Sep 5 2023 (first Tuesday of each month) and the next meeting is on Sep 19 2023. Please join in for the Sep 5 2023 meeting to present on the Logging Operator. Please share details about what you plan to cover in the presentation. Typically our meeting is 45 minutes long so I recommend a 25 minute presentation with some time for Q&A.

**Comment by sagikazarmark** [comment]
Thank you @alolita!

@tarokkk will share some details about the presentation.

25 minutes should be ample time to present the Logging Operator and Q&A in my opinion.

**Comment by alolita** [comment]
Awesome. @tarokkk please share an abstract when you can before Sep 5.

**Comment by tarokkk** [comment]
Hi @alolita!

Thanks for the opportunity! I prepared a short abstract If you need a more detailed version, please notify me!


**Logging Operator Sandbox Application**

The presentation will cover three key points:
1. Brief history of the Logging operator
Just a quick review of why and how it started, and what problems the project aimed to solve.
2. Simple example walkthrough
Learn by example. It’s easier to show what the Logging operator does and how. A simple example of abstracting away the complexity of logging pipelines.
3. Vision and Roadmap
There are several plans to make the Logging operator a go-to solution when it comes to Kubernetes logging. I’ll talk about the current features under development and possible future steps.

**Comment by alolita** [comment]
Thanks! Look forward to your joining in today for the presentation.

**Comment by rochaporto** [comment]
Link to TAG-Observability meeting notes:
https://docs.google.com/document/d/1_QoF-njScSuGFI3Ge5zu-G8SbL6scQ8AzT1hq57bRoQ/edit#heading=h.xb41lzm5je40

**Comment by sagikazarmark** [comment]
Thank you @Cmierly ! I'll review the checklist and reply on the new issue.
