### ISSUE TITLE
[Sandbox] Kanister

### ISSUE THREAD

**Issue by mlavi** [cncf/sandbox#46]
### Application contact emails

Mark.Lavi@veeam.com, Pavan.N.Devaraj@veeam.com, Thomas.Manville@veeam.com

### Project Summary

An extensible framework for application-level data management on Kubernetes.

### Project Description

Kanister provides a cloud native, extensible framework for data protection with application consistent backup and recovery of Kubernetes workloads. Distributed, traditional, and persistent workloads hosted on Kubernetes often require maintenance (also called “Day 2 operations”). The Kanister controller executes ActionSets, Profiles, and Blueprint custom resources for operations with any API, CLI, or Kanister task. Complex Kanister orchestration examples include invoking Kubernetes operators, quiescing storage, and leveraging logical and custom tooling for application, traffic, cluster, and external control systems.

### Org repo URL

https://github.com/kanisterio/

### Project repo URL

https://github.com/kanisterio/kanister

### Website URL

https://kanister.io/

### Roadmap

https://github.com/kanisterio/kanister/blob/master/ROADMAP.md

### Roadmap context

The Kanister roadmap contains project, community, and engineering work to prepare for [CNCF.io](http://cncf.io/) sandbox project submission. We’ll work to deprecate code that only Kasten K10 uses, improve project governance to reuse some Kubernetes principles, and formally separate blueprints from a testing and project supported (project inclusive) versus examples and community supported (exclusive, move to a new public repo in the org).

### Contributing Guide

https://github.com/kanisterio/kanister/blob/master/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/kanisterio/kanister/blob/master/CODE_OF_CONDUCT.md

### Adopters

https://github.com/kanisterio/kanister/blob/master/ADOPTERS.md

### Contributing or Sponsoring Org

https://Kasten.io by parent company: https://Veeam.com

### Maintainers file

https://github.com/kanisterio/kanister/blob/master/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Kanister as a CNCF project would focus attention and potentially converge bespoke end-user, project, and vendor efforts around data protection on Kubernetes by providing neutrality and visibility.

### Benefit to the Landscape

Providing complex application maintenance and orchestration with cloud native operations on Kubernetes. The [Data on Kubernetes Community](https://dok.community/) and their recent collaboration with SIG-Storage is evidence for the evolving data protection needs for Kubernetes workloads.

Kanister could potentially compliment https://k8up.io/ as well as the other projects listed in the Cloud Native Overlap section that follows.

### Cloud Native 'Fit'

This project fits primarily with the “Orchestration and Management: Scheduling and Orchestration” category projects,
but perhaps also:

- Provisioning: Automation and Configuration
- App Definition & Development:
    - Application Definition & Image Build
    - Continuous Integration & Delivery
- Runtime: *determined not to be appropriate because they are bound to very specific domains*
    - Cloud Native Storage
        - Kasten has been heavily involved here with the Data Protection working group and Storage/CSI providers
    - Database

Would it be possible to create a new category under Runtime for data protection?

The distinguishing factor is that Kanister is focused on: “day 2” data protection maintenance operations versus the workload provisioning lifecycle. Kanister can orchestrates across multiple potential architectural boundaries, such as infrastructure (storage and network), micro service, application, Kubernetes, etc.

### Cloud Native 'Integration'

Kanister provides a Helm Chart, but Kanister depends on the downstream (non-CNCF) open source project (Apache 2.0 license) https://kopia.io/

### Cloud Native Overlap

Overlapping projects:

1. https://cloudcustodian.io/  manage resources by filtering, tagging, and then applying actions to them
3. https://www.crossplane.io/ Encapsulate policies, permissions, and other guardrails to orchestrate applications and infrastructure
5. https://keptn.sh/docs/1.0.x/concepts/automated_operations/#declarative-operations-as-code
7. https://openkruise.io/ 
9. https://kubevela.io/

### Similar projects

Above mentioned Cloud Native Overlap projects.

Many offerings have limitations that Kanister accommodates in a cloud native, non-proprietary manner (multiple databases, user maintainable operations, extensible framework). Kanister provides application consistent backup and recovery to accommodate operational and storage efficiency by using a combination of snapshot, logical, and/or system methods.

|                                                      Project |       Sponsor       | Cloud Native Architecture                                    | Orchestration: Script                                        | Backup:  CSI Snapshot | Backup: Logical                                              | Backup: System                                        |
| -----------------------------------------------------------: | :-----------------: | ------------------------------------------------------------ | ------------------------------------------------------------ | :-------------------: | ------------------------------------------------------------ | ----------------------------------------------------- |
|                                      [K8up](https://k8up.io) | CNCF.io/TAG-Storage | K8up operator has [Schedule, Restore, Archive, Backup, Check, Prune, Backend, Effective Schedule, PreBackupPod](https://k8up.io/k8up/2.7/references/object-specifications.html) CRs | [Backup Commands](https://k8up.io/k8up/2.7/how-tos/application-aware-backups.html) are inline, sequential scripts, per workload via an annotation that requires CLI tool to output to STDOUT.<br />Project could invoke/adopt Kanister to improve! |          No; [PVC file backup](https://k8up.io/k8up/2.7/explanations/backup.html)     | Conditional on orchestration with [Pre-Backup Pods](https://k8up.io/k8up/2.7/how-tos/prebackuppod.html#PreBackup-pods)  environment variables require spec definition, per workload, medium effort. | Conditional on orchestration, hard effort.            |
|                              [Kanister](https://kanister.io) |   Kasten by Veeam   | [Kanister controller](https://docs.kanister.io/architecture.html) operates on Blueprint CR and Profile CR invoked by ActionSet CRs. Many [functions](https://docs.kanister.io/functions.html) in addition to scripting. ActionSet history and Prometheus metrics to track operations. Because blueprints and profiles are Kubernetes objects, they foster isolation from workload configuration, reuse across different application instances, and a single source of truth. | Resides in a Blueprint's Action, which can run in parallel and in different orchestration stages to accommodate non-sequential operations. |          Yes          | Conditional on orchestration with [sidecar container with logical tooling](https://docs.kanister.io/tooling.html) and script, easy effort. | Conditional on orchestration, easy effort.            |
| [Postgres-operator](https://postgres-operator.readthedocs.io) |     Zalando SE      | Operator                                                     | None.<br />Kanister blueprints can orchestrate pre-operator, operator invocation, and post-operator operations to coordinate systems and additional requirements outside Postgres. |          No           | [Yes](https://postgres-operator.readthedocs.io/en/latest/administrator/#logical-backups), only for Postgres.<br />Kanister accommodates any workload via blueprint and can orchestrate the operator to improve storage artifact efficiency. | No                                                    |
|                                  [Velero](https://velero.io) |       VMware        | [Velero controllers](https://velero.io/docs/v1.12/how-velero-works/) operate on DataUpload, DataDownload, BackupRepository CRs, Velero Node Agent daemonset, [Storage Provider Plugins](https://velero.io/docs/v1.12/overview-plugins/). | [Backup](https://velero.io/docs/v1.12/backup-hooks/) and [Restore](https://velero.io/docs/v1.12/restore-hooks/) Hooks are inline, sequential scripts, per workload.<br />Project could invoke/adopt Kanister to improve! |          Yes          | Conditional on orchestration script, medium  to hard effort. | Conditional on orchestration and plugin, easy effort? |

### Product or Service to Project separation

Kasten K10 by Veeam still has some references and a native integration, but the Kanister project and codebase has been separate since inception. A roadmap item removes K10 utilities that Kanister itself does not use, decoupling it from K10 releases.

### Project presentations

- [Kanister.io CNCF Webinar](https://community.cncf.io/events/details/cncf-cncf-online-programs-presents-cncf-live-webinar-kubernetes-data-protection-requires-orchestration-kanisterio-delivers/)
- [TAG-Storage Kanister Presentation](https://www.youtube.com/watch?v=Cf3-XLdLinU)
- [Kanister.io slides](https://github.com/kanisterio/demo/raw/main/webinar/cncf.io/CNCF.ioWebinar-Kanister.io-Blueprints.pptx) used in the webinar and TAG-Storage meeting

### Project champions

Thomas.Manville@veeam.com

### Additional information

The [Kanister.io](http://kanister.io/) open source, cloud native, and Apache 2.0 licensed project was announced and launched at KubeCon 2017 and has steadily gained data protection capabilities and blueprints. Adoption by Kasten customers and independent organizations is apparent by community feedback. The project is hosted on public GitHub for code, releases, and issues under the Kanister organization. An independent Kanister Slack instance is open to the community for questions, discussion, and feedback. Open bi-weekly community meetings take place on Zoom, the agenda and meeting notes are captured into a public Google document, and each agenda covers community topics on the project and current GitHub issues.

Kanister is very compatible with Kubernetes and the CNCF community!

**Comment by nikhita** [comment]
@mlavi it would be great if you could present Kanister at a TAG Storage meeting before the next sandbox vote on Sept 12.

cc @xing-yang

**Comment by xing-yang** [comment]
@mlavi We have TAG Storage meetings on Aug 9 and Aug 23.  Let us know if you want to present at either of these meetings. Thanks.

**Comment by mlavi** [comment]
@xing-yang @nikhita I've confirmed availability of our team and myself for the August 9 TAG Storage meeting, please add us to the agenda. I'm unsure what will happen outside of reviewing the above, is there anything we can do to prepare?

**Comment by xing-yang** [comment]
@mlavi Sounds good.  I added Kanister to the TAG Storage agenda doc.

**Comment by xing-yang** [comment]
Here's the [recording](https://www.youtube.com/watch?v=Cf3-XLdLinU) from Kanister's presentation at TAG Storage meeting.
cc @chira001

**Comment by xing-yang** [comment]
Hi @mlavi, thanks for addressing comments from the TAG Storage meeting!  I see that in [Kubecon EU 2022: Your Manila CephFS Share Backups Belong to S3 - Robert Vasek, CERN](https://youtu.be/XfpP9pBTXfY?t=1623), there is a comparison (mainly on performance) between Restic (Velero) and Kopia (Kanister).  Can you also create a table that compares the functionalities of these projects, including K8up?  See an example [here](https://github.com/cncf/sandbox/issues/29#issuecomment-1589526650). Thanks!

**Comment by mlavi** [comment]
@xing-yang I provided a table of comparisons last week when I edited the Similar Projects section of the application, above. Please review, does that satisfy your request?

**Comment by xing-yang** [comment]
Hi @mlavi, thank you very much for addressing my comments!  I still have some questions.  The table says that PostgreSQL operator does not support restore operation.  There are many PostgreSQL operators.  I don't think we can say none of them supports restore. Here's one blog talking about PostgreSQL operator restore: https://thedatabaseme.de/2022/05/03/restore-and-clone-from-s3-configure-zalando-postgres-operator-restore-with-wal-g/.  The tables also says that the PostgreSQL operator "does not accommodate full application consistency to storage". I think that since those operators use logical backups, it should be application consistent.  It may be better to put all the projects to be compared (including Kanister) in the left column, and list the features you want to compare in the top row (i.e., whether it supports application consistency, whether it uses logical backup or other technologies, supports concurrent operations, etc.).  Thanks.

**Comment by mlavi** [comment]
@xing-yang Updated the comparison table, thank you for correcting my oversight on postgres-operator, this is much improved!

**Comment by xing-yang** [comment]
Thanks @mlavi!  The table looks much better.  One comment: I think K8up does not support CSI snapshot yet.

**Comment by mlavi** [comment]
@xing-yang Thank you for your diligence, another flawed assumption on my part. K8up Snapshot contrast fixed with a clarification.

**Comment by xing-yang** [comment]
Thanks for addressing my comments, @mlavi!  The table looks good now.

**Comment by mlavi** [comment]
Hello Crystal, we're planning the onboarding tasks and will respond over there with progress.

We are planning a Veeam Press Release and Blog about the acceptance to attract people to the Kasten by Veeam booth to see Kanister demos (since we're too early for anything else at Kubecon). Is there anything we should coordinate (CNCF review?) or guidelines for this? Will CNCF echo any of our announcements via social media, etc.?

Thanks.

**Comment by amye** [comment]
We do not offer marketing for sandbox projects! Incubating and graduated projects can participate in marketing.

**Comment by mlavi** [comment]
Work is tracked here, will return here when item checkbox achieved: https://github.com/orgs/kanisterio/projects/2
