### ISSUE TITLE
[Sandbox] KCL

### ISSUE THREAD

**Issue by Peefy** [cncf/sandbox#48]
### Application contact emails

xiaodong.dxd@antgroup.com
xpf6677@gmail.com
shushan.css@antgroup.com
huangch96@gmail.com
zongzhe1024@163.com
897013703@qq.com

### Project Summary

Constraint-based record and functional language and tools that is primarily utilized in cloud-native configurations and policy scenarios.

### Project Description

With cloud-native language and tools, KCL aims to address the cognitive burden of large-scale cloud-native static configuration, YAML/template bloat, and customization/validation of third-party applications through the following features:

+ Concealing infrastructure and platform details by establishing more appropriate API abstractions.
+ Managing large-scale configuration data across teams without side effects using the configuration language and tools.
+ Mutating and validating existing config files or manifests with Kubernetes configuration integrations.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/kcl-lang

### Project repo URL in scope of application

https://github.com/kcl-lang/kcl

### Additional repos in scope of the application

https://github.com/kcl-lang/kcl-go
https://github.com/kcl-lang/vscode-kcl
https://github.com/kcl-lang/kpm
https://github.com/kcl-lang/krm-kcl
https://github.com/kcl-lang/kubectl-kcl
https://github.com/kcl-lang/helm-kcl
https://github.com/kcl-lang/kustomize-kcl
https://github.com/kcl-lang/kpt-kcl
https://github.com/kcl-lang/kcl-operator

### Website URL

https://kcl-lang.io/

### Roadmap

https://kcl-lang.io/docs/community/release-policy/roadmap

### Roadmap context

N/A

### Contributing Guide

https://kcl-lang.io/docs/community/contribute/

### Code of Conduct (CoC)

https://github.com/kcl-lang/kcl/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/kcl-lang/kcl/blob/main/ADOPTERS.md

### Contributing or Sponsoring Org

N/A

### Maintainers file

https://github.com/kcl-lang/kcl/blob/main/MAINTAINERS

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

KCL has reached the production readiness stage and has been recognized by some adopters. We strongly believe that KCL is a missing piece of CNCF in the fields of automation and configuration. By joining CNCF, we aim to increase the project's visibility and promote community adoption and participation, as a strong and well-known organization is essential for driving a language ecosystem. We hope that the CNCF community can provide valuable ideas and contributions to help achieve this goal. Additionally, we look forward to receiving guidance from CNCF in building KCL communities.

We believe that incorporating KCL into the CNCF ecosystem will significantly enhance the project's visibility. Under the guidance of CNCF, we can follow their procedures and standards, set achievable goals to improve our language and tools, promote community participation, and integrate KCL with other cloud-native projects.

### Benefit to the Landscape

Firstly, KCL adheres to the Kubernetes Resource Model (KRM) specification, making it an ideal fit for Kubernetes integration. Additionally. Secondly, KCL aims to support a wide range of cloud-native configuration tools. By leveraging the dynamic characteristics of the language, it can non-invasively address the limitations of existing CNCF configuration management tools, potentially simplifying the use of multiple tools in the CNCF landscape.

### Cloud Native 'Fit'

KCL was originally designed to tackle the challenges of static configuration and automation in cloud-native configurations, it was built using cloud-native technologies and fits within the CNCF "Automation & Configuration" area.

### Cloud Native 'Integration'

KCL integrates with most configuration management tools in the cloud native area, and it also supports abstraction, mutation, and validation of configurations at both the client and Kubernetes runtime.

+ KRM KCL Integration: https://github.com/kcl-lang/krm-kcl
+ Kubectl KCL Plugin: https://github.com/kcl-lang/kubectl-kcl
+ Kustomize KCL Plugin: https://github.com/kcl-lang/kustomize-kcl
+ Helm KCL Plugin: https://github.com/kcl-lang/helm-kcl
+ KPT KCL Plugin: https://github.com/kcl-lang/kpt-kcl
+ KCL Kubernetes Operator: https://github.com/kcl-lang/kcl-operator
+ ArgoCD KCL Plugin: https://kcl-lang.io/docs/user_docs/guides/gitops/gitops-quick-start

### Cloud Native Overlap

KCL is a programming language with full toolchain implementation that features a distinctive implementation technique and user interface in the cloud-native landscape. Despite its unique qualities, there are also similar projects, such as [ytt](https://github.com/carvel-dev/ytt) and [tanka](https://github.com/grafana/tanka), that seek to address the same challenges.

### Similar projects

[ytt](https://github.com/carvel-dev/ytt): ytt utilizes a combination of static configuration and dynamic programming language to achieve dynamic expansion of configuration. KCL can accomplish similar functions. Furthermore, KCL offers additional schema, constraint definitions and abstraction capabilities, further simplifying the user configuration interface.
[Tanka](https://github.com/grafana/tanka): Tanka is the robust configuration utility for Kubernetes cluster, powered by the jsonnet language. Compared to Tanka and Jsonnet, KCL has done more work in schema definition, static type checking, and constraints to shift configuration risks to the left, rather than bringing errors to the language runtime.

### Landscape

Yes

### Business Product or Service to Project separation

N/A

### Project presentations

https://kcl-lang.io/blog/2022-declarative-config-overview
https://medium.com/@xpf6677/gitops-with-kcl-programming-language-cb910230e310
https://medium.com/dev-genius/manage-kubernetes-configurations-with-kcl-oci-artifacts-39d311d366e1

### Project champions

N/A

### Additional information

[Project Introduction Slides](https://kcl-lang.io/talks/kcl-intro.pdf)

**Comment by nikhita** [comment]
@Peefy can you present KCL at a TAG App Delivery meeting before the next sandbox vote on Sept 12?

cc @joshgav

**Comment by joshgav** [comment]
Thank you @nikhita!

@Peefy we've started to discuss KCL in our Slack channel [#tag-app-delivery](https://cloud-native.slack.com/archives/CL3SL0CP5/p1690204937094849) - would love for you to join the conversation. You can get an invite to CNCF Slack at <https://slack.cncf.io/>.

You could present at the TAG's Aug 2 or Aug 16 general meetings; DM me in Slack to finalize. We'd like to talk with you all about the values KCL offers users, its high-level technical architecture, your near-term roadmap, and the state of your community and governance. We can ask maintainers of Helm, kpt and ytt to attend and help us review too.

**Comment by Peefy** [comment]
> Thank you @nikhita!
> 
> @Peefy we've started to discuss KCL in our Slack channel [#tag-app-delivery](https://cloud-native.slack.com/archives/CL3SL0CP5/p1690204937094849) - would love for you to join the conversation. You can get an invite to CNCF Slack at https://slack.cncf.io/.
> 
> You could present at the TAG's Aug 2 or Aug 16 general meetings; DM me in Slack to finalize. We'd like to talk with you all about the values KCL offers users, its high-level technical architecture, your near-term roadmap, and the state of your community and governance. We can ask maintainers of Helm, kpt and ytt to attend and help us review too.



> @Peefy can you present KCL at a TAG App Delivery meeting before the next sandbox vote on Sept 12?
> 
> cc @joshgav

Thank you @nikhita! I will present at the TAG's Aug 16 general meetings and I've joined the slack channel.

**Comment by Peefy** [comment]
> Thank you @nikhita!
> 
> @Peefy we've started to discuss KCL in our Slack channel [#tag-app-delivery](https://cloud-native.slack.com/archives/CL3SL0CP5/p1690204937094849) - would love for you to join the conversation. You can get an invite to CNCF Slack at https://slack.cncf.io/.
> 
> You could present at the TAG's Aug 2 or Aug 16 general meetings; DM me in Slack to finalize. We'd like to talk with you all about the values KCL offers users, its high-level technical architecture, your near-term roadmap, and the state of your community and governance. We can ask maintainers of Helm, kpt and ytt to attend and help us review too.

Thank you @joshgav and your interest in the KCL project! I will present at the TAG's Aug 16 general meetings and I've joined the slack channel. 😄

**Comment by joshgav** [comment]
Thank you for the presentation @Peefy! Notes and recordings are linked from this issue comment: <https://github.com/cncf/tag-app-delivery/issues/430#issuecomment-1693627540>

My conclusion is that KCL would be a good fit for CNCF sandbox.

**Comment by Peefy** [comment]
> 

Thank you for the review! I have browsed the notes and recordings linked in the question comment and they have no issues. Thank you to CNCF sandbox for recognizing the KCL project.

**Comment by roberthstrand** [comment]
After a quick look at the docs, it looks like a great fit. I'm going to review the video as well, but I vaguer it won't change my mind.

**Comment by Peefy** [comment]
Thank you @Cmierly ! I'll review the checklist.
