### ISSUE TITLE
[Sandbox] Wasm Mock Server

### ISSUE THREAD

**Issue by alanpoon** [cncf/sandbox#50]
### Application contact emails

brightshadowx@gmail.com

### Project Summary

Software testing tool using WebAssembly

### Project Description

MITM server for software testing that supports both user defined wasm functions and Websocket connection.
It is no longer feasible to create separate MITM tool for each programming language.
This tool can support multiple programming languages either through WebAssembly support or via websocket.
This tool can help to streamline the tools and skills required of software tester.
- Supports [http/https/tcp/websocket] MITM
- Extensible to any protocol

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/wasmmock

### Project repo URL in scope of application

https://github.com/wasmmock/wasm_mock_server

### Roadmap

https://github.com/wasmmock/wasm_mock_server

### Contributing Guide

Still closed source ( single developer status)

### Code of Conduct (CoC)

Still closed source  ( single developer status)

### Maintainers file

Still closed source  ( single developer status)

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

I was fortunate enough to be invited as a speaker on one of a [CNCF event](https://cloudnativewasmdayeu22.sched.com). I showcased how to make a multiplayer game using a [CNCF sandbox project](https://github.com/wasmCloud). I made several friends whose projects are incubating in CNCF. By donating a project to CNCF, will allow me to receive financial support for me to keep in touch with them in CNCF events.

### Benefit to the Landscape

As a full time software tester, I hope to be able to share my software testing tool to more people. At the same time, bring more software tester to CNCF.

### Cloud Native 'Fit'

Using WebAssembly, software testing and automation can be done in the cloud. Hence, reduces the steep learning curve of setting up test environment.

### Cloud Native 'Integration'

This project depends on [waPC](https://wapc.io). One of its founder, Kevin Hoffman, or known as autodidaddict, subsequently founded Cosmonic. The company has a CNCF sandbox project, which is wasmcloud.

https://lib.rs/~autodidaddict

### Cloud Native Overlap

Currently, MITM testing is associated to enhancing security of web application and backend server. CNCF has several projects that does security and vulnerability checks.

### Similar projects

N/A

### Landscape

N/A

### Business Product or Service to Project separation

N/A

## Video Resources
| Video Description  | Video Link |
| ------------- | ------------- |
| [Software testing] Wasm mock server websocket mitm (1)  | https://www.youtube.com/watch?v=xuspE_u71Og  |
| 【软件测试】wasm mock server Websocket 示范  | https://www.bilibili.com/video/BV1kg4y157hE/?spm_id_from=333.999.0.0&vd_source=8513215e56d2a613eb870e5ccc630e88  |
| 【rust conf china】应用WAPC做软件测试工具   | https://www.bilibili.com/video/BV1ws4y1k7pR/?spm_id_from=333.999.0.0&vd_source=8513215e56d2a613eb870e5ccc630e88  |

### Project champions

Liam Randall

**Comment by nikhita** [comment]
@alanpoon It would be great if you could present at one of the WG WASM meetings - https://github.com/cncf/tag-runtime/blob/main/wg/wasm.md.

cc @raravena80 @helayoty @devigned @endocrimes

**Comment by nikhita** [comment]
For the record - @alanpoon will be presenting Wasm Mock Server in the WG WASM meeting on [8th August](https://cloud-native.slack.com/archives/C056EDRH4PJ/p1690428038091399?thread_ts=1690351750.312349&cid=C056EDRH4PJ).

Thanks for helping coordinate this, @rajaskakodkar and @devigned!

**Comment by jberkus** [comment]
I met with the author of this project at WASMcon.  I'll provide feedback at the meeting.

**Comment by alanpoon** [comment]
I am maintaining the live demo at this page [https://pg.wasmmock.xyz/](https://pg.wasmmock.xyz/)

**Comment by kgamanji** [comment]
WG WASM  meeting notes here: https://docs.google.com/document/d/1d6PvdCuKbSdcuXG2M9fBSDQPTPfHYA0PPDTM2plbH3I/edit#heading=h.6lmmvsjb4n23

**Comment by justincormack** [comment]
Hi, we reviewed this in the sandbox review, and we feel this project is much too early for the Sandbox. We do not generally accept projects at such an early stage with so few commits. We recommend coming back when a larger community has formed and the project meets more use cases.
