### ISSUE TITLE
[Sandbox] Kairos

### ISSUE THREAD

**Issue by mudler** [cncf/sandbox#52]
### Application contact emails

mudler@kairos.io, itxaka@kairos.io, dimitris@kairos.io, mauro@kairos.io

### Project Summary

Kairos is a meta-Linux distribution to build immutable edge Kubernetes.

### Project Description

Kairos is an open-source project that simplifies edge, cloud, and bare-metal OS lifecycle management. It is a framework to build immutable Linux meta-distribution for edge Kubernetes, enabling users to customize or run bootable Kubernetes and OS images for edge devices with ease. Kairos offers features like immutability, security, container-based management, P2P mesh for self-coordinated deployments, and distro agnosticism. It allows users to create their own cloud on-premises, provision nodes using custom or Kairos images, and manage the entire cluster lifecycle with Kubernetes. Kairos aims to provide a unified, cloud-native approach to OS management.

With Kairos, users can effortlessly create Kubernetes clusters with Kubernetes distributions such as k3s and any Linux distribution of their choice. Kairos images are full OS images that are used in atomic upgrades. 

Instead of the traditional upgrade process involving package managers, Kairos uses a common, generic process across all the distributions: A/B image swap using standard container images. Users can choose to use Kairos container images or build custom ones that can be based from upstream Linux distribution images.

Kairos also supports the creation of highly flexible and scalable multi-node, single clusters that can span multiple regions with k3s, providing enhanced adaptability to meet varying requirements. In order to orchestrate deployments Kairos doesn’t need an external service, k3s HA deployments are fully autonomous, removing friction of deploying Kubernetes at the edge.

### Org repo URL (provide if all repos under the org are in scope of the application)

github.com/kairos-io

### Project repo URL in scope of application

github.com/kairos-io/kairos

### Additional repos in scope of the application

The organization with all the repositories is in scope of application

### Website URL

https://kairos.io

### Roadmap

https://github.com/orgs/kairos-io/projects/2

### Roadmap context

In our office hours and community channels, we openly discuss the Roadmap, gathering input and prioritizing items through collaborative discussions. Our approach is strongly oriented towards fostering a thriving ecosystem, and we actively seek opportunities for interoperability with CNCF projects and other open-source initiatives. This commitment helps us better address the interests and needs of our community.

### Contributing Guide

https://github.com/kairos-io/community/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/kairos-io/community/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/kairos-io/community/blob/main/ADOPTERS.md

### Contributing or Sponsoring Org

https://spectrocloud.com

### Maintainers file

https://github.com/kairos-io/community/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Kairos seeks to apply for CNCF to find a vendor-neutral home for its open-source project.

Kairos wants to establish itself as a cloud-native meta-Linux distribution tailored for Kubernetes. From its inception, Kairos was designed with cloud-native and container-first principles in mind. 

By becoming a part of CNCF, Kairos aims to demonstrate its commitment to managing expansion in an open-source manner and ensure neutral governance for its growing community of users and contributors. The CNCF platform will serve as a catalyst for community adoption and encourage contributions from developers. Additionally, being a part of CNCF allows Kairos to learn from other projects and actively contribute back to the cloud-native community, aligning with the maintainer's ethos.

### Benefit to the Landscape

The CNCF ecosystem would benefit from having a vendor-neutral project that applies cloud-native approaches to OS management. 
It seems a natural solution that does not prefer any distribution or seek any sort of promotion or solution vendor-lock in. 

The user is free to pick the OS of their choice, and just benefit from Immutability, A/B upgrades, where OS images are delivered as standard container images.

There are no similar projects to my knowledge already in the CNCF ecosystem targeting directly the OS management layer with a cloud-native, distro-agnostic first approach. 

### Cloud Native 'Fit'

The project is a natural fit for the CNCF TAG Runtime. There has been demand in creating a special interest group for operative systems (see: https://github.com/kairos-io/kairos/discussions/1660), and we are happy to collaborate with.

### Cloud Native 'Integration'

When it comes to Kubernetes deployment, Kairos defaults to several components in the CNCF landscape:
K3s https://github.com/k3s-io/k3s
Kube-vip https://kube-vip.io/ (I think at the time of writing this it’s in the process, right?)

### Cloud Native Overlap

As far as I know, there are no similar projects in the CNCF landscape

### Similar projects

Outside of the CNCF landscape there are projects similar or that are tangentially related to Kairos. 
To some extent, Kairos shares a similar philosophy to k3os (https://github.com/rancher/k3os) and linuxkit (https://github.com/linuxkit/linuxkit). It can be actually seen as a “mix” of the two with a truly distro-agnostic approach, with a strong focus on Kubernetes and maintenance. Kairos has roots on the Elemental toolkit project (https://github.com/rancher/elemental-toolkit), indeed it shares some of the feature sets, while it expands on security and advanced customization features.

### Landscape

No, we are not listed in the Landscape

### Business Product or Service to Project separation

Spectro Cloud does provide Edge solutions to run Kubernetes and uses Kairos as base to build custom OS images for Enterprise customers.

### Project presentations

There is a media section on the Kairos website: https://kairos.io/docs/media/

The project was presented in various conferences:

- FOSDEM 2023: https://www.youtube.com/watch?v=XD5nfMf59v4
- CNCF webinar: https://www.youtube.com/watch?v=kiDQujibz2k
- SCaLE: https://www.youtube.com/watch?v=GuxIiludGgA
- KCD Amsterdam: https://community.cncf.io/events/details/cncf-kcd-netherlands-presents-kubernetes-community-days-amsterdam-2023/
- KCD France: https://www.youtube.com/watch?v=46qcE5MC6-8&t=17s
- KCD Czech: https://www.youtube.com/watch?v=dwS-dBAAuOk
- Devconf.cz: https://www.youtube.com/watch?v=UmBxh5q_AF0

### Additional information

We have an open issue to formally collect all the adopters and external stakeholders, however, there are companies like Spectro Cloud which is funding the project entirely and using it in production environments.

There are individuals from companies involved in the community and/or contributing directly to the project, such as Intel [1], Deutsche Bahn or Facebook.

1: We have published for instance a whitepaper with the Intel team addressing Security at the Edge in Kubernetes: https://kairos.io/blog/2023/04/18/kairos-is-now-part-of-the-secure-edge-native-architecture-by-spectro-cloud-and-intel/

**Comment by mudler** [comment]
> @mudler It would be great if you could present Kairos at a TAG Runtime meeting.
> 
> @rajaskakodkar can help coordinate :)
> 
> cc @raravena80 @helayoty

I'd be happy to!

**Comment by jberkus** [comment]
Part of Kairos is Linux images.  Does the project fork any Linux distribution?  Asking because that would affect licensing.

**Comment by mudler** [comment]
> Part of Kairos is Linux images. Does the project fork any Linux distribution? Asking because that would affect licensing.

No, it does not fork any Linux Distribution, the process is explained here: https://kairos.io/docs/reference/build-from-scratch/

**Comment by mudler** [comment]
CNCF TAG-Runtime meeting recording: https://www.youtube.com/watch?v=kTG8FuKzGYE&t=563s

**Comment by mauilion** [comment]
let's get a review from Tag Runtime after the presentation

**Comment by TheFoxAtWork** [comment]
Requesting an update from tag-runtime on the outcome of the meeting

**Comment by jberkus** [comment]
Kairos builds Linux but does not include it.  As such, I wouldn't assume a licensing issue, although it might be nice to run that past the legal committee.

**Comment by raravena80** [comment]
Revisited the [notes](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.gt01xb71fe19) and [presentation](https://youtu.be/kTG8FuKzGYE) for the [project](https://kairos.io/) - looks good. I don't see any licensing issues here because the project code itself doesn't include code that is used by other distros (to create those specific other distros). However, I'm asking @mudler to confirm.  After confirmation, I think this is good for a vote.

**Comment by mudler** [comment]
> Revisited the [notes](https://docs.google.com/document/d/1k7VNetgbuDNyIs_87GLQRH2W5SLgjgOhB6pDyv89MYk/edit#heading=h.gt01xb71fe19) and [presentation](https://youtu.be/kTG8FuKzGYE) for the [project](https://kairos.io/) - looks good. I don't see any licensing issues here because the project code itself doesn't include code that is used by other distros (to create those specific other distros). However, I'm asking @mudler to confirm. After confirmation, I think this is good for a vote.

Yes I can confirm, Kairos does not include code by other distros, it actually is composed of a set of standalone golang binaries (https://github.com/kairos-io/kairos-agent) and configuration files (for e.g. dracut configurations) that are packed in a container image, that we call Kairos framework. Those images can then be overlayed on top of container images from other distros, anyone can build their own images bu using any existing compatible OS as a base.

**Comment by amye** [comment]
On hold for a TOC discussion around distributions more generally

**Comment by cathyhongzhang** [comment]
I think this project is a good addition to CNCF. I have a question though. Could you clarify why it is a kubernetes distribution specific for edge? Does it slim down the Kubernetes in some way?

**Comment by mauromorales** [comment]
@cathyhongzhang indeed, k3s has a smaller footprint. One example would be its use of sqlite3 over etcd, which also helps for single node setups.

It's worth mentioning that while we focus mostly on the k3s provider (as we call them), we are open to more of them and there's already implementations for [kubeadm](https://github.com/kairos-io/provider-kubeadm) and [rke2](https://github.com/kairos-io/provider-rke2).

cc @mudler

**Comment by mudler** [comment]
> I think this project is a good addition to CNCF. 

Thanks! we would be happy to donate Kairos to the CNCF

> I have a question though. Could you clarify why it is a kubernetes distribution specific for edge? Does it slim down the Kubernetes in some way?

While Kairos can be extended and customize for various use-cases, it is tailored for Kubernetes as it comes tweaked torwards running Kubernetes workloads in an immutable environment, and it targets the edge as it comes pre-packaged for a support for various HW platforms, including for instance Raspberry, or Nvidia AGX Orin.

As also @mauromorales mentioned, Kairos abstracts away the Kubernetes distribution that can be used, and there are many supported alongside with k3s (kubeadm, rke2, microk8s, ...)

Hope it clarifies!

**Comment by jeefy** [comment]
Heya @mudler !

Welcome aboard! We're very excited to get you onboarded as a CNCF sandbox project! Here's the link to your onboarding checklist: https://github.com/cncf/toc/issues/1300

That issue is where you can communicate any questions or concerns you might have. Please don't hesitate to reach out!

**Comment by mudler** [comment]
> Heya @mudler !
> 
> Welcome aboard! We're very excited to get you onboarded as a CNCF sandbox project! Here's the link to your onboarding checklist: [cncf/toc#1300](https://github.com/cncf/toc/issues/1300)
> 
> That issue is where you can communicate any questions or concerns you might have. Please don't hesitate to reach out!

Thanks @jeefy ! 

I'll follow up from there for the next steps  - we are really thrilled to join the CNCF foundation!

**Comment by mrbobbytables** [comment]
With the onboarding issue open at: https://github.com/cncf/toc/issues/1300
I'm going to go ahead and close this out. 👍 

Thanks!
