### ISSUE TITLE
[Sandbox] IO Flow

### ISSUE THREAD

**Issue by mayur-yambal** [cncf/sandbox#55]
### Application contact emails

mayur.yambal@iauro.com, sudhir.raut@iauro.com, shashwat.tiwari@iauro.com

### Project Summary

IO Flow is a Cloud-Native, Microservices enabled workflow engine that facilitates creation, execution, monitoring & optimisation of complex business processes..  

### Project Description

IO Flow presents a remarkable opportunity for CNCF's prestigious sandbox program as it embodies cloud-native innovation and fulfils the demand for efficient workflow management solutions. This cutting-edge, microservices-enabled workflow engine is designed to significantly impact the cloud-native ecosystem by enhancing the creation, execution, monitoring, and optimisation of complex business processes. 

Built with a clear focus on openness and industry standards, IO Flow seamlessly integrates with existing CNCF projects through interoperability libraries. Its compatibility with industry standards like MACH (Microservices-based, API-first, Cloud-native, and Headless) ensures seamless communication between various cloud-native tools, fostering a cohesive environment where projects complement each other's functionalities. Moreover, IO Flow adheres to OpenAPI 3.0, promoting a standardised approach to API definition, while embracing BPMN and OCEL to highlight its commitment to industry recognised standards and open collaboration within the cloud-native ecosystem. 

IO Flow takes a novel approach to address the unfulfilled needs of workflow orchestration and management by offering a comprehensive feature set that aligns perfectly with CNCF values. With real-time process monitoring and detailed execution logs, it embodies CNCF's focus on observability and data-driven insights. The platform's modular and reusable workflows demonstrate commitment to extensibility and interoperability, supporting CNCF's goal of building a cohesive and collaborative cloud-native landscape. IO Flow's dynamic UI for user tasks enhances the user experience, aligning with CNCF's emphasis on improving user-centric design. The pre-built connector ecosystem further contributes to interoperability, making IO Flow a robust solution that empowers organisations to succeed in cloud-native environments. 

IO Flow's clear roadmap includes workflow mining capabilities, visual workflow mining, KPI dashboards, benchmarking, workflow variant detection, conformance analysis, and workflow graphs/models. By integrating these features with its workflow management system, IO Flow goes beyond mere monitoring, facilitating seamless end-to-end workflow management and optimising workflows effectively. With its dedication to innovation and alignment with CNCF values, IO Flow emerges as a standout candidate for CNCF's sandbox program, destined to make a meaningful contribution to the cloud-native community. 

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/iauroSystems  

### Project repo URL in scope of application

https://github.com/iauroSystems/io-flow-core 

### Website URL

https://www.iauro.com/io-flow  

### Roadmap

https://github.com/orgs/iauroSystems/projects/1

### Contributing Guide

https://github.com/iauroSystems/io-flow-core/blob/master/CONTRIBUTING.md  

### Code of Conduct (CoC)

https://github.com/iauroSystems/io-flow-core/blob/master/CODE_OF_CONDUCT.md 

### Contributing or Sponsoring Org

https://www.iauro.com/ 

### Maintainers file

https://github.com/orgs/iauroSystems/people

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We are eager to contribute IO Flow to the CNCF because of the exceptional value it offers to our project and the broader cloud-native ecosystem. Joining the CNCF provides us with access to a diverse and knowledgeable community, fostering collaboration, knowledge sharing, and technical advancements. The CNCF's emphasis on openness & interoperability aligns perfectly with our project's core principles, making it an ideal fit for seamless integration and collaboration. 

By being part of the CNCF, IO Flow gains exposure to industry leaders, experts, and potential contributors, enabling us to refine and strengthen our project through valuable feedback and insights. The CNCF's sandbox program offers a valuable platform for showcasing IO Flow's capabilities, driving adoption, and encouraging community engagement. 

The CNCF's sandbox program provides a launching pad for IO Flow, allowing us to demonstrate its unique features and foster meaningful connections within the cloud-native community. Overall, joining the CNCF will strengthen our project and enable us to make a valuable contribution to the cloud-native ecosystem. 

### Benefit to the Landscape

IO Flow brings significant benefits to the CNCF landscape, presenting a versatile workflow management solution with clear differentiators from existing projects like Argo Workflows. While Argo is specifically designed for Kubernetes, IO Flow extends beyond Kubernetes to cater to various cloud-native environments. Its adoption of BPMN for standardised workflow modelling sets it apart, enhancing compatibility and communication between cloud-native tools. With comprehensive features, real-time monitoring, dynamic UI, and scalability, IO Flow empowers organisations with actionable insights and improved user experiences. Its contribution enriches the ecosystem, optimising cloud-native workflows and empowering organisations in their cloud-native journey. 

Furthermore, IO Flow's comprehensive roadmap includes workflow mining capabilities such as visual workflow mining, KPI dashboards, benchmarking, workflow variant detection, conformance analysis, and workflow graphs/models. By seamlessly integrating these features with its workflow management system, IO Flow offers seamless end-to-end workflow management and optimisation. This unique differentiator positions IO Flow as a powerful and innovative solution to address workflow challenges within the CNCF landscape, complementing and advancing cloud-native practices and fostering collaboration within the community. 

### Similar projects

https://github.com/camunda
https://github.com/Netflix/conductor
https://github.com/kissflow

### Landscape

No

### Business Product or Service to Project separation

N/A

**Comment by joshgav** [comment]
Thanks for this submission @mayur-yambal! I see parallels with [Argo Workflows](https://argoproj.github.io/argo-workflows/) (as you mention) as well as [Serverless Workflow](https://serverlessworkflow.io/).

Since this project enables users to develop and deliver workflow-style processes and applications I think it fits TAG App Delivery like those other two projects.

Could you present IO Flow at an upcoming TAG App Delivery general meeting? Our next opening is likely Sept 16, here's our running agenda/notes doc: https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit

I'll shortly open a tracking issue in our TAG repo too.

cc @thschue

**Comment by mayur-yambal** [comment]
Hi Josh,

Thanks for the update.

Argo Workflows and serverless workflow look similar, but Argo workflows focuses more on Kubernetes flows. And serverless workflow is based on serverless functions.

IO Flow is microservices based process automation targeting any business process orchestration.

Happy to present IO Flow in TAG App Delivery general meeting. Looking forward to joining.


Thanks,
Mayur Yambal
Chief Platform Officer
+91 9960841912 |   LinkedIn<https://www.linkedin.com/in/mayuryambal/><https://www.linkedin.com/in/yogesh-iauro/>

[https://isignimages.s3.ap-south-1.amazonaws.com/Logo.png]
iauro systems Pvt. ltd.
[https://isignimages.s3.ap-south-1.amazonaws.com/Web.png] <https://www.iauro.com/>

www.iauro.com

[https://isignimages.s3.ap-south-1.amazonaws.com/mail.png]

***@***.***

[https://isignimages.s3.ap-south-1.amazonaws.com/fb.png]<https://www.facebook.com/iauro>   [https://isignimages.s3.ap-south-1.amazonaws.com/twitter.png] <https://twitter.com/iauro>    [https://isignimages.s3.ap-south-1.amazonaws.com/linkedIn.png] <https://www.linkedin.com/company/iauro-systems-pvt-ltd>    [https://isignimages.s3.ap-south-1.amazonaws.com/Insta.png] <https://www.instagram.com/iauro_systems/>

This e-mail is confidential. It may also be legally privileged. If you are not the addressee, you may not copy, forward, disclose or use any part of it. If you have received this message in error, please delete it and all copies from your system and notify the sender immediately by return e-mail. Internet communications cannot be guaranteed to be timely, secure, error or virus-free. The sender does not accept liability for any errors or omissions. The management of iauro systems Pvt. Ltd. do not accept any liability for mishandling of email account.


[cid:b5854bc7-2410-4a2f-93ea-c114ab81cb21]

________________________________

**Comment by joshgav** [comment]
Thank you @mayur-yambal for presenting to TAG App Delivery! Our writeup, the recording and the deck are all now at <https://github.com/cncf/tag-app-delivery/issues/447#issuecomment-1789301258>

The IOFlow project follows cloud-native principals and is seeking to enable some cloud-related use cases as well as general business process use cases.

**Comment by mauilion** [comment]
thank you for presenting this project for inclusion. The CNCF TOC has decided that this project should re apply in 6 to 12 months. Once the project has a bit more momentum and adoption.

**Comment by amye** [comment]
Closing, project can reapply for June review
