### ISSUE TITLE
[Sandbox] kube-burner

### ISSUE THREAD

**Issue by smalleni** [cncf/sandbox#57]
### Application contact emails

smalleni@redhat.com, rsevilla@redhat.com, vchalla@redhat.com

### Project Summary

Kube-burner is a Kubernetes performance and scale test orchestration framework that helps create, delete and patch resources at scale, collect metrics, measurements and alerts around cluster performance and index them for long term storage, retrieval and regression identification.

### Project Description

As Kubernetes has crossed the chasm to establish itself as the preferred foundation on which to deploy and scale cloud native applications, performance and scale of the platform are now more important than ever. Cluster administrators, application developers and end-users all have different ways of perceiving it, but they all unequivocally agree that performance and scale are perhaps the most important non-functional requirements alongside security for the Kubernetes platform.

kube-burner is a flexible and extensible tool written in golang that helps one easily design tests and evaluate the performance and scale of a Kubernetes platform through a simple to use CLI.  It can be used to establish a baseline for the performance of the Kubernetes platform, stress the control plane as well as the runtime, help derive SLOs and continually evaluate the platform against it, compare different Kubernetes distributions and across different form factors to help choose the right solution. It exemplifies performance-as-a-service by taking complexity out and establishing a low enough barrier for cluster administrators, application developers and end-users to put their performance engineering hats on.

kube-burner helps a user run tests to characterize performance of the Kubernetes solution, by creating, deleting and patching Kubernetes resources (pods, deployments, services, secrets, configmaps and more) at scale according to canned or user-defined scenarios. It also helps evaluate the behavior of the platform under load by scraping and indexing prometheus metrics and alerts along with custom measurements like podready latencies and pprofs for surfacing and zooming in on bottlenecks. 

![image](https://github.com/cncf/sandbox/assets/11049799/59b1f91d-9147-408c-92a5-9e713870ef8a)

### Org repo URL (provide if all repos under the org are in scope of the application)

N/A

### Project repo URL in scope of application

https://github.com/cloud-bulldozer/kube-burner

### Website URL

https://cloud-bulldozer.github.io/kube-burner

### Roadmap

https://github.com/cloud-bulldozer/kube-burner/blob/master/ROADMAP.md

### Roadmap context

Kube-burner has a robust roadmap to improve stability of the code and consistency of results while continuing to advance features around performance and scale testing use cases. The focus is on adding additional checks to ensure that the cluster is healthy before running a benchmark, automated performance regression flagging, standalone metrics and measurements collection on the cluster without running a benchmark and more canned workloads that push Kubernetes' scale in different dimensions. There are several use-case specific performance and scale test suites that depend on kube-burner as the orchestrator, so our roadmap tends to encompass features needed to enable those efforts as well. The community is free to open Github issues and get them prioritized to be incorporated into the roadmap.

### Contributing Guide

https://cloud-bulldozer.github.io/kube-burner/v1.7.6/contributing/

### Code of Conduct (CoC)

https://github.com/cloud-bulldozer/kube-burner/blob/master/CODE_OF_CONDUCT.md

### Adopters

Bosch, Cisco, IBM, Upbound, ANZ Bank, Plaid Inc., EnterpriseDB

### Contributing or Sponsoring Org

Red Hat Inc.

### Maintainers file

https://github.com/cloud-bulldozer/kube-burner/blob/master/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We believe that becoming a part of the CNCF opens up a world of opportunities for kube-burner, as the foundation provides the stage to accelerate contributions, collaboration and adoption. We know that end users are looking for simple, reliable ways to understand the performance and scale of their Kubernetes platforms so they can design better solutions, and putting kube-burner under the CNCF umbrella will give them a vendor neutral tool to do exactly that.

### Benefit to the Landscape

Performance and scale are two of the most important non-functional requirements alongside security and there is currently a void in the CNCF landscape when it comes to easy to use, reliable tools that work across any Kuberentes distribution and form factor. Hence, the community at large has an unmet need in this area. Kube-burner will add another dimension to the Observability and Analysis column in the CNCF landscape and give cluster administrators, application developers and end users a mechanism to not only benchmark the Kubernetes control plane, node agents, container runtime and CNIs but help approach their choices through a performance lens. For example, it is indeed empowering to be able to benchmark different cloud native network choices for the Kubernetes platform and choose what works best for the given use case.  We believe that kube-burner is uniquely positioned to benefit the cloud native stack as it allows stress testing even custom controllers and generating enough load on the Kubernetes platform to create a 360 degree view of the cluster’s performance under different workloads and conditions. Most importantly, it will help catalyze discussions around performance and evangelize a scalability first approach to designing a cloud native stack with Kubernetes at the core.

### Cloud Native 'Fit'

Cloud native technologies are all about delivering value at massive scale across the public cloud, data center and the edge.  kube-burner thrusts performance and scale tooling to the forefront of the CNCF Cloud Native Landscape, providing cloud administrators, application developers and end-users with the technology to test the reliability, stability, performance and scale of different layers of the cloud native stack - provisioning, runtime, orchestration and management, observability and analysis.

### Cloud Native 'Integration'

Kube-burner is capable of testing performance and scale of Kubernetes which is at the core of the cloud native stack. It uses client-go to create, patch and delete kubernetes resources at scale with massive parallelism and scrapes prometheus for metrics and alerts generated during the tests. It is capable of operating against several distributions of Kubernetes as well as vanilla Kubernetes.

### Cloud Native Overlap

There are currently no projects that focus on the performance and scale dimensions of Kubernetes, so kube-burner helps meet an unmet need in this area.

### Similar projects

clusterloaderv2 has a somewhat similar motivation although it is not a CNCF project. However, kube-burner provides differentiated functionality and experiences as follows: 
1. Flexible and easy to use configuration. kube-burner configuration is much more intuitive and helps design scenarios that push Kubernetes scale in different dimensions with minimal effort. The configuration is a blend of procedural and declarative approaches, bringing the best of both worlds together
2. Ability to capture and index metrics from Prometheus that represent the cluster's performance under load aka scale and index them to Elasticsearch/OpenSearch by consuming a custom metrics file.
3. Functionality to capture metadata about the cluster configuration for performing run-to-run comparisons
4. Alerting based on Prometheus expressions
5. Works across a range of Kubernetes distributions
6. Platform and cloud agnostic
7. Well documented

kubestone which is a benchmarking operator is no longer in active development and kubebench primarily focuses on database application performance as opposed to kube-burner which is focused on the platform.

### Landscape

No

### Business Product or Service to Project separation

kube-burner is a 100% open-source tool built for the community. There are currently no productization plans. 

### Additional information

End-Users are looking for reliable, easy to use tools to benchmark their platform to measure its performance against SLOs and also make informed choices on several fronts including Kubernetes distributions and runtimes. kube-burner puts the power of performance engineering into the hands of key stakeholders like architects, cluster administrators, application developers and end-users and thrusts performance into the forefront of cloud native design conversations.

**Comment by nikhita** [comment]
@smalleni it would be great if you could present kube-burner at a TAG Obeservability meeting.

@alolita @halcyondude

**Comment by smalleni** [comment]
@nikhita Happy to! Looks like the next instance of the TAG Observability meeting is on September 5th (https://github.com/cncf/tag-observability)? Would appreciate it if we can get on the schedule then.

**Comment by alolita** [comment]
Hi @nikhita thanks for referring @smalleni to present on kube-burner at a TAG O11y meeting. 

Sai - The next meeting on Sep 5 should work. Will reach out to you on Slack to coordinate details :-)

**Comment by smalleni** [comment]
> Hi @nikhita thanks for referring @smalleni to present on kube-burner at a TAG O11y meeting.
> 
> Sai - The next meeting on Sep 5 should work. Will reach out to you on Slack to coordinate details :-)

Awesome, I will be there with a couple of teammates to present. Looking forward to it!

**Comment by alolita** [comment]
@smalleni we have another presentation scheduled for logging operator (https://github.com/cncf/sandbox/issues/42) also on Sep 5. Can you do a 20-25 minute presentation and then use a few minutes for live Q&A since we now have 2 project presentations for Sep 5 :-)  to support projects lining up for sandbox review on the 12th.

**Comment by smalleni** [comment]
> @smalleni we have another presentation scheduled for logging operator (#42) also on Sep 5. Can you do a 20-25 minute presentation and then use a few minutes for live Q&A since we now have 2 project presentations for Sep 5 :-) to support projects lining up for sandbox review on the 12th.

Perfect, that should work for us. Thanks so much!

**Comment by smalleni** [comment]
@alolita Would it be possible for us to take the first available time slot in that meeting?

**Comment by smalleni** [comment]
@alolita Thanks for the opportunity to present to TAG Observability. While kube-burner has certain aspects of observability to it, it is primarily a performance and scale test orchestration framework and fulfills a key role to help find the limits of Kubernetes scale . @nikhita Based on alignment, do you feel the need for us to present to any other TAG as well?

**Comment by joshgav** [comment]
Thank you @smalleni and team for presenting kube-burner to TAG App Delivery today. Our notes, a recording of the presentation and demo, and a copy of the presentation itself are all available at <https://github.com/cncf/tag-app-delivery/issues/466#issuecomment-1813203599>.

The TAG concluded that the project is a technical fit for CNCF and fits as part of TAG App Delivery.
