### ISSUE TITLE
[Sandbox] Cartography

### ISSUE THREAD

**Issue by achantavy** [cncf/sandbox#58]
### Application contact emails

achantavy@lyft.com, ramonp@lyft.com

### Project Summary

Cartography builds a self-maintaining map of your infrastructure.

### Project Description

Cartography consolidates infrastructure assets across multiple vendors and the relationships between them in a knowledge graph powered by an openCypher-compatible database. 

Cartography aims to enable a broad set of exploration and automation scenarios. It is particularly good at exposing otherwise hidden dependency relationships between your service's assets so that you may validate assumptions about security risks.

Service owners can generate asset reports, Red Teamers can discover attack paths, and Blue Teamers can identify areas for security improvement. All can benefit from using the graph for manual exploration through a web frontend interface, or in an automated fashion by calling the APIs.

To provide specific examples, Cartography can be used to [better understand AWS IAM permissions](https://eng.lyft.com/iam-whatever-you-say-iam-febce59d1e3b) and [perform automated vulnerability management on container images](https://eng.lyft.com/vulnerability-management-at-lyft-enforcing-the-cascade-part-1-234d1561b994).

### Org repo URL (provide if all repos under the org are in scope of the application)

N/A

### Project repo URL in scope of application

https://github.com/lyft/cartography/

### Additional repos in scope of the application

N/A

### Website URL

https://github.com/lyft/cartography/

### Roadmap

https://github.com/orgs/lyft/projects/26/views/1

### Roadmap context

We built a [new data model](https://docs.google.com/document/d/1HI_EUgXd55affTNznEj80aY3vNVWlnWSLjwyxJ8nDpQ/edit#heading=h.9cnwzh9b0ooe) to make plugin development less error prone and improve write performance. We are currently focused on migrating older plugins to use it.

### Contributing Guide

https://github.com/lyft/cartography/#contributing

### Code of Conduct (CoC)

https://github.com/lyft/cartography/#code-of-conduct

### Adopters

https://github.com/lyft/cartography/#who-uses-cartography

### Contributing or Sponsoring Org

https://github.com/lyft

### Maintainers file

https://github.com/lyft/cartography/blob/master/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Cartography was open sourced by Lyft in March 2019 and we are proud of how the community has grown since then. We believe Cartography solves asset management and analysis problems in a useful way, and would like to continue to grow the project. However, this is not possible over the long run if its steward is just one company. By moving the project to a neutral open source foundation such as the CNCF, we hope that we will attract more users and contributors so that we can better sustain a steady stream of maintainers.

### Benefit to the Landscape

We believe that having a Cartography-generated map over your infrastructure is a game changer for any security or devops shop. Cartography is not the only cloud inventory tool out there, but it differentiates itself in that it 
- Has a healthy ecosystem of documented use-cases. Here is a sample of public contributions _not_ created by Lyft employees: [1](https://blog.marcolancini.it/2020/blog-mapping-moving-clouds-with-cartography/), [2](https://blog.marcolancini.it/2020/blog-mapping-moving-clouds-with-cartography/), [3](https://gigi.nullneuron.net/gigilabs/getting-started-with-cartography-for-aws/), [4](https://gigi.nullneuron.net/gigilabs/migrating-cartography-to-memgraph/), [5](https://github.com/paypay/seizu), [6](https://gigi.nullneuron.net/gigilabs/getting-started-with-cartography-for-okta/)
- Has a robust plugin architecture that makes it easy to extend
- Is easy to adopt in that it is shipped as a simple Python script and is flexible about how to deploy it.

### Cloud Native 'Fit'

**Landscape**: Provisioning - Security & Compliance.
Cartography is a foundational security tool that makes it easier to manage your infrastructure.

Its graph approach makes it easy to answer questions including but not limited to
- Who has read access to my sensitive datastores and how
- What is the effective blast radius of a compromised asset in my environment
- Which of my assets are open to the internet
- What are my cross-vendor trust relationships
- From which parent container image was this vulnerability introduced to my environment and who should I assign the action item to

As such, it fits in “Provisioning” and “Security & Compliance”.

**TAGs**: TAG Security

### Cloud Native 'Integration'

Cartography uses the Neo4j graph database to build knowledge graphs of infra across multiple resource types.

### Cloud Native Overlap

Trivy: As described in this [blog](https://eng.lyft.com/vulnerability-management-at-lyft-enforcing-the-cascade-part-1-234d1561b994), Cartography knowledge graphs can be used to orchestrate Trivy image scans so that we can identify whether a vulnerability was introduced by the service itself or by one of its parent images several layers up – a time-consuming task solved quickly using a graph approach.

### Similar projects

Similar CNCF projects

- ThreatMapper provides a graph view over network flows to prioritize threat scan results. Cartography is more general purpose as it can be applied to multiple infra/security scenarios, and is more low level in the sense that it only stores data to a graph database and does not include a user interface out of the box (other than the default Neo4j web interface).

Non-CNCF similar projects

- CloudQuery pulls data from multiple sources and loads it to multiple destinations. Cartography focuses on knowledge graphs.
- BloodHound creates knowledge graphs for identifying attack paths in Microsoft Windows domain environments. Cartography focuses on cloud assets and relating resources from one provider to another.

### Landscape

No

### Business Product or Service to Project separation

N/A

### Project presentations

Yes.

- Meeting notes: [2020-03-11](https://docs.google.com/document/d/1ppM5Q-NH0qa5s1s0mCMEgRbEaBL9celwHc2s-JxT6GU/edit#heading=h.6cgk4vs4mjh5)
- https://github.com/cncf/sig-security/issues/347
- [Slides](https://docs.google.com/presentation/d/1pLbQbORYtF_WHl24GHY4LrQKHd7Rz9B56Tu0YICdeek/edit#slide=id.g6599e03b20_0_0)

### Project champions

N/A

### Additional information

Thank you for your consideration!

**Comment by achantavy** [comment]
Hi @jberkus, thanks for your read.

While it doesn't have a specific dependency on Kubernetes, cartography is suitable for the CNCF in particular because was built to solve problems that are uniquely complicated in cloud native environments such as reasoning about permissions, networking, and container image lineage.

cartography also complements existing cloud-native tools and methodologies even though it doesn't directly integrate with them. Here are a few examples:

- **Cross-vendor cross-cloud auditing**: cloud-native environments often involve a mix of on-prem and cloud resources across multiple vendors that change over time, and cartography is useful for maintaining an inventory and providing a centralized view of the entire ecosystem. This is useful for reporting and regulatory requirements, and is described much more eloquently in Marco's blog [Mapping Moving Clouds](https://blog.marcolancini.it/2020/blog-mapping-moving-clouds-with-cartography/).

- **Security incident response**: if a detection agent like Falco detects that a malicious shell has been launched in a container, it can send security alerts to an observability platform, and an incident handler can then use cartography to put the alert into context:
    - What service does that container belong to?
    - Assuming this service is compromised, what other assets is the malicious actor able to access or pivot to? What is the blast radius?
    - Who is on call for the service and who else do I need to notify?

- **Microservice comms**: cartography is not directly involved in the network comms that happen in a service mesh, but it complements them by visualizing the topology and dependencies between services, such as how it can show K8s nodes grouped by cluster and how network ingress and egress is controlled, or how it can maintain an inventory of all known URI endpoints of an application and map them to owners.

**Comment by achantavy** [comment]
Hi @rochaporto, back in 2020 we [asked](https://cloud-native.slack.com/archives/CDJ7MLT8S/p1583949276062300) about the steps needed to join CNCF and decided that it wasn't the right time because the pandemic had just started and we had other priorities.

In the 4 years since then, I think we've hit a lot of the CNCF project criteria - e.g. adoption by multiple companies, public roadmaps, decisions fully made in the open, various specific information available in docs, etc -  as cartography needed to grow that way. The project now has a more defined identity in that knows what it is - a uniquely useful analysis capability - and what it isn't - e.g. it's not a near real-time detection tool.

In a nutshell, we're pursuing CNCF now because the project has reached the right maturity level to think about longer term strategic direction and ownership beyond just one company.

**Comment by achantavy** [comment]
Hi @rochaporto , thanks for your reply and for you and the team's time reviewing!

> The CNCF staff will look at the license implication of the neo4j dependency (cc @jeefy @amye) but once that's sorted it out we can go for a vote without having to re-discuss during a sandbox review session.

Appreciate it, please write back when the license questions are resolved. 

> In the meantime we also recommend the project gives an update to TAG-Security

I will reach out to TAG-Security to give an updated presentation.

> given the maturity of the project a move to incubation might be something to consider soon. The discussion with the TAG should help understanding if this would be a good option.

I'm looking forward to learning more from the TAG. One logistics question: how would this work given that we are not in the sandbox yet -- assuming the license issues end up ok, would it take longer for us to be admitted to sandbox, or admitted directly into incubation?

Thanks again!

**Comment by TheFoxAtWork** [comment]
@achantavy Sandbox applications are fairly lightweight as compared to direct [application to Incubation](https://github.com/cncf/toc/tree/main/process#applying-to-become-an-incubating-or-graduating-project). While most projects apply to sandbox and then apply to incubation when they are ready, we occasionally have projects that are well advanced to apply directly to incubation.

@jeefy @mrbobbytables Were the license implications here sorted?

**Comment by achantavy** [comment]
Hi @jeefy, @mrbobbytables, @TheFoxAtWork - are there any updates on the license situation?

We'd like to continue this sandbox application and pursue incubation later.

**Comment by TheFoxAtWork** [comment]
Thank you for the ping.  CNCF is working to get a status on this.

**Comment by jeefy** [comment]
@achantavy Heya! We have a "few" follow-up questions if you wouldn't mind. :) 

- Is Cartography using neo4j’s Community Edition, licensed under GPL-3.0, https://github.com/neo4j/neo4j?
- Is Cartography distributing neo4j, or does each downstream user have to obtain neo4j themselves?
    - If Cartography is distributing neo4j, are you also distributing neo4j’s source code and its GPL-3.0 license text + copyright notices?
- Is Cartography modifying neo4j in any way?
- Is neo4j a mandatory dependency for Cartography, or is it one of multiple options available to the end user?
- Please briefly describe the functionality / purpose that neo4j serves for Cartography.
- How does Cartography interact with neo4j, and how are the two combined or linked together?
    - For example, does Cartography only interact with neo4j through an official Apache-2.0 driver provided by neo4j, such as https://github.com/neo4j/neo4j-python-driver?
    - Is neo4j included together in an executable with Cartography? Or does neo4j run as a separate executable / process?
    - Do the two operate together in a shared memory space?
    - (See https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation for more specifics on what we’re trying to get at with these questions.)

Thanks!!

**Comment by achantavy** [comment]
@jeefy thanks so much for your reply! Here are the answers:

> Is Cartography using neo4j’s Community Edition, licensed under GPL-3.0, https://github.com/neo4j/neo4j?

Yes, Cartography uses neo4j community edition.


> Is Cartography distributing neo4j, or does each downstream user have to obtain neo4j themselves?

No, we do not distribute neo4j, each downstream user obtains neo4j themselves.


> If Cartography is distributing neo4j, are you also distributing neo4j’s source code and its GPL-3.0 license text + copyright notices?

N/A


> Is Cartography modifying neo4j in any way?

No, Cartography does not modify Neo4j.


> Is neo4j a mandatory dependency for Cartography, or is it one of multiple options available to the end user?

Yes, neo4j is a mandatory dependency.


> Please briefly describe the functionality / purpose that neo4j serves for Cartography.

It's the main datastore: we need neo4j's graph functionality. In the future we could add support for other graph DBs but at this time neo4j is our principal datastore.


> How does Cartography interact with neo4j, and how are the two combined or linked together? For example, does Cartography only interact with neo4j through an official Apache-2.0 driver provided by neo4j, such as 
https://github.com/neo4j/neo4j-python-driver?

Yes, this is correct: Cartography only interacts with neo4j through the official Apache-2.0 driver provided by neo4j.


> Is neo4j included together in an executable with Cartography? Or does neo4j run as a separate executable / process?

No, neo4j is not included in an executable with Cartography. Cartography is a python script that talks to neo4j via the neo4j-driver.


> Do the two operate together in a shared memory space? (See https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation for more specifics on what we’re trying to get at with these questions.)

No, the two do not operate together in a shared memory space.

**Comment by achantavy** [comment]
Hi @jeefy and everyone, are there any updates from the meeting on August 13? Please let me know if you need more information.

**Comment by TheFoxAtWork** [comment]
@achantavy thank you for your patience.  I've asked Staff to check in on any additional blockers that prevent this from moving to a vote.

**Comment by mrbobbytables** [comment]
(proxy for @jeefy) it's going to be a longer discussion around neo4j as a dependency, but at the moment it should not serve as a blocker.

We are good to move this to a vote. 👍 

/vote

**Comment by achantavy** [comment]
Thank you everyone for your review and votes! Really excited for what's next.

**Comment by Cmierly** [comment]
Welcome and congrats on getting accepted as a CNCF Sandbox project!

You can get started on your on-boarding checklist here: https://github.com/cncf/toc/issues/1410

and if you have any questions, please don't hesitate to reach out!

**Comment by mrbobbytables** [comment]
With https://github.com/cncf/toc/issues/1410 created, we can go ahead and close this out :)

Congrats again!
