### ISSUE TITLE
[Sandbox] Atlantis

### ISSUE THREAD

**Issue by jamengual** [cncf/sandbox#60]
### Application contact emails

jose.amengual@gmail.com
dylandcpage@gmail.com
[rui@chenrui.dev](mailto:rui@chenrui.dev)

### Project Summary

Terraform Pull Request Automation

### Project Description

Atlantis is PR automation application that allows users to create PRs against a repository to run terraform via command comments like `atlantis plan/apply/import/unlock`.
It allows users to interact with terraform commands within the PR and get the output of those commands in the form of PR comments.
Users can define project structures, generate policies, autogenerate projects, require review requirements etc.
Atlantis supports multiples VCSs Github, Gitlab, BitBucket, Azure Pipelines

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/runatlantis

### Project repo URL in scope of application

https://github.com/runatlantis/atlantis

### Website URL

https://www.runatlantis.io/

### Roadmap

https://github.com/runatlantis/atlantis/milestones

### Contributing Guide

https://github.com/runatlantis/atlantis/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/runatlantis/atlantis/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/runatlantis/atlantis/issues/2626

### Maintainers file

https://github.com/runatlantis/atlantis/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Atlantis has been part of the IaC community for many many years and lately, after a few years dormant it has been reviving thanks to the work of the maintainers and the community, it is more than ever vitally crucial for many companies and individuals these days were there is more and more IaC adoption in the industry. But without a good supporting structure, Atlantis could potentially one day go dormant forever and it will fracture the long-lasting community that it has built.
That is why we believe by donating the project to the CNCF we could get the much-needed supporting structure to the project and drive a richer contributor community.

### Benefit to the Landscape

As I said before, the project has been a long-time key player in the community, and its role in IaC and cloud infrastructure is vital, we feel that CNCF is a natural fit for the project.
Many CNCF projects actually run Atlantis to create their own infrastructure to actually deploy their own code to the cloud resources or to deploy other CNCF projects in their infrastructure.
It is a key piece withing the cloud native infrastructure.

### Cloud Native 'Fit'

The Atlantis project fits within the Automation/Configuration section on the CNCF alongside terraform, ArgoCD, and others.
It uses the GitOps workflow to run terraform automation to then deploy resources to support different other types of applications like, Kubernetes, Argo and many others.
It sits in a key part of the deployment workflow of many cloud native application.

Most Atlantis users use Atlantis in Kubernetes, bootstrapping other Kubernetes clusters using Atlantis, and deploying their apps in Kubernetes using Atlantis workflows.

### Cloud Native 'Integration'

Atlantis runs primarily Terraform project in a GitOps workflow.
Any Terrafrom project can be run through atlantis and be enhanced by the many features that it offers.
Atlantis complements terraform in particular by moving the IaC to the left, closer to the developer so that the interaction with terraform happens in familiar tools to the developer.

### Cloud Native Overlap

none I believe

### Similar projects

ArgoCD

### Landscape

I do not think we are listed

### Business Product or Service to Project separation

N/A

### Project presentations

N/A

### Project champions

N/A

### Additional information

The project owner has authorized us to submit the project and has made us the official maintainers.

https://github.com/runatlantis/atlantis/issues/3686

**Comment by pszelestey** [comment]
+1

**Comment by maateen** [comment]
+1

**Comment by attila-nagy-statsperform** [comment]
+1

**Comment by jamengual** [comment]
@amye I see other projects that committed the application later than us have feedback about their projects and I'm wondering if there is any feedback for our project? do we wait for the review on Dec 12 to hear back? Thanks.

**Comment by joshgav** [comment]
Hi @jamengual would you be able to present Atlantis to TAG App Delivery at one of our general meetings? I'll create an issue to track with what you would present to us, and we'll share the presentation and recommendations back with TOC here. We meet the first and third Wednesdays of every month and though there are other projects presenting on 11/1 and 11/15 we could probably get Atlantis in one of those too. Alternatively 12/6 is still open. Thanks!

**Comment by jamengual** [comment]
I can do any of those dates, and we can prepare a presentation for that.

**Comment by mustafa89** [comment]
+1

**Comment by Michalosu** [comment]
+1

**Comment by axcosta** [comment]
+1

**Comment by benoittoulme** [comment]
+1

**Comment by joshgav** [comment]
@jamengual could we put you down for Wednesday December 6? We have another project presenting on 11/15 now, and I think folks will want to discuss how Kubecon went in the 11/15 meeting too. I'd like Atlantis to have a good 20-25 minutes, which would work best on 12/6. Will that work for you and the team? Thanks!

**Comment by jamengual** [comment]
Yes, I can do 12/6.

**Comment by johndotpub** [comment]
+1

**Comment by ugrkm** [comment]
+1

**Comment by lemmah-zen** [comment]
+1

**Comment by hungran** [comment]
+1

**Comment by jadametz** [comment]
+1

**Comment by jberkus** [comment]
Given the nature of this project, should it be in the CNCF, or part of the OpenTofu project?

**Comment by joshgav** [comment]
Atlantis presented to TAG App Delivery on 12/6, recording and notes are available here: <https://github.com/cncf/tag-app-delivery/issues/474#issuecomment-1861676966>

We asked if the project would fit better in OpenTofu; the group expressed concern that they wish to support both TF and OpenTofu, but we answered that this should be feasible within OpenTofu as well. A question for us is if OpenTofu intends to accept other projects and implementations too. (Note: a similar question keeps coming up for LF's OpenAPI foundation too.)

If not part of OpenTofu then the TAG believes that Atlantis would fit in CNCF's sandbox.

**Comment by scheuk** [comment]
+1

**Comment by swade1987** [comment]
+1

**Comment by PopeyeTheSai10r** [comment]
+1

**Comment by logicminds** [comment]
+1

**Comment by GenPage** [comment]
> Atlantis presented to TAG App Delivery on 12/6, recording and notes are available here: [cncf/tag-app-delivery#474 (comment)](https://github.com/cncf/tag-app-delivery/issues/474#issuecomment-1861676966)
> 
> We asked if the project would fit better in OpenTofu; the group expressed concern that they wish to support both TF and OpenTofu, but we answered that this should be feasible within OpenTofu as well. A question for us is if OpenTofu intends to accept other projects and implementations too. (Note: a similar question keeps coming up for LF's OpenAPI foundation too.)
> 
> If not part of OpenTofu then the TAG believes that Atlantis would fit in CNCF's sandbox.

Since the submission of OpenTofu to the CNCF alongside the TAG App Delivery classification. I think it would make sense to keep Atlantis on track for CNCF submission.

https://github.com/cncf/sandbox/issues/81

**Comment by banthaherder** [comment]
+1

**Comment by tluzon-digibank** [comment]
+1

**Comment by rochaporto** [comment]
The TOC reviewed this sandbox application on January 23rd.

The TOC recommends the project engages with OpenTofu to understand if it would be a good fit as a subproject. This should clarify the open question also raised by TAG-AppDelivery (https://github.com/cncf/sandbox/issues/60#issuecomment-1861686056) regarding support for both OpenTofu and TF.

**Comment by GenPage** [comment]
@rochaporto The open question seems to be whether OpenTofu will accept subprojects or implementations.

> A question for us is if OpenTofu intends to accept other projects and implementations too. 

It would not benefit the project or be a good fit to be a subproject of OpenTofu. This aligns with our goal of being vendor-agnostic as an IaC orchestration tool beyond Terraform and OpenTofu implementations. It is my opinion that the open question is further answered by OpenTofu's application to the CNCF's sandbox. #81 

> If not part of OpenTofu then the TAG believes that Atlantis would fit in CNCF's sandbox.

**Comment by GenPage** [comment]
I have contacted the OpenTofu team again and requested their input directly on this issue to clarify their position.

**Comment by cube2222** [comment]
Hey, Kuba here, Technical Lead of the OpenTofu Project.

We've met with Dylan and discussed this, and both sides fully agree that keeping the projects separate is the best path forward for both projects.

First, as Dylan mentioned, Atlantis wants to serve many tools - including both Terraform and OpenTofu. We feel that this will work better with separate steering teams.

Second, at the OpenTofu project we're focusing on the core CLI. We're intentionally not building a "blessed" orchestration layer, in order to facilitate competition in the OpenTofu ecosystem - both open-source and commercial.

On that note, OpenTofu and Atlantis will definitely collaborate as projects, as exemplified by OpenTofu support being added to Atlantis, and the Atlantis maintainers being invited to speak at OpenTofu Day.

**Comment by izo-kshanahan** [comment]
+1

**Comment by shyamjos** [comment]
+1

**Comment by rochaporto** [comment]
Thanks @GenPage @cube2222 for the additional info.

**Comment by aravindhan-p-kf** [comment]
+1

**Comment by kevbo** [comment]
+1

**Comment by jenndaltonlg** [comment]
+1

**Comment by carovel-lg** [comment]
+1

**Comment by brunolima1989** [comment]
+1

**Comment by blo-grindr** [comment]
+1

**Comment by jberkus** [comment]
This project is a weird candidate for CNCF, because it is not inherently cloud-native.  It can be used in a cloud-native way, but it can also be used in the complete absence of Kubernetes, containers, or microservices.

This proposal hinges on the question of: does CNCF want to increase its scope to cover configuration management and deployment?  If the CDF still existed, we might suggest it as an alternate foundation, but that's not an option anymore.

**Comment by jamengual** [comment]
This project is very comparable to Argo CD, which has components that attach to VCSs and then go and run a workflow that produces some results; the only difference here is that it is not only a K8s service, but it can run in K8s, and we produce helm charts and container images.

I will say 95% of our use base uses this on cloud-native settings.

**Comment by Santhin** [comment]
+1

**Comment by preetsindhal** [comment]
+1

**Comment by zbialik** [comment]
+1

**Comment by dgo-ableton** [comment]
+1

**Comment by Brightside56** [comment]
> This project is a weird candidate for CNCF, because it is not inherently cloud-native. It can be used in a cloud-native way, but it can also be used in the complete absence of Kubernetes, containers, or microservices.
> 
> This proposal hinges on the question of: does CNCF want to increase its scope to cover configuration management and deployment? If the CDF still existed, we might suggest it as an alternate foundation, but that's not an option anymore.

Then half of CNCF projects are weird candidates for CNCF, including graduated projects such as Prometheus, Fluentd or even Cilium because those can be used without containers, Kubernetes and microservices

**Comment by JesusRo** [comment]
+1

**Comment by GenPage** [comment]
This will be long-winded, but I'm posting here due to the issue's high visibility.

> This project is a weird candidate for CNCF, because it is not inherently cloud-native. It can be used in a cloud-native way, but it can also be used in the complete absence of Kubernetes, containers, or microservices.
> 
> This proposal hinges on the question of: does CNCF want to increase its scope to cover configuration management and deployment? If the CDF still existed, we might suggest it as an alternate foundation, but that's not an option anymore.

Josh does have a point on Atlantis not entirely fitting the CNCF as it currently stands. I've been attending multiple talks and meetings at KubeCon EU to try and figure out the answer to this and to see how we can be part of the solution and not the problem. Atlantis isn't the only project residing in this "grey" area, and there's a need to figure out where projects of this scope fit into the ecosystem. 

There are also contributing factors from the CNCF side that exacerbate this. They do not have enough contributors participating in the TAGs (Technical Advisory Groups), which results in TAGs being overloaded with expanding scope. I highly encourage everyone to please join a TAG in your area of interest and contribute. You can find a list of TAGs here: https://github.com/cncf/toc/tree/main/tags

After the App-Delivery community talk at KubeCon and discussions with the TAG chairs, I'm happy to announce that I have volunteered to help coordinate and evaluate the building of a new working group around "Infrastructure Provisioning" within the App-Delivery TAG (https://github.com/cncf/tag-app-delivery/issues/589). To start, I will reach out to coordinate with similar projects, such as OpenTofu and Crossplane. 

If you wish to support/provide feedback, please consider joining the bi-monthly TAG meetings and Slack, which can be found here: https://tag-app-delivery.cncf.io/. Otherwise, a simple +1 is a great way to show your support and that we're thinking in the right direction. Thank you

**Comment by zanetworker** [comment]
I've been discussing a related topic with @angelk, and to @GenPage's point, Atlantis isn't the only project facing issues. Other initiatives like "hosted control planes" have also been caught in the grey area. While we could opt for runtime, I haven't found a suitable tag/wg for topics like infrastructure, multi-cluster management, control-planes, and lifecycle. 

@GenPage I am happy to collaborate (others in the hcp space are willing as well) to determine the right place for those efforts. I believe it would make sense to create a new WG that covers infra, multi-cluster management, control planes, and lifecycle projects, which would include cross-plane and open tofu. We could work on the naming to make sure the scope covers those efforts as well.

**Comment by iv0rish** [comment]
+1

**Comment by mbarr-hrp** [comment]
+1, and looking at the App Delivery TAG, so.. :)

**Comment by matthewbarr** [comment]
+1  , and you now having me look at the App Delivery TAG.

**Comment by manumbs** [comment]
+1

**Comment by rammanokar-plateron** [comment]
+1

**Comment by jonjpbm** [comment]
+1

**Comment by ShankyJS** [comment]
+1

**Comment by vitaly-sinev** [comment]
+1

**Comment by fjudith** [comment]
+1

**Comment by jberkus** [comment]
> Then half of CNCF projects are weird candidates for CNCF, including graduated projects such as Prometheus, Fluentd or even Cilium because those can be used without containers, Kubernetes and microservices

They *can be* but materially they *are not*.  It's unquestionable that the primary, 95% use case of Prometheus is collecting metrics for Kubernetes-based stacks.  Most Cillium users are on top of a Kubernetes distribution.  Etc.  If you're making the case that Atlantis is used primarily for building cloud native stacks, rather than for other configuration management tasks, then that's a good case to make for this application.  Are you?

**Comment by kdevray** [comment]
+1

**Comment by jamengual** [comment]
> > Then half of CNCF projects are weird candidates for CNCF, including graduated projects such as Prometheus, Fluentd or even Cilium because those can be used without containers, Kubernetes and microservices
> 
> They _can be_ but materially they _are not_. It's unquestionable that the primary, 95% use case of Prometheus is collecting metrics for Kubernetes-based stacks. Most Cillium users are on top of a Kubernetes distribution. Etc. If you're making the case that Atlantis is used primarily for building cloud native stacks, rather than for other configuration management tasks, then that's a good case to make for this application. Are you?

Most Atlantis users use Atlantis in Kubernetes, bootstrapping other Kubernetes clusters using Atlantis, and deploying their apps in Kubernetes using Atlantis workflows.

**Comment by Brightside56** [comment]
> > Then half of CNCF projects are weird candidates for CNCF, including graduated projects such as Prometheus, Fluentd or even Cilium because those can be used without containers, Kubernetes and microservices
> 
> They _can be_ but materially they _are not_. It's unquestionable that the primary, 95% use case of Prometheus is collecting metrics for Kubernetes-based stacks. Most Cillium users are on top of a Kubernetes distribution. Etc. If you're making the case that Atlantis is used primarily for building cloud native stacks, rather than for other configuration management tasks, then that's a good case to make for this application. Are you?

I think the vast majority of use cases for Atlantis is to be collaborative tool for a cloud infrastructure orchestration, but of course it can be used for something else

**Comment by raghavtan** [comment]
+1

**Comment by cwstrommer** [comment]
+1

**Comment by dibenlloch** [comment]
+1

**Comment by jberkus** [comment]
> Most Atlantis users use Atlantis in Kubernetes, bootstrapping other Kubernetes clusters using Atlantis, and deploying their apps in Kubernetes using Atlantis workflows.

Great!  Please add that to your original application text, in case members of the TOC aren't reading the whole comment thread.  It can go in either Cloud Native Integration or Cloud Native Fit.

**Comment by jberkus** [comment]
TAG-CS Comment:

Atlantis currently has:

- a very solid contributing guide
- simple, maintainer council governance with very strict company representation limits
- 4 maintainers, all from different companies

They do not have other project internal documentation ... yet.

**Comment by mrbobbytables** [comment]
Follow-up from today's sandbox review, Atlantis will be moved to a vote.
Just for an FYI though - you may be requested to change the name pending trademark review.
/vote

**Comment by jmateusousa** [comment]
+1

**Comment by chenrui333** [comment]
This is exciting!! 💯 Thanks everyone for helping us move forward. 😄

**Comment by jamengual** [comment]
I eco @chenrui333, thanks again for the support and please keep guiding us through the process.

This is the start of an exciting long journey with the project.

**Comment by AtharvaBondre** [comment]
Big supporter of Atlantis, have been using the product, and want it to go forward and big!

**Comment by Cmierly** [comment]
Hello and congrats on being accepted as a CNCF Sandbox project!

Here is the link to your onboarding task list: https://github.com/cncf/toc/issues/1369

Feel free to reach out with any questions you might have!
