### ISSUE TITLE
[Sandbox] rainforest

### ISSUE THREAD

**Issue by tachunwu** [cncf/sandbox#61]
### Application contact emails

tachunwu.go@gmail.com

### Project Summary

Ultra light-weight Data Mesh

### Project Description

rainforest: Ultra Light-weight Data Mesh Engine
In an era where the data landscape is undergoing massive transformation, centralized solutions like traditional data lakes and warehouses struggle to meet the needs of distributed organizations and rapid iterations. Enter Rainforest, an ultra-lightweight Data Mesh core engine.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/Awareness-Labs

### Project repo URL in scope of application

https://github.com/Awareness-Labs/rainforest

### Website URL

https://awareness-labs.github.io/

### Roadmap

https://github.com/Awareness-Labs/rainforest#roadmap

### Roadmap context

https://github.com/Awareness-Labs/rainforest/blob/main/Roadmap.md

### Contributing Guide

https://github.com/Awareness-Labs/rainforest/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/cncf/foundation/blob/main/code-of-conduct.md

### Adopters

https://brobridge.com/

### Contributing or Sponsoring Org

https://brobridge.com/

### Maintainers file

https://github.com/Awareness-Labs/rainforest/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

**Why do you want to contribute the project to the CNCF?**

We aim to contribute our project to the CNCF because it offers an influential platform and ecosystem that can grant our project broader exposure, support, and collaboration. Moreover, the expertise and resources of CNCF can accelerate the development and maturation of our project.

**What value does being part of the CNCF provide the project?**

Being part of CNCF confers multiple values to our project. Firstly, it amplifies the project's credibility and influence. Secondly, we can leverage CNCF's resources and network to expedite development and innovation. Additionally, we can participate in various CNCF events and training, further enhancing our technical and operational competencies.

Our primary motivation for choosing CNCF lies in its leadership and stellar reputation in the cloud-native technology arena. With a vast and active community, CNCF signifies diverse support and collaboration opportunities for our project. We believe that our project's philosophy aligns closely with CNCF's objectives, fostering seamless collaboration between the project and the ecosystem.

### Benefit to the Landscape

The inclusion of Rainforest will enhance the CNCF ecosystem, particularly in the realm of data management solutions. In the current cloud-native landscape, decentralized organization and distributed data management are paramount challenges, especially in the context of ensuring data synchronization, efficiency, and security.

Rainforest addresses this very challenge. Unlike traditional NATS systems, Rainforest is not just a messaging system but a data management platform at a higher level of abstraction. It amalgamates the high-performance benefits of NATS and adds functionalities specifically designed for distributed data ownership and decentralization. Furthermore, its compatibility and in-built OLTP and OLAP engines make it a versatile and comprehensive solution, apt for both current and future data management needs.

In essence, the addition of Rainforest will fill a gap in the CNCF landscape, offering an advanced data management platform that aids organizations in efficiently tackling the nuances of decentralization.

### Cloud Native 'Fit'

Rainforest's "fit" in the Cloud Native ecosystem is quite evident. Firstly, its distributed architecture epitomizes the core essence of cloud native, enabling elastic scaling and contraction within a cloud environment, while ensuring a high degree of fault tolerance. This guarantees high availability, maintaining system stability even in a distributed setting.

Secondly, Rainforest's decentralized data management approach is a pristine reflection of the microservices and cloud native philosophy. Offering efficient data synchronization and inter-service communication, it allows multiple independent services or applications to share and manage data without the need for centralized storage.

Moreover, being built on NATS means Rainforest can provide lightweight, efficient, and secure real-time communication in the cloud environment. This ensures data timeliness and consistency, a key demand for cloud-native applications.

In essence, Rainforest embodies the core values of cloud native through its distributed, decentralized, and real-time communication characteristics. It not only complements the cloud-native tech stack but introduces an innovative and efficient data management solution for cloud-native applications.

### Cloud Native Overlap

Rainforest has a degree of overlap with several CNCF projects:

NATS: While Rainforest is built upon NATS, its functionalities go beyond NATS's basic message delivery. Rainforest offers a higher-level of data management and synchronization, whereas NATS remains focused on basic message passing.

Vitess: Vitess focuses on enabling MySQL to run in large-scale cloud environments. It has some overlap with Rainforest's data management, but Rainforest provides a more generic solution agnostic to the data source.

Cortex: Cortex provides a highly scalable and highly available Prometheus implementation. Given that Rainforest might integrate with Prometheus, there might be functional overlaps, but Rainforest's main emphasis is on data management and synchronization, not monitoring.

ETCD: ETCD is a consistent key-value store primarily used to store configuration data for Kubernetes clusters. While it too can function in data management, Rainforest offers broader data synchronization and distributed data management functionalities.

Despite these overlaps, Rainforest still holds a unique position and value in the realm of data synchronization and decentralized data management.

### Similar projects

NATS

### Landscape

No

### Business Product or Service to Project separation

Rainforest operates as a distinct entity, entirely community-driven. Its development and governance will remain separate from any commercial product of the sponsoring company. All decisions and directions will be transparent, and any potential overlap or confusion with commercial products will be actively addressed.

**Comment by jberkus** [comment]
Questions:

1. Currently Rainforest has one maintainer.  If accepted to the CNCF, what are your plans to attract additional contributors, and eventually maintainers?
2. Can you explain what products Brobridge has built on Rainforest, and how those differ from Rainforest?  Are they just hosted/supported versions, or something else?
3. Could you do a presentation to TAG-Storage explaining how Rainforest works and how it integrates into a cloud native stack?

**Comment by justincormack** [comment]
Hi, we reviewed this project in the sandbox meeting. We would like you to answer the questions above. In addition we feel this project is too early for sandbox at present, and would encourage you to keep growing the project and community, and come back after 12 months or so when you feel you are ready for re-evaluation.
