### ISSUE TITLE
[Sandbox] Inspektor Gadget

### ISSUE THREAD

**Issue by blixtra** [cncf/sandbox#7]
### Application contact emails

chriskuehl@microsoft.com, mauriciov@microsoft.com

### Project Summary

Inspektor Gadget is a collection of tools (or gadgets) to debug and inspect Kubernetes resources and applications

### Project Description

Inspektor Gadget is a collection of tools (or gadgets) to debug and inspect Kubernetes resources and applications. It manages the packaging, deployment and execution of [eBPF](https://ebpf.io/) programs in a Kubernetes cluster, including many based on [BCC](https://github.com/iovisor/bcc) tools, as well as some developed specifically for use in Inspektor Gadget. It automatically maps low-level kernel primitives to high-level Kubernetes resources, making it easier and quicker to find the relevant information.

### Org repo URL

https://github.com/inspektor-gadget

### Project repo URL

ttps://github.com/inspektor-gadget/inspektor-gadget

### Additional repos

https://github.com/inspektor-gadget/website

### Website URL

https://www.inspektor-gadget.io/

### Roadmap

https://github.com/orgs/kinvolk/projects/22 (future: https://github.com/orgs/inspektor-gadget/projects/1)

### Roadmap context

Current focus is on consistency, integrations, creating APIs and improving usability.

### Contributing Guide

https://github.com/inspektor-gadget/inspektor-gadget/blob/main/docs/devel/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/kinvolk/contribution/blob/master/CODE_OF_CONDUCT.md - Can adopt the CNCF CoC if preferred.

### Contributing or Sponsoring Org

Microsoft

### Maintainers file

https://github.com/inspektor-gadget/inspektor-gadget/graphs/contributors (top 4 contributors, can put this in file)

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We want to encourage further community adoption and contributions to Inspektor Gadget and feel that having the project in a neutral organization reinforces the open governance we wish to establish for the project. We also value this step as we feel it brings the project even closer to the cloud native community for which it is designed.

### Benefit to the Landscape

Inspektor Gadget provides a set of tools for inspecting, debugging and troubleshooting Kubernetes clusters and applications. To our knowledge, it is a unique tool that is not directly comparable to any existing CNCF project. Inspektor Gadget enables the use of powerful eBPF tools in cloud-native environments; thus, empowering developers and users to understand their problems, helping them to solve them faster and makes great use of k8s related technology.

### Cloud Native 'Fit'

Inspektor Gadget is a unique tool amongst the CNCF projects. Its focus is on inspecting, debugging and troubleshooting various aspects of Kubernetes clusters and cloud-native applications. It can be used interactively or integrated into one's observability or alerting systems via its interfaces.

Some of the included eBPF-based gadgets assist in improving security, others measuring resource use and performance, while others allow you to observe various events happening across your system. Inspektor Gadget essentially brings the power of eBPF and tools such as those from the BCC project to Kubernetes clusters and cloud native applications.

### Cloud Native 'Integration'

Kubernetes, containerd, cri-o

Most of Inspektor Gadget’s functionality relies on it running in a Kubernetes cluster. One of its main tasks after all is to map low-level kernel concepts to high-level Kubernetes concepts.
There is a tool in Inspektor Gadget called local-gadget which does not require Kubernetes but does rely on a container runtime. This is used for testing IG locally and to troubleshoot a Kubernetes cluster when a component like the API server is not responsive.

### Cloud Native Overlap

While Inspektor Gadget does have some overlapping functionality with a couple CNCF projects, the purpose of the Inspektor Gadget project is unique. Inspektor Gadget should be seen as a toolbox. A toolbox includes essential but varied tools. Tools such as screwdrivers, a hammer, pliers, wire cutters, multimeter, etc. are all essential but serve quite different purposes depending on what you are building or fixing. Similarly, Inspektor Gadget does not focus on investigating one aspect of your system but includes tools that are essential but leaves it to the user or architect to decide how to use them. That is, Inspektor Gadget is not a security or network tool, or an observability tool. But there are individual tools in the Inspektor Gadget toolbox that a user could use as such, or a system architect could use to build such tools.

One could say Pixie is the closest project to Inspektor Gadget as they both use eBPF programs in Kubernetes clusters. But the projects have different focuses and go about things differently. Inspektor Gadget is a collection of varied tools and focused on interactive debugging sessions and being a tool with which other tools can be built.

### Similar projects

In many ways, Inspektor Gadget can be viewed as BCC, but for Kubernetes clusters. Inspektor Gadget started as a wrapper for BCC that provided the mapping between the kernel and Kubernetes concepts. Since, Inspektor Gadget has expanded its scope but the above is still very much true.

### Product or Service to Project separation

While Inspektor Gadget is used inside Azure, it is consumed using the same interfaces available to everyone. Thus, there is no "mixing" of internal products and the open-source project.

### Project presentations

No

### Additional information

N/A

**Comment by dims** [comment]
@blixtra Chris, thanks for the strong submission! (tangential and just fyi for now) https://github.com/cncf/foundation/issues/474

**Comment by cathyhongzhang** [comment]
I support this project being included as a sandbox project. I would also like to see that it has contributors from more companies down the road.
