### ISSUE TITLE
[Sandbox] stacker

### ISSUE THREAD

**Issue by rchamarthy** [cncf/sandbox#73]
### Application contact emails

ravi@chamarthy.dev
rchincha@cisco.com

### Project Summary

a vendor-neutral OCI-native container image builder

### Project Description

Software supply chain security is front and center in the minds of all security practitioners, especially given vital US government compliance requirements. **stacker** and OCI registries such as **zot** (a CNCF sandbox project) make a _vendor-neutral_ end-to-end (build, publish, deploy) secure software supply chain viable.
 
Differentiation:
1. stacker is general-purpose and can be used for any programming language environment
2. stacker is vendor-neutral and strictly conforms to OCI specs
3. SBOM generation and strict validation is part of the image building process itself instead of a post-processing step
4. stacker can consume, publish and co-locate these artifacts with the container images using OCI refererrers
5. stacker's capabilities are a superset of other commonly used tools such as docker and podman
6. Container images and artifacts generated by stacker along with a OCI-native registry such as **zot** are readily compatible with the rest of the container and Kubernetes ecosystem in terms of deployment and enforcement of security policies

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/project-stacker

### Project repo URL in scope of application

https://github.com/project-stacker/stacker

### Additional repos in scope of the application

https://github.com/project-stacker/stacker-bom
https://github.com/project-stacker/stacker-build-push-action

### Website URL

https://stackerbuild.io

### Roadmap

https://github.com/orgs/project-stacker/projects/1

### Roadmap context

* Continued strong conformance to OCI image and distribution specfications
* Enhanced support for secure software supply chain
* Support for OCIv2 prototypes like atomfs/puzzlefs.

### Contributing Guide

https://github.com/project-stacker/stacker/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/project-stacker/stacker/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/project-stacker/stacker/blob/main/ADOPTERS.md

### Contributing or Sponsoring Org

https://www.cisco.com

### Maintainers file

https://github.com/project-stacker/stacker/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

The goals of this project are compatible with CNCF.

### Benefit to the Landscape

1. Vendor-neutral since strong conformance to OCI specs
2. Helps meet secure software supply chain requirements

### Cloud Native 'Fit'

"Application Definition & Image Build"
 
Container images are the defacto application lifecycle mechanism in the cloud native world making CNCF a great fit for this project since it can also be readily used to meet secure software supply chain requirements in a vendor-neutral fashion.

### Cloud Native 'Integration'

Although stacker is a standalone tool, the container images and artifacts it produces can be stored on OCI registries such as **zot** and deployed in Kubernetes. Furthermore, the artifacts such as SBOMs that it produces can be used for policy enforcement using tools such as Kyverno.

### Cloud Native Overlap

Similarities:
1. https://www.cncf.io/projects/ko/ - **ko** can also generate OCI images but are specific to certain programming languages
2. https://github.com/oras-project/oras - **oras** can push and pull OCI images, however they cannot build them

### Similar projects

Similar projects:

https://github.com/containers/buildah
https://github.com/docker/buildx

### Landscape

yes

### Business Product or Service to Project separation

N/A

### Project presentations

https://github.com/project-stacker/stacker#conference-talks

### Project champions

Stephen Augustus - https://github.com/justaugustus

**Comment by rchincha** [comment]
https://github.com/kubernetes/kubernetes/issues/121742
^ another data point why a tool such as stacker is needed.

Also, with recent PRs merged, stacker project is in a much better shape to tackle software supply chain security aligning with OCI artifacts work.

**Comment by rchincha** [comment]
"Landscape: no"
updated to "yes"

https://landscape.cncf.io/?item=app-definition-and-development--application-definition-image-build--stacker

**Comment by jberkus** [comment]
TAG-CS note:

Project stacker currently has:

- a pretty good contributing guide
- five maintainers, 4 Cisco & 1 Netflix
- no written governance (yet)

**Comment by rchincha** [comment]
@jberkus 
> no written governance (yet)

^ is this a blocker?

**Comment by jberkus** [comment]
@rchincha  Incoming Sandbox projects are _not_ required to have written governance.  It is a credit to the project if they do have one, and if the project is a single-company project, having a good written governance may reassure the TOC around product/project separation.

**Comment by mrbobbytables** [comment]
Follow-up from today's sandbox review, Stacker will be moved to a vote. 👍 
But please coordinate a project review with TAG-Runtime
/vote

**Comment by Cmierly** [comment]
Hello and congrats on being accepted as a CNCF Sandbox project!

Here is the link to your onboarding task list: https://github.com/cncf/toc/issues/1370

Feel free to reach out with any questions you might have!
