### ISSUE TITLE
[Sandbox] Kubecolor

### ISSUE THREAD

**Issue by prune998** [cncf/sandbox#75]
### Application contact emails

prune@lecentre.net

### Project Summary

KubeColor is a kubectl plugin used to add colors to your kubectl output.

### Project Description

kubecolor colorizes your kubectl command output and does nothing else. kubecolor internally calls kubectl command and try to colorizes the output so you can use kubecolor as a complete alternative of kubectl.

It's a user opt-in and does not change the behaviour of any commands. In the worste case, the output is not colorized. 
Output to other programatic treatments (like using a pipe `kubectl get pods | <other command>` are detected and colourization is disabled).

This is useful as it offers a far better output reading. 

Note that https://github.com/kubecolor/kubecolor is NOT the original project, but a fork + a lot of patching, that as of today makes it a totally different project. 

To be noted:

- better parsing of `kubectl` output to enhance the colorization experience
- support colorization on a lot more `kubectl <commands>` than the original
- offer a better color scheme (and simpler) that is more inclusive with some color-blindmess 
- Work in progress to allow customized color schemes
- more active than the original project
- 2 maintainers (for now, willing to add more)
- `brew` install for Mac OSX
- a github project not tied to a user

While it would be better that `kubectl` itself support colored output, it's not yet the case. I heard of a SIG working on such a thing a year ago, but i'm still unsure about the evolution of this project and can't find any trace of it. 

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/kubecolor

### Project repo URL in scope of application

https://github.com/kubecolor/kubecolor

### Website URL

https://github.com/kubecolor/kubecolor/blob/main/README.md

### Roadmap

none yet

### Roadmap context

KubeColor is quite mature and the only roadmap is:

- support a user-defined color schema 

### Contributing Guide

none yet

### Code of Conduct (CoC)

none yet (will reuse the CNCF one)

### Contributing or Sponsoring Org

https://github.com/kubecolor/kubecolor/blob/main/README.md#contributions

### Maintainers file

none yet, 2 maintainers 

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

`Kubecolor` is a great tool, and I'm sad when I see terminal demos, like at KubeCon, where everything is outputed white in a black terminal (or worse, black in a white terminal).
Being part of the CNCF echosystem will allow a better visibility and usage for `kubecolor`

### Benefit to the Landscape

as stated before, if being part of CNCF gives more visibility to the project, then every people using apps in the  CNCF landscape, and specifically Kubernetes users, will benefit.

### Cloud Native 'Fit'

it fits as it enhance the experience of `kubectl`, which is widely used, everyday, by thousands of engineers.

### Cloud Native 'Integration'

This project enhance the output of `kubectl`, which is relied on to provide the content to colorize.

### Similar projects

https://github.com/hidetatz/kubecolor is the original project which is undermaintained and outdated.

### Landscape

no

### Business Product or Service to Project separation

none i'm aware of

### Project presentations

no

### Project champions

not sure, but I'm sure many are already using it.

### Additional information

Don't forget to ⭐ the project if you're already using it :)
https://github.com/kubecolor/kubecolor

Thanks !

**Comment by jberkus** [comment]
Prune, 

This looks like it should be a subproject of Kubernetes SIG-CLI, not a CNCF project.  Have you talked to SIG-CLI about it?

**Comment by prune998** [comment]
maybe that's what I should do :)

**Comment by prune998** [comment]
Thanks for your help @jberkus. I'm closing this request.
