### ISSUE TITLE
[Sandbox] Cloud Intel

### ISSUE THREAD

**Issue by unknownhad** [cncf/sandbox#77]
### Application contact emails

anand.himanshu17@gmail.com

### Project Summary

Threat intel for public cloud

### Project Description

The "CloudIntel" project,  dedicated to monitoring attacks on Cloud infrastructure, specifically targeting cloud-native and cloud-only threats. It serves as a resource hub, offering key elements like Indicators of Compromise (IOCs), malware analysis, and malware samples to aid in this surveillance​​​​.

The project addresses a critical need in cybersecurity, focusing on protecting Public Cloud environments, which are increasingly targeted by cyber attacks. Given the widespread use of Cloud for various critical applications and services, having a dedicated repository that collates and analyses threats specific to Pubic Cloud infrastructure is vital for maintaining the security and integrity of cloud-based systems.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/unknownhad/CloudIntel

### Project repo URL in scope of application

https://cloudintel.info/

### Website URL

https://cloudintel.info/

### Roadmap

https://github.com/unknownhad/CloudIntel/issues

### Roadmap context

Currently Platform only support AWS infrastructure, though idea is to expand it for all cloud platforms.
And add more components in Cloud infrastructure to achieve better telemetry of attacks and TTPs.

### Contributing Guide

https://github.com/unknownhad/CloudIntel/issues

### Code of Conduct (CoC)

https://github.com/unknownhad/CloudIntel/blob/main/README.md

### Maintainers file

https://github.com/unknownhad/CloudIntel/blob/main/README.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Contributing our project to the CNCF aligns perfectly with our goals, as it offers an invaluable platform for gaining insights into making our product more consumer-friendly. As an engineer, my expertise lies in development, but I lack experience in understanding market needs and user preferences. CNCF's vast network and seasoned professionals provide a unique opportunity for receiving targeted feedback and guidance. This collaboration will not only help in refining our project to meet real-world demands but also ensure it aligns with the evolving trends and standards in the cloud-native ecosystem. By joining CNCF, we aim to transform our project into a more accessible and widely-adopted tool, contributing significantly to the cloud-native community.

### Benefit to the Landscape

Contributing  to the Cloud Native Computing Foundation (CNCF) offers a unique opportunity to address emerging threats and vulnerabilities in cloud environments. Being part of CNCF would enable us to collaborate with a wider community of experts, enhancing our capabilities in early detection and resolution of security issues. This alignment with CNCF's ecosystem also means access to cutting-edge resources and knowledge, which is crucial for developing innovative solutions to safeguard cloud infrastructures. Our project, detailed at [AWSAttacks on GitHub](https://github.com/unknownhad/AWSAttacks), aims to leverage these benefits, making a significant contribution to cloud security research and practice.

### Cloud Native 'Fit'

Cloud Intel focuses on improving security in cloud environments, a key aspect of cloud-native technology. It aligns with the cloud-native approach by addressing security threats in systems that use microservices and containers – two fundamental elements of cloud-native architectures. Additionally, our project supports continuous improvement and automation, which are essential for cloud-native development, and emphasises open-source collaboration, allowing for wider community input and enhancement. This makes our project not just relevant, but also a valuable contributor to the evolving cloud-native ecosystem.

### Similar projects

N/A

### Landscape

No

### Business Product or Service to Project separation

N/A

**Comment by jberkus** [comment]
Two questions:

1. This project appears to be a service rather than redistributable software, is that correct?
2. At this point, it's entirely the work of a single developer?

**Comment by unknownhad** [comment]
1) yes for now I am distributing the final results (IOC) as a service. The idea is to open full code for other folks to deploy it as per the need.
2) mostly yes, I am getting some help on the side for testing and website.

**Comment by mrbobbytables** [comment]
@unknownhad following the Sandbox Review meeting today (2024-06-11) the project is looks interesting but it seems a bit too early, and the general suggestion from the TOC was to reapply once its a bit more mature and has additional maintainers.

Thanks!
