### ISSUE TITLE
[Sandbox] TrestleGRC

### ISSUE THREAD

**Issue by vikas-agarwal76** [cncf/sandbox#78]
### Application contact emails

avikas@in.ibm.com, ancas@us.ibm.com, manjiree.gadgil@ibm.com, jpower@redhat.com

### Project Summary

A tooling platform for managing compliance artifacts as code using NIST's OSCAL standard.

### Project Description

This project helps automate the creation and management of various compliance artifacts in a machine processable format based on NIST OSCAL standard, The OSCAL standard provides a compliance framework and the corresponding set of key compliance artifacts expressed in machine processable formats enabling all compliance documents to be treated as code and therefore processed and managed in the same manner.

**Trestle** is an ensemble of tools that enable the creation, validation, and governance of documentation artifacts for compliance needs. It leverages NIST's [OSCAL](https://pages.nist.gov/OSCAL/documentation/) as a standard data format for interchange between tools and people, and provides an opinionated approach to OSCAL adoption.

Trestle is designed to operate as a CI/CD pipeline running on top of compliance artifacts in git, to provide transparency for the state of compliance across multiple stakeholders in an environment friendly to developers. Trestle passes the generated artifacts onto tools that orchestrate the enforcement, measurement, and reporting of compliance.

**Agile Authoring:** It is a collaborative platform enabling various compliance personas to orchestrate their individual aspects of the compliance artifacts via an interface of their choice. It is a Trestle-based GitOps automated workflow and ensures artifacts consistency and traceability. It provides ready to use CI/CD pipeline configuration and setup using a GitOps approach with Trestle for OSCAL document management and collaboration.

**Compliance to Policy:** Compliance-to-Policy (C2P) bridges Compliance as Code and Policy as Code. C2P takes Compliance requirements and generates technical policies for Policy Validation Points (PVPs), and takes PVP native results and generates Compliance Assessment Results. C2P reduces the cost to implement the interchange between Compliance artifacts and PVP proprietary artifacts. C2P is extensible to various PVPs through plugin.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/oscal-compass

### Project repo URL in scope of application

https://github.com/oscal-compass/compliance-trestle

### Additional repos in scope of the application

https://github.com/oscal-compass/compliance-trestle-agile-authoring
https://github.com/oscal-compass/compliance-to-policy
https://github.com/oscal-compass/compliance-trestle-fedramp

There are few additional repos in the organization for sample content and demo which are also in the scope.

### Website URL

https://oscal-compass.github.io/compliance-trestle/

### Roadmap

https://github.com/oscal-compass/compliance-trestle/issues/1480

### Contributing Guide

https://oscal-compass.github.io/compliance-trestle/contributing/mkdocs_contributing/

### Code of Conduct (CoC)

https://oscal-compass.github.io/compliance-trestle/mkdocs_code_of_conduct/

### Adopters

We have reached 15k downloads per month from our adopters. We have internal collaboration with adopters such as SunStone, RegScale, Chicago Mercantile Exchange, Singapore Government, however only RegScale is in open-space to publicly review the adoption of our technology. 

### Contributing or Sponsoring Org

https://www.ibm.com/

### Maintainers file

https://oscal-compass.github.io/compliance-trestle/maintainers/

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Cloud Native systems represent a paradigm shift in both technical and human operations workflows.  The community (and industry) has invested significant time researching and solutioning approaches to Cloud Native Cyber Security concerns and topics: software vulnerabilities, risk management, software component dependencies and infrastructure as code (aka supply chain), malicious attackers, threat models, and technical security assessments. However, many commercial, non-profit community and government organizations performing services or providing data storage on cloud must abide by national, regional, or local laws and regulations regarding user privacy and data, with assurance of protection of their compute and data processing integrity and resilience. These cross cutting concerns for mission critical environments on cloud native span not only specific technical configuration of software and systems, but also require complex orchestration of human administrative, operational, and design activities, especially when involving  audit activities expecting concrete, reviewable independent audit artifacts. 

Moreover, the timeline for the renewal of these compliance and audit artifacts has shifted recently on cloud in many industries from annual and quarterly, to continuous compliance, forcing an evolution of the manual compliance processes into the automation and engineering realm with concerns, technologies, and data models specific to modelling compliance and requiring continuous compliance and hence specific compliance automation. 

In the universe of cloud-native constraints and concerns for mission critical industries, our projects are addressing the emerging cloud and AI regulatory compliance automation requirements by supporting Compliance, Risk, and Policy from an “as code” engineering perspective vs the traditional now unscalable manual labor perspective.

### Benefit to the Landscape

As organizations move their sensitive workloads to public cloud environments, they need to comply with multiple different regulations. Hence, they need to modernize from manual document based compliance management to automated processes for continuous compliance known as compliance-as-code.

Trestle is one of the early implementor of the NIST OSCAL standard in the Compliance area that enables all compliance documents to be treated as code and therefore processed and managed in the same manner.. Adding this project to CNCF will greatly increase the reach of CNCF to organizations and people working in the compliance area.

### Cloud Native 'Fit'

Cloud Native has seen in the recent years adoption for various domains that traditionally used on-prem / dedicated environments - Financial Services, Life Sciences, AI. Shift to continuous compliance, forcing an evolution into the automation and engineering realm with concerns, technologies, and data models specific to modelling compliance - System Security Plan, Audit plan artifats.

Many commercial, non-profit community and government organizations performing services or providing data storage must abide by national, regional, or local laws and regulations regarding user privacy and data, with assurance of protection of their compute and data processing integrity and resilience. These cross cutting concerns span not only specific technical configuration of software and systems, but also require complex orchestration of human administrative, operational, and design activities, especially when involving  audit activities expecting concrete, reviewable independent audit artifacts. 

Moreover, the timeline for the renewal of these artifacts has shifted recently in many industries from annual and quarterly, to continuous compliance, forcing an evolution of the manual compliance processes into the automation and engineering realm with concerns, technologies, and data models specific to modeling compliance and hence aligned with, but very different from cyber security frameworks.

This project helps automate the creation and management of various compliance artifacts in a machine processable format based on NIST OSCAL standard,

### Cloud Native 'Integration'

Compliance-to-Policy is designed to bridge Compliance as Code such as Open Security Controls Assessment Language (OSCAL) and Policy as Code used by Policy Validation Point (PVP). It generates policies in native format of PVP from OSCAL Component Definitions and produces OSCAL Assessment Results from the native assessment results of PVP. Compliance-to-Policy can be used both as a command-line tool and a Python library, making it easy and flexible to integrate into your Continuous Compliance pipelines, such as GitHub Actions, Tekton Pipelines, or Agile Authoring Pipelines. It supports multiple PVP engines, including Kyverno, Open Cluster Management, and the open-source Auditree, through dedicated plugins for each. Custom plugins can be implemented with a small amount of Python code.

Supported Integrations w/ CNCF projects: Kyverno, Open Cluster Management Policy, OPA (roadmap)

- [Kyverno](https://kyverno.io/) is a policy engine designed for Kubernetes, where policies are managed as Kubernetes resources. Kyverno policies can validate, mutate, generate, and clean up Kubernetes resources.

- [Open Cluster Management](https://open-cluster-management.io/) is a multi-cluster management platform that provides governance of Kubernetes policies. [Its policy framework](https://open-cluster-management.io/concepts/policy/) allows for the validation and enforcement of policies across multiple clusters.

- [OPA](https://www.openpolicyagent.org/) is policy-based control for cloud native environments

Supported Integrations w/ open source technology for cloud native: Auditree, Ansible (roadmap)

- [Auditree](https://auditree.github.io/) is a GitOps based workflow automation that enables the collection and verification of evidence, building a long-term store of evidence in an git "evidence locker." Evidence is gathered by code scripts called "fetchers" and verified by "checks."

- [Ansible](https://www.ansible.com/) is a versatile automation tool used for managing and configuring various IT systems and services. Ansible latest automated Policy as Code capability will help you automate compliance and policy enforcement.

Supported Integrations w/ multi-cluster/multi-cloud compliance

- [KubeStellar](https://docs.kubestellar.io/) (CNCF sandbox) is a multi-cluster workload management platform seamlessly scaling out a single Kubernetes workloads to multiple Kubernetes clusters.

### Similar projects

N/A

### Landscape

We are starting under the Security TAG (Pushkar Joglekar, Andrew Martin, Francesco Beltramini) while we work to find the right working group / TAG for compliance related projects.

### Business Product or Service to Project separation

N/A

### Project presentations

Compliance TAG review at Security TAG - Wednesday, October 25, 2023 from 1:00 PM to 2:00 PM
MORE DETAILS: https://docs.google.com/document/d/170y5biX9k95hYRwprITprG6Mc9xD5glVn-4mB2Jmi2g/

Pushkar Joglekar, Andrew Martin andy@control-plane.io, Francesco Beltramini), Emily Fox 

### Project champions

Robert Ficcaglia <rficcaglia@sunstonesecure.com>
Anca Sailer <ancas@us.ibm.com>

**Comment by vikas-agarwal76** [comment]
@amye Please provide any updates based on the review that happened on 23 Jan. What are the next steps for us?

**Comment by amye** [comment]
This project was not reviewed. It may be reviewed in the April 9th session, but it's not guaranteed.

**Comment by ancatri** [comment]
@amye Hi, HNY :) I guess in the interest of our collaborators and users we should start the Office Hours - we reached 7k downloads per months and are interested to link to the community asap, rather than wait for months.
What do you suggest?

**Comment by ancatri** [comment]
@amye is there any way/condition to accelerate the process? 
also, was there any specific reason it was not reviewed (I assumed workload, but just to validate)
Thank you!

**Comment by amye** [comment]
> This project was not reviewed. It may be reviewed in the April 9th session, but it's not guaranteed.

This is the next scheduled review session.

**Comment by ancatri** [comment]
@amye Thank you for your reply , I understand we moved to April. Can you pls help with the clarification question : did you guys run out of time OR was anything about our submission? Thanks so much for shading some light here!

**Comment by ancatri** [comment]
For instance, the org has 3 projects that work together , do we submit a joined sandbox request (as the one submitted above) 
OR we should submit a request for each project. 
Thanks!

**Comment by amye** [comment]
It wasn't discussed, the TOC has not yet provided input on this.

**Comment by ancatri** [comment]
@amye Hi! What was the outcome for this project in the last CNCF Sandbox review? Thanks!

**Comment by amye** [comment]
This project was not reviewed. Projects in the 'upcoming' queue are reviewed by the TOC in a meeting. 
<img width="453" alt="_Sandbox__TrestleGRC_·_Issue__78_·_cncf_sandbox" src="https://github.com/cncf/sandbox/assets/107161/3e8883ba-c193-4192-bef5-627365edc49d">

**Comment by jberkus** [comment]
TAG-CS review, this project has:

- A fairly complete Contributing document
- A well-developed [contributor ladder](https://github.com/oscal-compass/community/blob/main/MEMBERSHIP.md), but no other written governance
- 6 maintainers from IBM and one from Red Hat

**Comment by vikas-agarwal76** [comment]
@jberkus Thanks for your review. We have added the governance structure at the oscal-compass organization level. It is available here - https://github.com/oscal-compass/community/blob/main/GOVERNANCE.md

**Comment by jberkus** [comment]
@vikas-agarwal76 what's the relationship between oscal-compass and the rest of the project?

**Comment by mrbobbytables** [comment]
Follow-up from today's sandbox review, TrestleGRC will be moved to a vote 👍 
/vote

**Comment by jflowers** [comment]
@jberkus in yesterday's meeting IIUC I wanted to clarify that this project does not develop compliance standards. 

From our [community README](https://github.com/oscal-compass/community):
The OSCAL Compass project is a set of tools that enable the creation, validation, and governance of documentation artifacts for compliance needs. It leverages NIST's OSCAL ([Open Security Controls Assessment Language](https://pages.nist.gov/OSCAL/)) as a standard data format for interchange between tools and people, and provides an opinionated approach to OSCAL adoption.

Does this clear up the confusion?

**Comment by Cmierly** [comment]
Hello and congrats on being accepted as a CNCF Sandbox project!

Here is the link to your onboarding task list: https://github.com/cncf/toc/issues/1371

Feel free to reach out with any questions you might have!
