### ISSUE TITLE
[Sandbox] kluctl

### ISSUE THREAD

**Issue by codablock** [cncf/sandbox#8]
### Application contact emails

ablock@codablock.de

### Project Summary

The missing glue to put together large Kubernetes deployments

### Project Description

Kluctl is the missing glue that puts together your (and any third-party) deployments into one large declarative Kubernetes deployment, while making it fully manageable (deploy, diff, prune, delete, ...) via one unified command line interface.

Kluctl tries to be as flexible as possible, while remaining as simple as possible. It reuses established tools (e.g. Kustomize and Helm), making it possible to re-use a large set of available third-party deployments.

Kluctl is centered around "targets", which can be a cluster or a specific environment (e.g. test, dev, prod, ...) on one or multiple clusters. Targets can be deployed, diffed, pruned, deleted, and so on. The idea is to have the same set of operations for every target, no matter how simple or complex the deployment and/or target is.

Kluctl does not depend on external operators/controllers and allows to use the same deployment wherever you want, as long as access to the kluctl project and clusters is available. This means, that you can use it from your local machine, from your CI/CD pipelines or any automation platform/system that allows to call custom tools.

### Org repo URL

https://github.com/kluctl

### Project repo URL

https://github.com/kluctl/kluctl

### Additional repos

https://github.com/kluctl/flux-kluctl-controller
https://github.com/kluctl/www-kluctl.io

### Website URL

https://kluctl.io

### Roadmap

N/A

### Roadmap context

There is no written roadmap yet, but it can be created if necessary. The focus is currently on stability, documentation and community building.

Kluctl itself is at the point where all necessary features are implemented to make it usable in practical in daily DevOps business. It's also stable to the point where it can be used in production.

### Contributing Guide

https://github.com/kluctl/kluctl/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/kluctl/kluctl/blob/main/CODE_OF_CONDUCT.md

### Adopters

N/A

### Contributing or Sponsoring Org

N/A

### Maintainers file

https://github.com/kluctl/kluctl/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We believe that Kluctl is in a stable state already and that it can be safely used in production environments.

What is missing right now, is visibility and adoption of the project. We would like to signal that this project is going to stay and that it is able to mature to a point where it becomes completely independent from the original developers (especially me/@codablock, as I'm contributing 99% of the code at the moment).

To accomplish this, we also need guidance and support from more experienced Open Source communities, especially in the cloud native space.

### Benefit to the Landscape

Kluctl fills a gab that I've perceived for many years. There are many tools available (e.g. Helm and Kustomize) that are very good at their specific use cases, but hard to combine and integrate in a way that avoids "glue" around it. In many cases, the "glue" turns out to be Bash scripts and easily become hard to maintain.

Even uprising new CI/CD tooling, for example GitOps style controllers, do not fill this gab completely, as they require you to accept full dependence on them. This means, if you go with GitOps, you can't revert to non-GitOps workflows even when needed.

Kluctl allows you to declaratively define Kluctl deployments, comprising of Kustomize deployments and Helm Charts and then deploy/diff/prune/delete them via the Kluctl CLI on your local machine. At the same time, you can use a CI/CD Pipeline or GitOps style controller to automate the deployment. The same deployment project can be used for all workflows and switching between them whenever needed is not an issue. You can also have workflows where local Kluctl invocations only perform dry-runs (to allow testing changes fast) while GitOps/Pipeline workflows perform the actual deployment. At all times, it is guaranteed that Kluctl does the same, no matter how/where it was invoked.

I'd suggest to watch the YT video linked below. It also contains a presentation where I try to describe the requirements that Kluctl tries to fulfil.

### Cloud Native 'Fit'

Kluctl is used to deploy things to Kubernetes. What exactly is deployed is completely up the user of Kluctl. It could be native K8s resources (e.g. Deployment, Service, ...) or CRD based resources like cluster-api objects.

In the end, Kluctl can be used to manage everything that needs to be applied/deployed to the cluster, giving you all the benefits that Kluctl offers (e.g. dry-runs, diffs, configuration management, ...).

### Cloud Native 'Integration'

* Kubernetes: It deploys to Kubernetes
* Flux: The [flux-kluctl-controller](https://github.com/kluctl/flux-kluctl-controller) implements GitOps style controller and reuses Flux's source CRs.
* Helm: Kluctl has a Helm integration that allows to deploy Helm Charts
* Kustomize: Kluctl has a Kustomize integration that allows to deploy Kustomization deployments

### Cloud Native Overlap

* Flux: Kluctl can be used together with the [flux-kluctl-controller](https://github.com/kluctl/flux-kluctl-controller) to implement GitOps style deployments. A lot of things that can be solved with Flux's Kustomize and Helm Controllers can also be solved through the Helm/Kustomize integration inside Kluctl.
* ArgoCD: A lot of things that can be solved with ArgoCD can also be solved through the Helm/Kustomize integration inside Kluctl.
* Helm: Helm templating can be used to solve a few of the things solved by Kluctl. It's however limited in its abilities to structure the deployment project.

### Similar projects

The most similar project is probably [helmfile](https://github.com/roboll/helmfile). The biggest difference between Helmfile and Kluctl is that Helmfile obviously concentrates on Helm while allowing to deploy Kustomize resources as well by converting these to Helm Charts internally. Kluctl goes the other way around and converts Helm Charts to Kustomize deployments and deploys these.

### Product or Service to Project separation

N/A

### Project presentations

I have not presented to the tag-app-delivery yet, but plan to do so. Until then, you can watch the [Hands-on Introduction to kluctl](https://www.youtube.com/watch?v=9LoYLjDjOdg&t=2103s) from the Rawkode Academy.

There is also a new delivery scenario for the podtato-head demo from the tag-app-delivery. The scenario is however not merged yet and awaits review. The PR can be found [here](https://github.com/podtato-head/podtato-head/pull/178).

This demo is probably the best way to compare between different deployment solutions.

### Project champions

N/A

### Additional information

N/A

**Comment by codablock** [comment]
fyi, I have removed the [WIP] prefix, meaning the application is ready for review :)

**Comment by dims** [comment]
thanks for the submission, especially calling out `I'm contributing 99% of the code at the moment`, do you have thoughts already on how to get more people interested in contributing to the project?

**Comment by codablock** [comment]
@dims I assume that user adoption will automatically lead to contributions, so this is what the project actually needs to focus on at the moment. This part however turns out to be quite hard due to me being alone in promoting it. Getting some help in that regard would be great, but it would require people from the CNCF to actually try out the project.

**Comment by TheFoxAtWork** [comment]
@codablock beyond user adoption, demoing and discussing the project with one of the TAGs may be beneficial as well. In particular, TAGs may have good indicators of problem areas adopters face, understanding these could help you highlight the aspects of this project that meet or exceed those problems while introducing the project to a broader audience. For this project, [TAG App Delivery](https://github.com/cncf/toc/blob/main/tags/app-delivery.md) would have the best alignment.

**Comment by TheFoxAtWork** [comment]
Recommend we '[Postpone](https://github.com/cncf/sandbox/#postponed)' this and have the project present to TAG App Delivery for feedback, increase awareness, and receive more contributions. Also recommend reaching out to TAG Contributor Strategy for methods to increase contribution.

**Comment by joshgav** [comment]
Thanks @TheFoxAtWork. `kluctl` was presented on Nov 16, 2022 but unfortunately I wasn't there and it wasn't written up; notes and recording follow though. @AloisReitbauer @thschue can you share your thoughts from that session?

I'd be happy to chat with @codablock again, reach out to us in Slack to schedule another time.

- Notes: https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit#heading=h.hcnbl15gz93v
- Recording: https://www.youtube.com/watch?v=VGk5-tug6UU

**Comment by mattfarina** [comment]
@joshgav Thanks for providing those pointers.

@codablock Thank you for your submission. As you called out, you have contributed 99% of the code. We would like there to be more contributors to the project so that it is no longer a one person project. This is a common piece of feedback from the TOC. Adding more regular contributors will help here.

**Comment by TheFoxAtWork** [comment]
Definitely - reaching out to TAG Contributor Strategy will help here to, CC @CathPag , @jberkus, @geekygirldawn

**Comment by codablock** [comment]
@TheFoxAtWork @mattfarina I'm fine with postponing this and actually closing this issue. I'll reconsider a new CNCF application in the future if I feel the project is ready. So, feel free to close this issue.

Regarding the presentation to TAG App Delivery, I already did this in November last year, as mentioned by Josh. I will contact you @joshgav again to get a new slot where you can attend.

**Comment by codablock** [comment]
Closing this and will re-open (or create a new issue?) when the time comes.

**Comment by TheFoxAtWork** [comment]
Hey @codablock check out [returning-for-review-after-being-postponed](https://github.com/cncf/sandbox#returning-for-review-after-being-postponed) for info. (in short you will reopen it)
