### ISSUE TITLE
[Sandbox] Iter8

### ISSUE THREAD

**Issue by kalantar** [cncf/sandbox#84]
### Application contact emails

kalantar@us.ibm.com, alan.cha1@ibm.com, spartha@us.ibm.com

### Project Summary

Iter8 makes it easy to ensure that Kubenetes applications and ML models perform well and maximize business value.

### Project Description

Iter8 is the Kubernetes release optimizer built for DevOps, MLOps and data science teams. It makes it easy to ensure that Kubernetes applications and ML models perform well and maximize business value. In particular, Iter8 provides mechanisms that simplify all types of application and model testing -- blue-green, canary, A/B/n and performance. It automatically and dynamically reconfigures routing resources to support application transparent blue-green and canary testing as part of application/model release. It provides a client SDK to support A/B testing of backend components. Finally, it provides composable tasks to enable rapid creation of performance tests. These techniques are integrated into Iter8.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/iter8-tools

### Project repo URL in scope of application

https://github.com/iter8-tools/iter8

### Additional repos in scope of the application

Documentation
- https://github.com/iter8-tools/docs

### Website URL

https://iter8.tools

### Roadmap

https://iter8.tools/1.1/roadmap/

### Contributing Guide

https://github.com/iter8-tools/iter8/blob/master/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/iter8-tools/iter8/blob/master/CODE_OF_CONDUCT.md

### Adopters

https://github.com/iter8-tools/iter8/blob/master/ADOPTERS.md

### Contributing or Sponsoring Org

https://www.ibm.com

### Maintainers file

https://github.com/iter8-tools/iter8/blob/master/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Iter8 seeks a vendor-neutral home that will offer the opportunity for greater project awareness, adoption, and contributions. Iter8 will also benefit from CNCF's guidance on best practices and governance.

### Benefit to the Landscape

Iter8 benefits the CNCF landscape by adding a tool that simplifies testing. Different types of testing require different approaches. Iter8 brings these approaches together in  a single tool. A common testing approach simplifies adoption, ensuring user applications and models are of high quality.

### Cloud Native 'Fit'

Iter8 fits in the category *Continuous Integration & Delivery*. Its suite of testing capabilities can be used by other CI/CD tools.

### Cloud Native 'Integration'

As noted above, Iter8 complements Continuous Integration & Delivery projects. Iter8 provides a set of tools that enable various forms of testing which can used as part of CI/CD.

To implement blue-green and canary testing, Iter8 depends on a service mesh. Iter8 works natively with the Kubernetes gateway API supported by, for example, graduated projects Istio and Linkerd.

To simplify user interaction and configuration, Iter8 uses Helm.

### Similar projects

[Flagger](https://flagger.app/) (sub-project of Flux) and [Argo Rollouts](https://argo-rollouts.readthedocs.io/en/stable/) share similarities with Iter8. Both provide support for advanced application rollout on Kubernetes with blue-green and canary analysis. They work with many service meshes and ingress products to provide this support. Users specify the desired rollout using a Kubernetes custom resource.
    
Iter8 was heavily inspired by both projects. However, Iter8 differs in several regards. With Iter8:
    
- Applications can be composed of any Kubernetes resource type. For example, it works with machine learning applications built using KServe `InferenceService` resources out of the box. To do so, Iter8 allows the user to specify the resources being deployed as part of the specification of the rollout instead of assuming a particular pattern.
    
- Users can A/B/n test application backend components. Beyond providing HTTP header and cookie-based routing, Iter8 provides a client SDK with a simple API that allows users to write frontend components designed to focus A/B/n testing on the backend components.
    
- No custom resource is required to specify rollouts. Both Flagger and Argo Rollouts require the user to install and use a custom resource definition to define rollouts. In Iter8, users simply specify rollouts using Helm configuration files.

### Landscape

no

### Business Product or Service to Project separation

N/A

### Project presentations

[Technical Introduction](https://youtu.be/r1JtJQZ8PG4?si=5rXD8tk04tbdO8kF)

### Project champions

TBD

**Comment by angellk** [comment]
@amye we believe this should be TAG App Delivery - could you please re-label?

**Comment by kalantar** [comment]
> @amye we believe this should be TAG App Delivery - could you please re-label?

@amye (or someone else), could this be done?

**Comment by amye** [comment]
Adding both, trying to get more TAGs engaged in process

**Comment by angellk** [comment]
@kalantar Please confirm Iter8 will be available to present on April 17 in TAG App Delivery? (thank you for understanding the move from last meeting)

**Comment by kalantar** [comment]
> @kalantar Please confirm Iter8 will be available to present on April 17 in TAG App Delivery? (thank you for understanding the move from last meeting)

@angellk Unfortunately, I find that I will not be able to attend the meeting on April 17. I've reschedule for mid May instead if that is ok.

**Comment by jberkus** [comment]
What was the result of the TAG meeting?  Please add notes.

**Comment by jberkus** [comment]
TAG-CS review, the project has:

- 3 maintainers from IBM
- A fairly complete Contributing document
- No documented governance

**Comment by kalantar** [comment]
[Recording of presentation to TAG](https://youtu.be/8E316JEe3HY?si=Ker2sDeQqyXZmgiN&t=2720)

**Comment by angellk** [comment]
@kalantar thank you for submitting an application for CNCF Sandbox! The TOC would like to see more contributors and project growth. Please coordinate with your company's OSPO and/or discuss with TAG Contributor Strategy ways to grow your contributor base and re-apply to CNCF Sandbox in 6 months.
