### ISSUE TITLE
[Sandbox] Shipwright

### ISSUE THREAD

**Issue by qu1queee** [cncf/sandbox#85]
### Application contact emails

encalada@de.ibm.com
schwarzs@de.ibm.com
adam.kaplan@redhat.com

### Project Summary

An extensible framework for building container images on Kubernetes.

### Project Description

Shipwright is designed to make it easy to build container images securely and reliably. The community is rooted in the fundamental principles of simplicity, flexibility, and security. Shipwright is currently an incubating project under the Continuous Delivery Foundation (a subsidiary of the Linux Foundation).

This project introduces a layer of standardisation across many of today's build tools (_such as Kaniko, ko or Buildpacks_). By abstracting the complexity of today's build processes, Shipwright establishes a common layer within Kubernetes, that can work across multiple tools and runtimes.

In essence, Shipwright empowers developers and organisations to easily build container images, leveraging their preferred build tools with the confidence of adhering to security best practices. Shipwright extensible and pluggable nature, makes it an invaluable asset for integration into existing Kubernetes components or CI/CD systems.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://github.com/shipwright-io

### Project repo URL in scope of application

N/A

### Additional repos in scope of the application

N/A

### Website URL

https://shipwright.io

### Roadmap

https://github.com/shipwright-io/build/blob/main/ROADMAP.md

### Contributing Guide

https://github.com/shipwright-io/.github/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/shipwright-io/.github/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/shipwright-io/build/blob/main/ADOPTERS.md

### Contributing or Sponsoring Org

https://www.ibm.com/, https://www.redhat.com/ . Contributors are primarily employees from IBM and RedHat. Project Shipwright is already a vendor-neutral Linux Foundation Project, incubating inside the Continuous Delivery Foundation.

### Maintainers file

https://github.com/shipwright-io/build/blob/main/OWNERS

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

Shipwright is currently an incubating project within the Continuous Delivery Foundation (CDF). After further evaluation, we believe the project is more closely aligned with the CNCF. We are confident the CNCF will help us increase community contributions and adoption, and foster closer collaboration with our mutual project dependencies.

The goals of our project align with the CNCF Sandbox goals and with CNCF's mission by addressing key challenges in the Cloud Native space related to application delivery. Shipwright empowers organisations to build and run scalable applications in today's diverse cloud environments.

### Benefit to the Landscape

In the evolving landscape of today's Cloud Native ecosystem, developers encounter a multitude of build tools for creating container images. Project Shipwright addresses this variety by introducing standardisation across multiple CNCF build tools, promoting their adoption through an extensible declarative API accessible to both developers and organisations.

This standardisation can be consumed by other projects that aim to provide a unique experience when building and deploying applications, using Shipwright as a fundamental building block.

In addition, Project Shipwright aims to provide throughout the same declarative API, today's Supply Chain Security Best Practices.

### Cloud Native 'Fit'

Shipwright is build with and for Cloud Native technologies, fitting into the Application Definition & Image Build category.

### Cloud Native 'Integration'

We complement the following projects:

- OpenFunction
    - How? 
        - Uses Shipwright as a Building Block
- Tekton
    - How?
        - Can integrate Shipwright inside a Tekton Pipeline, as the building block.

We depend on the following projects:

- ko
    - How?
        - Shipwright can use `ko` to delegate the mechanism of building a container image.
- Buildpacks
    - How?
        - Shipwright can use Buildpacks to delegate the mechanism of building a container image.
- Kaniko
    - How?
        - Shipwright can use Kaniko to delegate the mechanism of building a container image.
- Tekton
    - How?
        - Shipwright uses Tekton to achieve the sequential execution of containers inside a Kubernetes Pod, plus other Tekton features.

### Cloud Native Overlap

None.

### Similar projects

N/A

### Landscape

Yes.

### Business Product or Service to Project separation

N/A

### Project presentations

N/A

### Project champions

- Karena Angell
- Derek Carr

### Additional information

Our decision to contribute the project to CDF was primarily driven by its integration with Tekton, Shipwright is built on Tekton, a CDF project since its inception. However, we anticipate that this association will become less influential over time, especially in light of Tekton's departure from CDF and the growing number of CNCF projects used by or that rely on Shipwright.

**Comment by angellk** [comment]
@qu1queee are you available April 3 to present to TAG App Delivery?

**Comment by pgonin** [comment]
Interestingly, Kaniko is also candidate https://github.com/cncf/sandbox/issues/88

**Comment by angellk** [comment]
@qu1queee we'd like to move your presentation from 4/3 to 3/6 (this coming wednesday) - are you available?

**Comment by qu1queee** [comment]
We will give an introduction on the Project to the TAG App delivery on 3rd of April. Just for the record.

**Comment by TheFoxAtWork** [comment]
@lianmakesthings - Does TAG App Delivery have a recommendation on this project?

**Comment by rchincha** [comment]
Here is my evaluation (fwiw):

The build process is now cloud-native (k8s CRDs) 
https://shipwright.io/docs/#build
which I think is pretty neat.

What are the competing proposals or existing solutions though?
For example, does tekton have its own build job CRDs etc?

**Comment by schristoff** [comment]
## Shipwright review
The Shipwright project had a presentation for TAG App Delivery at our meeting held April 3rd, 2023. The project was presented by Adam Kaplan. The TAG leadership was represented by Lian Li, Karena Angell, Alois Reitbauer

[Recording of the meeting](https://youtu.be/dkN_MfkiiSA?si=rscJS2RS-rbdJMsT)
Meeting notes: [CNCF TAG App Delivery Meeting Notes](https://docs.google.com/document/d/1OykvqvhSG4AxEdmDMXilrupsX2n1qCSJUWwTc3I7AOs/edit?usp=sharing)

## Project Summary
### History
Shipwright is looking to move from the CDF to the CNCF. It runs on Tekton, like a swiss army knife, and has a direct dependency on Tekton. 
Architecture
Project is written primarily Golang 
It has a direct dependency on Tekton
When creating a build, it creates a Tekton task
In the future it could look to decouple and support something like Argo Workflows 
Goals & Roadmap

Need to clarify if Tekton is a hard dependency and roadmap
Additional Signatures
Additional provenance
Shipwright could correct some gaps in Tekton
Multi-arch
Project called Triggers
Integrate with Tekton custom tasks feature
Expose shipwright API to build custom tasks
Appropriate chain of owner

## Key Considerations:
### Community and Growth

Currently all issues stem from June (two months ago) - there seems to be about three core maintainers ([1](https://github.com/SaschaSchwarze0), [2](https://github.com/qu1queee), [3](https://github.com/HeavyWombat)) all from IBM. 


### TAG Recommendation to TOC
Currently the project is tied strongly to Tekton, which is a CDF project - and with maintainers primarily from IBM. We would ideally like to see Shipwright collaborate more with CNCF projects and have a more diverse set of maintainers. Currently voting "yes"

**Comment by xmulligan** [comment]
TAG Contributor strategy has reviewed this project and found the following:

* The [contributor guide](https://github.com/shipwright-io/.github/blob/main/CONTRIBUTING.md) is basic.
* There is currently no written governance beyond an [OWNERS file](https://github.com/shipwright-io/build/blob/main/OWNERS)
* The [roadmap](https://github.com/shipwright-io/build/blob/main/ROADMAP.md) was created 7 months ago and defines a few high level directions
* There are 5 [approves](https://github.com/shipwright-io/build/blob/main/OWNERS), who all work for IBM/RedHat
* The project doesn't currently require a CLA or DCO
* The project also references Kubernetes documentation for how things work in the project instead of using K8s as a template to write their own governance documentation, see [OWNERS](https://github.com/shipwright-io/build/blob/main/OWNERS) as an example

This review is for the TOC’s information only.  Sandbox projects are not required to have full governance or contributor documentation.

**Comment by donaldliu** [comment]
Found this:
[[shipwright-dev] Proposal: Moving Shipwright to CNCF](https://lists.shipwright.io/archives/list/shipwright-dev@lists.shipwright.io/message/32RELKJ6JKPRLVOE7FJA52WG5POYQKMA/)

**Comment by adambkaplan** [comment]
@donaldliu @mauilion :+1: that email is the authoritative proposal to start the move. It links back to the community meeting minutes that prompted the proposal.

We also tracked the sandbox application work in https://github.com/shipwright-io/community/issues/178.

**Comment by Cmierly** [comment]
Welcome and congrats on getting accepted as a CNCF Sandbox project!

You can get started on your on-boarding checklist here: https://github.com/cncf/toc/issues/1414

and if you have any questions, please don't hesitate to reach out!

**Comment by qu1queee** [comment]
Hello @Cmierly, we're really excited to join the CNCF Foundation! I'll follow up with my peers to coordinate the next steps.

**Comment by mrbobbytables** [comment]
With https://github.com/cncf/toc/issues/1414 created, we can go ahead and close this out :)

Congrats again!
