### ISSUE TITLE
[Sandbox] etcd-operator

### ISSUE THREAD

**Issue by kvaps** [cncf/sandbox#91]
### Application contact emails

etcd-operator-dev@googlegroups.com

### Project Summary

New generation community-driven etcd-operator! 

### Project Description

New generation community-driven etcd-operator!

etcd-operator is a project aimed at simplifying the deployment and management of the etcd clusters within a Kubernetes environment. It simplifies operations such as deployment, scaling, and disaster recovery through Kubernetes custom resources, enabling easy configuration and management via YAML files.

The etcd-operator is designed for developers and operators looking for a robust solution to handle etcd clusters as part of their Kubernetes applications, offering reliability and ease of use for dynamic, distributed systems.

### Org repo URL (provide if all repos under the org are in scope of the application)

https://aenix.io/

### Project repo URL in scope of application

https://github.com/aenix-io/etcd-operator

### Website URL

https://etcd.aenix.io/

### Roadmap

https://github.com/orgs/aenix-io/projects/1

### Contributing Guide

https://github.com/aenix-io/etcd-operator/blob/main/CONTRIBUTING.md

### Code of Conduct (CoC)

https://github.com/aenix-io/etcd-operator/blob/main/CODE_OF_CONDUCT.md

### Adopters

https://github.com/aenix-io/etcd-operator/blob/main/ADOPTERS.md

### Maintainers file

https://github.com/aenix-io/etcd-operator/blob/main/MAINTAINERS.md

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

We have a large Kubernetes community where 10,000 people are constantly engaging. Our attempt to develop a collaborative project and bring it into the CNCF is an effort to get closer to our Western friends. We embrace open source and aspire to adopt best practices. If we receive support from the CNCF and the Kubernetes community, we would be immensely grateful.

CNCF sponsors open-source projects, and we aspire to become something greater. We aim to collaborate with the entire world towards creating common good. Because most of us believe that becoming part of the CNCF is a significant achievement.

### Benefit to the Landscape

Every startup typically begins its journey by developing its own etcd-operator (just a joke). However, there are several existing solutions, the majority of which have been abandoned and do not function as intended.

We decided to conduct an experiment within the Russian-speaking Kubernetes community and were surprised to receive a significant amount of responses. Currently, we have 10 active contributors who are contributing a lot, we made a first version, set-up a roadmap.

We aim to provide informational and organizational support as many projects require a stable etcd-operator. Some potential candidates include:

-  Cozystack
-  Kamaji
-  Cilium
-  Mayastor
-  Vitastor
-  Stolon
-  Patroni
-  Goteleport
-  LINSTOR

### Cloud Native 'Integration'

We applied to donate Cozystack to be CNCF project as well (see: https://github.com/cncf/sandbox/issues/87)
It will use this etcd-operator to run tenant Kubernetes clusters as a containers

### Similar projects

Competing projects and operators:

- [coreos/etcd-operator](https://github.com/coreos/etcd-operator) - not supported, not intended for persistent data storage.
- [gardener/etcd-druid](https://github.com/gardener/etcd-druid) - another implementation tightly coupled with Gardener.
- [clastix/kamaji-etcd](https://github.com/clastix/kamaji-etcd) - works decently, but it's a Helm chart, not an operator. I suggest using its logic as a basis.
- [aenix-io/kubernetes-in-kubernetes](https://github.com/aenix-io/kubernetes-in-kubernetes) - etcd here is part of the Kubernetes Helm chart, based on static manifests generated by kubeadm. This is also a Helm chart, not an operator, and it's abandoned.
- [improbable-eng/etcd-cluster-operator](https://github.com/improbable-eng/etcd-cluster-operator) - abandoned.
- [elemir/etcdops](https://github.com/elemir/etcdops) - a project by Evgeny Omelchenko, abandoned.

### Landscape

No

### Business Product or Service to Project separation

We don't have a business product. This is purely a community project. We envision that everyone will be able to use it for their own purposes.

**Comment by cblecker** [comment]
Hello TOC,

Wearing my hat as a maintainer of the Kubernetes project and GitHub Admin for the project.

The owners of this repo have not only applied to the CNCF Sandbox here, but also to move the repository into the auspices of the Kubernetes project under either the etcd or cluster lifecycle special interest groups.

I've recommended that they speak to the Kubernetes SIGs involved to weigh where the right place to house something like this might be as it seems there might be some confusion as to the process and the trade offs associated with each option.

The Kubernetes project will be tracking status here for the time being: https://github.com/kubernetes/community/pull/7796#issuecomment-2016526917

Until those discussions happen I'm not sure it's worthwhile processing this application, but I leave that to your discretion.

Cheers,
Christoph

**Comment by dims** [comment]
@cblecker thank you! will not review this until we hear back from you all.

**Comment by kvaps** [comment]
I apologize for the confusion, it looks like Kubernetes-SIGs is the right place for this project.
I'll close this application for now to avoid further confusion.

/close
