### ISSUE TITLE
[Sandbox] Reloader

### ISSUE THREAD

**Issue by karl-johan-grahn** [cncf/sandbox#98]
### Application contact emails

karl.johan@stakater.com

### Project Summary

A Kubernetes controller to watch changes in ConfigMap and Secrets and do rolling upgrades on Pods with their associated Deployment, StatefulSet, DaemonSet and DeploymentConfig

### Project Description

The problem Reloader addresses is that you would like to watch if some change happens in a ConfigMap or Secret, and then perform a rolling upgrade on the relevant DeploymentConfig, Deployment, Daemonset, Statefulset, and Rollout. Reloader can watch changes in ConfigMap and Secret objects and do rolling upgrades on Pods with their associated DeploymentConfigs, Deployments, Daemonsets, Statefulsets, and Rollouts.

### Org repo URL (provide if all repos under the org are in scope of the application)

Only Reloader is applicable for this application in the stakater GitHub organization.

### Project repo URL in scope of application

https://github.com/stakater/reloader/

### Website URL

https://docs.stakater.com/reloader/

### Roadmap

https://github.com/orgs/stakater/projects/4

### Roadmap context

The roadmap is continuously updated through the GitHub project

### Contributing Guide

https://github.com/stakater/Reloader#contributing

### Code of Conduct (CoC)

https://github.com/stakater/Reloader/blob/master/CODE_OF_CONDUCT.md

### Contributing or Sponsoring Org

Stakater

### Maintainers file

https://github.com/stakater/Reloader/blob/master/MAINTAINERS

### IP Policy

- [X] If the project is accepted, I agree the project will follow the CNCF IP Policy

### Trademark and accounts

- [X] If the project is accepted, I agree to donate all project trademarks and accounts to the CNCF

### Why CNCF?

The CNCF can provide the project with wider adoption and community collaboration, further simplifying and enhancing updates of Kubernetes resources when secrets or configurations change in Kubernetes environments.

### Benefit to the Landscape

Reloader uniquely addresses the problem of doing rolling updates of Kubernetes resources when configurations or secrets change.

### Cloud Native 'Fit'

Reloader has become integral to thousands of Kubernetes deployments since it serves a fundamental architectural gap. It is built on Go and fits well into cloud-native by being fully focused on Kubernetes.

### Cloud Native 'Integration'

Reloader integrates closely with Kubernetes.

### Cloud Native Overlap

Small overlap with https://github.com/fabric8io/configmapcontroller which hasn't been updated in the last five years.

### Similar projects

[configmapcontroller](https://github.com/fabric8io/configmapcontroller)

### Landscape

No

### Business Product or Service to Project separation

Stakater Reloader is available in an open-source version as well as an Enterprise version. The functionality is currently the same for both the open-source version and the Enterprise version.

The Reloader Enterprise version is different from the open-source version in that it is:

* Security-hardened
  * Certified by Stakater - an internal certification process that includes:
    * Quality assurance from code perspective
    * Quality assurance from supply chain perspective
    * Certified images is published to a private registry, which you gain access to with the
purchase
* Delivered with dedicated support
* Delivered with dedicated resources to prioritize implementation of unique feature requests
  * All unique feature requests will still be open-sourced, but delivery will be prioritized

**Comment by mnm678** [comment]
Please open a [presentation issue](https://github.com/cncf/tag-security/issues/new/choose) with TAG security so that we can provide the TAG review. It may be useful to perform a [self assessment](https://github.com/cncf/tag-security/blob/main/community/assessments/guide/self-assessment.md) before the presentation.

**Comment by TheFoxAtWork** [comment]
Some questions:
* The repo appears to be some less active, not many changes occurring. Is this project near feature complete/stable?
* what is stakater-user in relation to this repo?
* When is SHA1 going to be replaced with SHA2? SHA1 was deprecated in 2011.
* The project roadmap doesnt detail much future direction for the project, are there plans to extend the project beyond its current capabilities?


Actions:
* please complete the remaining fields on the application, 
   * the business product and service separation as the project's repo indicates enterprise level support available by the same name.
   * Cloud native fit needs completed.

**Comment by rchincha** [comment]
Don't Kubernetes' default controller already do what is described here? What additional functionality is being added/proposed? Other triggers other than k8s image field? How are reverts happening etc.

**Comment by jberkus** [comment]
TAG Contributor strategy has reviewed this project and found the following:

* The [contributor guide](https://github.com/stakater/Reloader#contributing) is basic.
* The project has no written governance, yet.
* The [roadmap](https://github.com/orgs/stakater/projects/4/views/1) is a Github project board and appears to be very new.
* There are 5 [maintainers](https://github.com/stakater/Reloader/blob/master/MAINTAINERS), whose employer affiliation is not clear.  Two of these maintainers appear to be currently active.
* The project is at least 6 years old.

This review is for the TOC’s information only.  Sandbox projects are not required to have full governance or contributor documentation.

**Comment by mrbobbytables** [comment]
Project has been given the okay to move to a vote in [today's sandbox review](https://github.com/cncf/toc/issues/1427)
/vote

**Comment by karl-johan-grahn** [comment]
> Actions:
> 
> * please complete the remaining fields on the application, in particular:
>   
>   * the business product and service separation as the project's repo indicates enterprise level support available by the same name.
>   * Cloud native fit

Done

**Comment by karl-johan-grahn** [comment]
> Don't Kubernetes' default controller already do what is described here? What additional functionality is being added/proposed? Other triggers other than k8s image field? How are reverts happening etc.

No, it's not about images and reverts, Reloader is about watch changes in ConfigMap and Secrets and do rolling upgrades on Pods with their associated Deployment, StatefulSet, DaemonSet and DeploymentConfig. Reloader watches changes in configmaps and secrets data. As soon as it detects a change in these. It forwards these objects to an update handler which decides if and how to perform the rolling upgrade.

**Comment by karl-johan-grahn** [comment]
> * There are 5 [maintainers](https://github.com/stakater/Reloader/blob/master/MAINTAINERS), whose employer affiliation is not clear.  Two of these maintainers appear to be currently active.

All maintainers have a Stakater email, how is the employer affiliation not clear? Four of the maintainers are currently active, how can you deem the other ones inactive?

**Comment by mrbobbytables** [comment]
gitvote has a bug keeping it at 0% voted, however manually looking at it with 9/11 TOC members voting against, its at 81%
I am going to go ahead  and cease the vote and close out the issue.

/vote-close

**Comment by jberkus** [comment]
> > * There are 5 [maintainers](https://github.com/stakater/Reloader/blob/master/MAINTAINERS), whose employer affiliation is not clear.  Two of these maintainers appear to be currently active.
> 
> All maintainers have a Stakater email, how is the employer affiliation not clear? Four of the maintainers are currently active, how can you deem the other ones inactive?

I do not have any of the maintainers emails; they are not listed in the Maintainers file.

Activity was based on the [Github Contributors chart](https://github.com/stakater/Reloader/graphs/contributors).  I do not have access to better-resolution data than this.

**Comment by MuneebAijaz** [comment]
hi @jberkus , 
Little maintainer of Reloader project here. 👋 
Just to clarify, here are the emails mentioned for the maintainers, mine for example `muneeb@stakater.com` : 
https://github.com/stakater/Reloader/blob/master/MAINTAINERS#L4
And our assumption was that `@stakater.com` at the end of the emails would clarify the affiliation. Do let us know if CNCF requires a specific format to be followed in such cases. 

On a second note, I'd appreciate some clarification around:
- Reason of project getting rejected as a sandbox project, and should we apply for a different maturity level
- Any particular action items that we missed (I acknowledge us not being able to focus on presentation before voting, and SHA1 being an issue). Is there any doc that was supposed to be followed, but was missed? 
- How long should we wait to apply again, if it's even possible?

**Comment by TheFoxAtWork** [comment]
@MuneebAijaz 

The TOC reviewed the project and moved it to a vote. The TOC's decision to not include the project in the CNCF is not indicative of application to a different maturity level, rather that the TOC did not find sufficient novelty/experimentation and viability of the project to become a cloud native project in CNCF. [You can find the discussion by the TOC on the YouTube Channel (it is the first project reviewed).](https://www.youtube.com/watch?v=yVN3fJbebuE).
